/**
 * Which focus-map outlines come from geoBoundaries rather than Natural Earth.
 *
 * GENERATED by build-hires-admin1.cjs on 2026-09-24 — do not edit by hand;
 * change the script and re-run it.
 *
 * geoBoundaries (Runfola et al., 2020, "geoBoundaries: A global database of
 * political administrative boundaries", PLoS ONE 15(4)). Each entry keeps
 * the licence of its own source - CC BY 4.0 for the Sentinel-2 tracings, the
 * ODbL for OpenStreetMap, and CC BY-SA, CC BY, CC0 or public domain for
 * national mapping - and a share-alike file stays under its licence. The
 * page names the licence of the place in view.
 */
export const GEOBOUNDARIES_URL = "https://www.geoboundaries.org/";

export const ADMIN1_SOURCES: Record<
  string,
  {
    level: "ADM0" | "ADM1";
    source: string;
    license: string;
    year: string;
    /** As the map caption shows them. */
    sourceShort: string;
    licenseShort: string;
  }
> = {
  "MT": {
    "level": "ADM1",
    "source": "geoBoundaries, d-maps.com",
    "license": "Public Domain",
    "year": "2022",
    "sourceShort": "geoBoundaries, d-maps.com",
    "licenseShort": "Public Domain"
  },
  "SG": {
    "level": "ADM1",
    "source": "Urban Redevelopment Authority, derived from ADM 3",
    "license": "Open Data Commons Open Database License 1.0",
    "year": "2016",
    "sourceShort": "Urban Redevelopment Authority, derived from ADM 3",
    "licenseShort": "ODbL 1.0"
  },
  "BH": {
    "level": "ADM1",
    "source": "OpenStreetMap, Wambacher",
    "license": "Open Data Commons Open Database License 1.0",
    "year": "2017",
    "sourceShort": "OpenStreetMap",
    "licenseShort": "ODbL 1.0 (© OpenStreetMap contributors)"
  },
  "MU": {
    "level": "ADM1",
    "source": "geoBoundaries, OpenStreetMap",
    "license": "Open Data Commons Open Database License 1.0",
    "year": "2017",
    "sourceShort": "OpenStreetMap",
    "licenseShort": "ODbL 1.0 (© OpenStreetMap contributors)"
  },
  "CV": {
    "level": "ADM1",
    "source": "OpenStreetMap, Wambacher",
    "license": "Open Data Commons Open Database License 1.0",
    "year": "2017",
    "sourceShort": "OpenStreetMap",
    "licenseShort": "ODbL 1.0 (© OpenStreetMap contributors)"
  },
  "SC": {
    "level": "ADM1",
    "source": "Digitizedhttps, Digitizedhttps",
    "license": "Creative Commons Attribution-ShareAlike 3.0 Unported",
    "year": "2018",
    "sourceShort": "geoBoundaries",
    "licenseShort": "CC BY-SA 3.0"
  },
  "ST": {
    "level": "ADM1",
    "source": "OpenStreetMap, Wambacher",
    "license": "Open Data Commons Open Database License 1.0",
    "year": "2017",
    "sourceShort": "OpenStreetMap",
    "licenseShort": "ODbL 1.0 (© OpenStreetMap contributors)"
  },
  "KM": {
    "level": "ADM1",
    "source": "OpenStreetMap, Wambacher",
    "license": "Open Data Commons Open Database License 1.0",
    "year": "2017",
    "sourceShort": "OpenStreetMap",
    "licenseShort": "ODbL 1.0 (© OpenStreetMap contributors)"
  },
  "WS": {
    "level": "ADM1",
    "source": "Wikipedia",
    "license": "Creative Commons Attribution-ShareAlike 3.0 Unported",
    "year": "2018",
    "sourceShort": "Wikipedia",
    "licenseShort": "CC BY-SA 3.0"
  },
  "TO": {
    "level": "ADM1",
    "source": "OpenStreetMap, Wambacher",
    "license": "Open Data Commons Open Database License 1.0",
    "year": "2017",
    "sourceShort": "OpenStreetMap",
    "licenseShort": "ODbL 1.0 (© OpenStreetMap contributors)"
  },
  "KI": {
    "level": "ADM1",
    "source": "OpenStreetMap, Wambacher",
    "license": "Open Data Commons Open Database License 1.0",
    "year": "2017",
    "sourceShort": "OpenStreetMap",
    "licenseShort": "ODbL 1.0 (© OpenStreetMap contributors)"
  },
  "FM": {
    "level": "ADM1",
    "source": "OCHA ROP, Federated States of Micronesia Division of Statistics, 2010 Census of Population and Housing and Secretariat of the Pacific Community, Statistics for Development Division",
    "license": "Creative Commons Attribution 3.0 Intergovernmental Organisations (CC BY 3.0 IGO)",
    "year": "2019",
    "sourceShort": "OCHA ROP, Federated States of Micronesia Division of Stat…",
    "licenseShort": "CC BY 3.0 IGO"
  },
  "MH": {
    "level": "ADM0",
    "source": "OpenStreetMap, Wambacher",
    "license": "Open Data Commons Open Database License 1.0",
    "year": "2017",
    "sourceShort": "OpenStreetMap",
    "licenseShort": "ODbL 1.0 (© OpenStreetMap contributors)"
  },
  "NR": {
    "level": "ADM1",
    "source": "geoBoundaries, FreeMapViewer",
    "license": "Public Domain",
    "year": "2005",
    "sourceShort": "geoBoundaries, FreeMapViewer",
    "licenseShort": "Public Domain"
  },
  "TV": {
    "level": "ADM0",
    "source": "OpenStreetMap, Wambacher",
    "license": "Open Data Commons Open Database License 1.0",
    "year": "2017",
    "sourceShort": "OpenStreetMap",
    "licenseShort": "ODbL 1.0 (© OpenStreetMap contributors)"
  },
  "GU": {
    "level": "ADM0",
    "source": "Sentinel-2 10-Meter Land Use/LandCover",
    "license": "Creative Commons Attribution 4.0 (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "BM": {
    "level": "ADM0",
    "source": "raster2polygon from Sentinel-2 10m Land Cover where Image Year = 2021 / exclude gridcode = 1 (water) / dissolve / processed by IMB",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "FO": {
    "level": "ADM0",
    "source": "raster2polygon from Sentinel-2 10m Land Cover where Image Year = 2021 / exclude gridcode = 1 (water) / dissolve / processed by IMB",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "AG": {
    "level": "ADM1",
    "source": "geoBoundaries, Wikimedia",
    "license": "Public Domain",
    "year": "2009",
    "sourceShort": "geoBoundaries, Wikimedia",
    "licenseShort": "Public Domain"
  },
  "DM": {
    "level": "ADM1",
    "source": "geoBoundaries, Wikimedia Commons",
    "license": "Creative Commons Attribution 2.5 Generic",
    "year": "2005",
    "sourceShort": "geoBoundaries, Wikimedia Commons",
    "licenseShort": "CC BY 2.5"
  },
  "GD": {
    "level": "ADM1",
    "source": "OpenStreetMap, Wikipedia",
    "license": "Creative Commons Attribution-ShareAlike 2.0",
    "year": "2017",
    "sourceShort": "OpenStreetMap",
    "licenseShort": "CC BY-SA 2.0"
  },
  "BB": {
    "level": "ADM1",
    "source": "geoBoundaries, Wikimedia",
    "license": "Creative Commons Attribution 2.5 Generic",
    "year": "2005",
    "sourceShort": "geoBoundaries, Wikimedia",
    "licenseShort": "CC BY 2.5"
  },
  "LC": {
    "level": "ADM1",
    "source": "Wikimedia Commons, Wikimedia Commons",
    "license": "CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
    "year": "2015",
    "sourceShort": "Wikimedia Commons",
    "licenseShort": "CC0 1.0"
  },
  "VC": {
    "level": "ADM1",
    "source": "OpenStreetMap, Wambacher",
    "license": "Open Data Commons Open Database License 1.0",
    "year": "2017",
    "sourceShort": "OpenStreetMap",
    "licenseShort": "ODbL 1.0 (© OpenStreetMap contributors)"
  },
  "KN": {
    "level": "ADM1",
    "source": "OpenStreetMap",
    "license": "Creative Commons Attribution-ShareAlike 2.0",
    "year": "2021",
    "sourceShort": "OpenStreetMap",
    "licenseShort": "CC BY-SA 2.0"
  },
  "MV": {
    "level": "ADM0",
    "source": "Sentinel-2 10-Meter Land Use/LandCover",
    "license": "Creative Commons Attribution 4.0 (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "SM": {
    "level": "ADM1",
    "source": "OpenStreetMap, Wambacher",
    "license": "Open Data Commons Open Database License 1.0",
    "year": "2017",
    "sourceShort": "OpenStreetMap",
    "licenseShort": "ODbL 1.0 (© OpenStreetMap contributors)"
  },
  "LI": {
    "level": "ADM1",
    "source": "OpenStreetMap, Wambacher",
    "license": "Open Data Commons Open Database License 1.0",
    "year": "2017",
    "sourceShort": "OpenStreetMap",
    "licenseShort": "ODbL 1.0 (© OpenStreetMap contributors)"
  },
  "AD": {
    "level": "ADM1",
    "source": "geoBoundaries, Wikimedia Commons",
    "license": "Public Domain",
    "year": "2007",
    "sourceShort": "geoBoundaries, Wikimedia Commons",
    "licenseShort": "Public Domain"
  },
  "MC": {
    "level": "ADM0",
    "source": "OpenStreetMap, Wambacher",
    "license": "Open Data Commons Open Database License 1.0",
    "year": "2017",
    "sourceShort": "OpenStreetMap",
    "licenseShort": "ODbL 1.0 (© OpenStreetMap contributors)"
  },
  "CK": {
    "level": "ADM0",
    "source": "raster2polygon from Sentinel-2 10m Land Cover where Image Year = 2021 / exclude gridcode = 1 (water) / dissolve / processed by IMB",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "NU": {
    "level": "ADM0",
    "source": "raster2polygon from Sentinel-2 10m Land Cover where Image Year = 2021 / exclude gridcode = 1 (water) / dissolve / processed by IMB",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "AW": {
    "level": "ADM0",
    "source": "Sentinel-2 10m LandCover",
    "license": "Creative Commons Attribution 4.0 (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "AS": {
    "level": "ADM0",
    "source": "Sentinel-2 10-Meter Land Use/LandCover",
    "license": "Creative Commons Attribution 4.0 (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "GG": {
    "level": "ADM0",
    "source": "raster2polygon from Sentinel-2 10m Land Cover where Image Year = 2021 / exclude gridcode = 1 (water) / dissolve / processed by IMB",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "CW": {
    "level": "ADM0",
    "source": "raster2polygon from Sentinel-2 10m Land Cover where Image Year = 2021 / exclude gridcode = 1 (water) / dissolve / processed by IMB",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "KY": {
    "level": "ADM0",
    "source": "raster2polygon from Sentinel-2 10m Land Cover where Image Year = 2021 / exclude gridcode = 1 (water) / dissolve / processed by IMB",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "GI": {
    "level": "ADM0",
    "source": "raster2polygon from Sentinel-2 10m Land Cover where Image Year = 2021 / exclude gridcode = 1 (water) / dissolve / erase adm0 overlap / processed by IMB",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "IM": {
    "level": "ADM0",
    "source": "raster2polygon from Sentinel-2 10m Land Cover where Image Year = 2021 / exclude gridcode = 1 (water) / dissolve / processed by IMB",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "PF": {
    "level": "ADM0",
    "source": "raster2polygon from Sentinel-2 10m Land Cover where Image Year = 2021 / exclude gridcode = 1 (water) / dissolve / processed by IMB",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "TC": {
    "level": "ADM0",
    "source": "raster2polygon from Sentinel-2 10m Land Cover where Image Year = 2021 / exclude gridcode = 1 (water) / dissolve / processed by IMB",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "VG": {
    "level": "ADM0",
    "source": "raster2polygon from Sentinel-2 10m Land Cover where Image Year = 2021 / exclude gridcode = 1 (water) / dissolve / processed by IMB",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "VA": {
    "level": "ADM0",
    "source": "geoBoundaries, Wikimedia Commons",
    "license": "Public Domain",
    "year": "2017",
    "sourceShort": "geoBoundaries, Wikimedia Commons",
    "licenseShort": "Public Domain"
  },
  "AI": {
    "level": "ADM0",
    "source": "raster2polygon from Sentinel-2 10m Land Cover where Image Year = 2021 / exclude gridcode = 1 (water) / dissolve / processed by IMB",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "MS": {
    "level": "ADM0",
    "source": "raster2polygon from Sentinel-2 10m Land Cover where Image Year = 2021 / exclude gridcode = 1 (water) / dissolve / processed by IMB",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "SH": {
    "level": "ADM0",
    "source": "raster2polygon from Sentinel-2 10m Land Cover where Image Year = 2021 / exclude gridcode = 1 (water) / dissolve / processed by IMB",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "PN": {
    "level": "ADM0",
    "source": "Sentinel-2 10-Meter Land Use/LandCover",
    "license": "Creative Commons Attribution 4.0 (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "TK": {
    "level": "ADM0",
    "source": "raster 2 polygon from Sentinel-2 10m Land Cover where Image Year = 2022 / exclude gridcode = 1 (water) / dissolve",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2022",
    "sourceShort": "Sentinel-2 10 m land cover, 2022",
    "licenseShort": "CC BY 4.0"
  },
  "WF": {
    "level": "ADM0",
    "source": "raster2polygon from Sentinel-2 10m Land Cover where Image Year = 2021 / exclude gridcode = 1 (water) / dissolve / processed by IMB",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "BL": {
    "level": "ADM0",
    "source": "raster2polygon from Sentinel-2 10m Land Cover where Image Year = 2021 / exclude gridcode = 1 (water) / dissolve / processed by IMB",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "BQ": {
    "level": "ADM0",
    "source": "Sentinel-2 10-Meter Land Use/LandCover",
    "license": "Creative Commons Attribution 4.0 (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "GP": {
    "level": "ADM0",
    "source": "raster2polygon from Sentinel-2 10m Land Cover where Image Year = 2021 / exclude gridcode = 1 (water) / dissolve / processed by IMB",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "MQ": {
    "level": "ADM0",
    "source": "raster2polygon from Sentinel-2 10m Land Cover where Image Year = 2021 / exclude gridcode = 1 (water) / dissolve / processed by IMB",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "RE": {
    "level": "ADM0",
    "source": "raster2polygon from Sentinel-2 10m Land Cover where Image Year = 2021 / exclude gridcode = 1 (water) / dissolve / processed by IMB",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  },
  "YT": {
    "level": "ADM0",
    "source": "Sentinel-2 10-Meter Land Use/LandCover",
    "license": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "year": "2021",
    "sourceShort": "Sentinel-2 10 m land cover, 2021",
    "licenseShort": "CC BY 4.0"
  }
};
