/**
 * Each city on the Cities page: its Wikipedia article and where it is.
 *
 * GENERATED by build-city-places.cjs on 2026-10-01 — do not edit by hand;
 * change the script and re-run it.
 *
 * The position is the article's own coordinates, checked against the map's
 * city layer where that has the city by the same name.
 */
export const CITY_PLACES_SOURCE = {
  label: "Wikipedia — the coordinates of each city's article",
  url: "https://en.wikipedia.org/",
  retrieved: "2026-10-01",
};

/** City id → the title of its Wikipedia article, and its longitude and latitude. */
export const CITY_PLACES: Record<string, { wiki: string; lon: number; lat: number }> = {
  "sgp": { wiki: "Singapore", lon: 103.8333, lat: 1.2833 },
  "seo26": { wiki: "Seoul", lon: 126.99, lat: 37.56 },
  "tky26": { wiki: "Tokyo", lon: 139.6922, lat: 35.6897 },
  "sfo": { wiki: "San Francisco Bay Area", lon: -122.37, lat: 37.81 },
  "sha26": { wiki: "Shanghai", lon: 121.4692, lat: 31.2325 },
  "dxb26": { wiki: "Dubai", lon: 55.2708, lat: 25.2047 },
  "ams26": { wiki: "Amsterdam", lon: 4.8936, lat: 52.3728 },
  "tal": { wiki: "Tallinn", lon: 24.7453, lat: 59.4372 },
  "hel26": { wiki: "Helsinki", lon: 24.9375, lat: 60.1708 },
  "zur26": { wiki: "Zurich", lon: 8.5411, lat: 47.3744 },
  "cph26": { wiki: "Copenhagen", lon: 12.5683, lat: 55.6761 },
  "lon26": { wiki: "London", lon: -0.1275, lat: 51.5072 },
  "nyc26": { wiki: "New York City", lon: -74.0061, lat: 40.7128 },
  "par26": { wiki: "Paris", lon: 2.3522, lat: 48.8567 },
  "bei26": { wiki: "Beijing", lon: 116.3975, lat: 39.9067 },
  "ber26": { wiki: "Berlin", lon: 13.405, lat: 52.52 },
  "tor26": { wiki: "Toronto", lon: -79.3817, lat: 43.6525 },
  "syd26": { wiki: "Sydney", lon: 151.21, lat: -33.8678 },
  "mum26": { wiki: "Mumbai", lon: 72.8775, lat: 19.0761 },
  "sao26": { wiki: "São Paulo", lon: -46.6333, lat: -23.55 },
  "ist26": { wiki: "Istanbul", lon: 28.955, lat: 41.0136 },
  "mos26": { wiki: "Moscow", lon: 37.6178, lat: 55.7558 },
  "mex26": { wiki: "Mexico City", lon: -99.1333, lat: 19.4333 },
  "bue26": { wiki: "Buenos Aires", lon: -58.3814, lat: -34.6039 },
  "lag26": { wiki: "Lagos", lon: 3.3936, lat: 6.4561 },
  "bar26": { wiki: "Barcelona", lon: 2.1833, lat: 41.3833 },
  "vie26": { wiki: "Vienna", lon: 16.3725, lat: 48.2083 },
  "mel26": { wiki: "Melbourne", lon: 144.9631, lat: -37.8142 },
  "hk26": { wiki: "Hong Kong", lon: 114.2, lat: 22.3 },
  "fra26": { wiki: "Frankfurt", lon: 8.6822, lat: 50.1106 },
  "joh26": { wiki: "Johannesburg", lon: 28.0456, lat: -26.2044 },
  "kar26": { wiki: "Karachi", lon: 67.01, lat: 24.86 },
  "bkk26": { wiki: "Bangkok", lon: 100.4942, lat: 13.7525 },
  "mco": { wiki: "Monaco", lon: 7.42, lat: 43.7311 },
};
