/**
 * The measured state of the climate, from the agencies that measure it.
 *
 * GENERATED by build-climate-indicators.cjs on 2026-09-15 — do not edit by hand;
 * change the script and re-run it.
 *
 * Each entry is the latest reading its source publishes, the period it belongs
 * to, and the same period ten years earlier for comparison. Nothing is
 * projected or interpolated: where a series stops, it stops, and the period
 * says when that was.
 */
export const CLIMATE_RETRIEVED = "2026-09-15";

export interface ClimateIndicator {
  id: string;
  label: string;
  value: number;
  unit: string;
  /** The month or year this reading is for. */
  period: string;
  /** The same period a decade earlier, or null where the series does not reach. */
  decadeAgo: number | null;
  source: string;
  url: string;
  /** What the figure is, where that is not obvious from the label. */
  note: string | null;
}

export const CLIMATE_INDICATORS: ClimateIndicator[] = [
  {
    id: "co2",
    label: "Carbon dioxide",
    value: 429.51,
    unit: "ppm",
    period: "August 2026",
    decadeAgo: 404.41,
    source: "NOAA Global Monitoring Laboratory — Mauna Loa",
    url: "https://gml.noaa.gov/ccgg/trends/",
    note: "Seasonally adjusted trend. The raw monthly mean was 427.55 ppm; it swings through the year with the northern growing season, so the trend is what compares across months.",
  },
  {
    id: "co2-global",
    label: "Carbon dioxide, global mean",
    value: 427.62,
    unit: "ppm",
    period: "June 2026",
    decadeAgo: 403.62,
    source: "NOAA Global Monitoring Laboratory — globally averaged marine surface",
    url: "https://gml.noaa.gov/ccgg/trends/gl_trend.html",
    note: "Averaged across the global marine surface network, which runs a little behind Mauna Loa.",
  },
  {
    id: "ch4",
    label: "Methane",
    value: 1939.44,
    unit: "ppb",
    period: "May 2026",
    decadeAgo: 1842.16,
    source: "NOAA Global Monitoring Laboratory — globally averaged marine surface",
    url: "https://gml.noaa.gov/ccgg/trends_ch4/",
    note: null,
  },
  {
    id: "n2o",
    label: "Nitrous oxide",
    value: 339.82,
    unit: "ppb",
    period: "May 2026",
    decadeAgo: 328.91,
    source: "NOAA Global Monitoring Laboratory — globally averaged marine surface",
    url: "https://gml.noaa.gov/ccgg/trends_n2o/",
    note: null,
  },
  {
    id: "warming",
    label: "Surface temperature anomaly",
    value: 1.4,
    unit: "°C",
    period: "August 2026",
    decadeAgo: 1.01,
    source: "NASA GISS Surface Temperature Analysis (GISTEMP v4)",
    url: "https://data.giss.nasa.gov/gistemp/",
    note: "Measured against GISTEMP's own 1951-1980 average, which is already warmer than pre-industrial — so this is not the same number as the 1.5 °C target.",
  },
  {
    id: "aggi",
    label: "Annual greenhouse gas index",
    value: 1.538,
    unit: "× 1990",
    period: "2024",
    decadeAgo: 1.352,
    source: "NOAA Annual Greenhouse Gas Index",
    url: "https://gml.noaa.gov/aggi/aggi.html",
    note: "Heating from long-lived greenhouse gases, indexed so 1990 = 1.",
  },
  {
    id: "sea-ice",
    label: "Arctic sea ice, September",
    value: 4.75,
    unit: "million km²",
    period: "September 2025",
    decadeAgo: 4.62,
    source: "NSIDC Sea Ice Index",
    url: "https://nsidc.org/arcticseaicenews/",
    note: "September is the Arctic's annual minimum, which is why it is the month usually quoted. The 1979-1990 September average was 7.11 million km²; single years move enough that a decade-on-decade comparison can run against the trend.",
  },
];
