/**
 * The journey to work: how long it takes, and how people make it.
 *
 * GENERATED by build-commute.cjs on 2026-10-07 — do not edit by hand; change the
 * script and re-run it.
 *
 * Two official series, each for the places it covers, and nothing for the
 * rest - no body publishes the journey to work for every country on one
 * footing. They are not the same measure and are not ranked against each
 * other: Eurostat's is the mean one-way journey of employed people aged 15 to
 * 74 who travel at least a minute, from the Labour Force Survey's 2019 module;
 * the Census Bureau's is of workers 16 and over who did not work from home,
 * from the American Community Survey 2024. The Bureau's mean is its own
 * calculation - aggregate minutes over the workers who travelled - and each
 * share is a count over its table's total.
 */
export const COMMUTE_SOURCES = {
  eurostat: {
    label: "Eurostat — commuting time of employed persons, Labour Force Survey 2019 module (lfso_19plwk28)",
    url: "https://ec.europa.eu/eurostat/databrowser/view/lfso_19plwk28/default/table",
    year: "2019",
    updated: "2022-02-04",
  },
  acs: {
    label: "US Census Bureau — American Community Survey 2024, 1-year: travel time and means of transportation to work (B08013, B08301, B08303)",
    url: "https://data.census.gov/table/ACSDT1Y2024.B08301",
    year: "2024",
  },
  retrieved: "2026-10-07",
};

/** Mean minutes, one way: for the country, and for the people living in its cities, its towns and suburbs, and its rural areas. */
export type EuropeCommute = { all: number; cities?: number; towns?: number; rural?: number };

/** The European Union's 27 members together, to read a country against. */
export const COMMUTE_EU: EuropeCommute = { all: 25, cities: 27, towns: 24, rural: 24 };

/** By ISO code: 32 countries of the Labour Force Survey. */
export const COMMUTE_EUROPE: Record<string, EuropeCommute> = {
  AT: { all: 24, cities: 28, towns: 21, rural: 23 },
  BE: { all: 28, cities: 28, towns: 28, rural: 29 },
  BG: { all: 26, cities: 28, towns: 22, rural: 24 },
  CH: { all: 26, cities: 27, towns: 27, rural: 24 },
  CY: { all: 19, cities: 19, towns: 18, rural: 23 },
  CZ: { all: 27, cities: 30, towns: 25, rural: 26 },
  DE: { all: 26, cities: 28, towns: 25, rural: 25 },
  DK: { all: 26, cities: 26, towns: 27, rural: 26 },
  EE: { all: 23, cities: 23, towns: 22, rural: 24 },
  ES: { all: 25, cities: 27, towns: 22, rural: 21 },
  FI: { all: 23, cities: 25, towns: 21, rural: 22 },
  FR: { all: 26, cities: 28, towns: 25, rural: 24 },
  GB: { all: 30, cities: 30, towns: 28, rural: 29 },
  GR: { all: 20, cities: 24, towns: 19, rural: 14 },
  HR: { all: 24, cities: 27, towns: 23, rural: 23 },
  HU: { all: 29, cities: 32, towns: 28, rural: 27 },
  IE: { all: 28, cities: 29, towns: 26, rural: 27 },
  IS: { all: 15, cities: 15, towns: 16, rural: 10 },
  IT: { all: 21, cities: 24, towns: 20, rural: 20 },
  LT: { all: 23, cities: 24, towns: 21, rural: 23 },
  LU: { all: 29, cities: 24, towns: 31, rural: 31 },
  LV: { all: 33, cities: 34, towns: 32, rural: 33 },
  MT: { all: 26, cities: 24, towns: 27, rural: 31 },
  NL: { all: 27, cities: 28, towns: 25, rural: 26 },
  NO: { all: 27, cities: 26, towns: 26, rural: 28 },
  PL: { all: 24, cities: 27, towns: 23, rural: 23 },
  PT: { all: 21, cities: 24, towns: 18, rural: 17 },
  RO: { all: 27, cities: 30, towns: 26, rural: 25 },
  SE: { all: 26, cities: 27, towns: 26, rural: 26 },
  SI: { all: 23, cities: 21, towns: 22, rural: 24 },
  SK: { all: 23, cities: 23, towns: 21, rural: 24 },
  TR: { all: 23 },
};

/** Mean minutes one way, the share of journeys of an hour or more, and each way of getting to work as a share of all workers. */
export type UsCommute = { place: string; minutes: number; hourPlusPct: number; modes: [way: string, pct: number][] };

export const COMMUTE_US: UsCommute = { place: "United States", minutes: 27.2, hourPlusPct: 9.3, modes: [["Drove alone",69.2],["Carpooled",9.2],["Public transport",3.7],["Walked",2.4],["Cycled",0.5],["Taxi, motorcycle or other",1.7],["Worked from home",13.3]] };

/** By the Cities page's id: the city within its own boundary, as the Census place of its name. */
export const COMMUTE_US_CITIES: Record<string, UsCommute> = {
  nyc26: { place: "New York city", minutes: 40.6, hourPlusPct: 25.2, modes: [["Drove alone",20.6],["Carpooled",4.4],["Public transport",48.7],["Walked",9.6],["Cycled",1.7],["Taxi, motorcycle or other",2.5],["Worked from home",12.5]] },
  sfo: { place: "San Francisco city", minutes: 32.2, hourPlusPct: 13.5, modes: [["Drove alone",30.4],["Carpooled",5.9],["Public transport",25],["Walked",10],["Cycled",3.8],["Taxi, motorcycle or other",3.4],["Worked from home",21.4]] },
};
