/**
 * Economy by sector, as shares of total value added, for countries the World
 * Bank publishes no split for.
 *
 * GENERATED by build-country-sectors-un.cjs on 2026-09-19 — do not edit by hand;
 * change the script and re-run it.
 *
 * UN Statistics Division, national accounts main aggregates, "Percentage
 * Distribution (Shares) of GDP". Shares of value added, so they sum to 100
 * with no taxes-less-subsidies remainder. The UN fills gaps in national
 * reporting with its own estimates without marking which.
 */
export const UN_SECTORS_SOURCE = {
  label: "UN Statistics Division — national accounts, shares of value added",
  url: "https://unstats.un.org/unsd/snaama/",
  retrieved: "2026-09-19",
};

export interface UnSectors {
  y: string;
  agriculture: number;
  industry: number;
  services: number;
  /** Part of industry. */
  manufacturing: number | null;
}

export const UN_SECTORS: Record<string, UnSectors> = {
  "ck": { y: "2024", agriculture: 2.7, industry: 6.1, services: 91.3, manufacturing: 2.5 },
  "er": { y: "2024", agriculture: 17.3, industry: 31.3, services: 51.4, manufacturing: 6 },
  "kp": { y: "2024", agriculture: 20.9, industry: 49.3, services: 29.8, manufacturing: 20.5 },
  "nr": { y: "2024", agriculture: 2.4, industry: 36.6, services: 61, manufacturing: 19.6 },
  "so": { y: "2024", agriculture: 60.2, industry: 7.4, services: 32.5, manufacturing: 2.5 },
  "ss": { y: "2024", agriculture: 3.4, industry: 51.2, services: 45.4, manufacturing: 4.1 },
  "tv": { y: "2024", agriculture: 8.2, industry: 9.5, services: 82.2, manufacturing: 1.7 },
  "ve": { y: "2024", agriculture: 4.5, industry: 52.2, services: 43.3, manufacturing: 16.9 },
};
