/**
 * Government spending by function (COFOG), per country, keyed by ISO2 code.
 *
 * GENERATED by build-budget.cjs on 2026-09-21 — do not edit by hand; change
 * the script and re-run it. See that script for the source and method.
 */

export type BudgetDivision =
  | "GF01" | "GF02" | "GF03" | "GF04" | "GF05"
  | "GF06" | "GF07" | "GF08" | "GF09" | "GF10";

/** The ten COFOG functions, in the order the classification numbers them. */
export const BUDGET_DIVISIONS: { id: BudgetDivision; label: string }[] = [
  { id: "GF01", label: "General public services" },
  { id: "GF02", label: "Defence" },
  { id: "GF03", label: "Public order & safety" },
  { id: "GF04", label: "Economic affairs & infrastructure" },
  { id: "GF05", label: "Environmental protection" },
  { id: "GF06", label: "Housing & community" },
  { id: "GF07", label: "Health" },
  { id: "GF08", label: "Recreation, culture & religion" },
  { id: "GF09", label: "Education" },
  { id: "GF10", label: "Social protection" },
];

export interface CountryBudget {
  /** ISO 3166 alpha-3, as the IMF codes it. */
  iso3: string;
  y: string;
  /** "general": central, state and local government; "central": central only. */
  basis: "general" | "central";
  /** Each function as a percent of total government outlays. */
  shares: Record<BudgetDivision, number>;
  /** Outlays not classified by function, in percent, where material. */
  unclassified?: number;
  /** Total government outlays as a percent of GDP, same year and basis. */
  spendingPctGdp?: number;
}

export const BUDGET_SOURCE = {
  label: "IMF — Government Finance Statistics, expenditure by function (COFOG)",
  url: "https://data.imf.org/Datasets/GFS_COFOG",
};
export const BUDGET_RETRIEVED = "2026-09-21";

export const COUNTRY_BUDGET: Record<string, CountryBudget> = {
  "AF": {
    "iso3": "AFG",
    "y": "2017",
    "basis": "general",
    "shares": {
      "GF01": 5.8,
      "GF02": 36.3,
      "GF03": 19.6,
      "GF04": 19.1,
      "GF05": 0.4,
      "GF06": 1.3,
      "GF07": 4.5,
      "GF08": 0.7,
      "GF09": 8.2,
      "GF10": 4.1
    },
    "spendingPctGdp": 44.9
  },
  "AL": {
    "iso3": "ALB",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 18.9,
      "GF02": 2.9,
      "GF03": 6.6,
      "GF04": 12,
      "GF05": 0.9,
      "GF06": 6.1,
      "GF07": 9.6,
      "GF08": 1.6,
      "GF09": 10.1,
      "GF10": 31.2
    }
  },
  "AD": {
    "iso3": "AND",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 9.5,
      "GF02": 0,
      "GF03": 6.1,
      "GF04": 13.7,
      "GF05": 2.8,
      "GF06": 0.8,
      "GF07": 23.1,
      "GF08": 5.3,
      "GF09": 7.8,
      "GF10": 30.7
    },
    "spendingPctGdp": 30.7
  },
  "AE": {
    "iso3": "ARE",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 25.3,
      "GF02": 6.2,
      "GF03": 15.3,
      "GF04": 11.3,
      "GF05": 3,
      "GF06": 6.7,
      "GF07": 12.7,
      "GF08": 4.4,
      "GF09": 6.2,
      "GF10": 9
    },
    "spendingPctGdp": 21.3
  },
  "AM": {
    "iso3": "ARM",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 19.8,
      "GF02": 18.4,
      "GF03": 7.6,
      "GF04": 8.5,
      "GF05": 1.3,
      "GF06": 1.4,
      "GF07": 5.1,
      "GF08": 2.1,
      "GF09": 10.5,
      "GF10": 25.2
    },
    "spendingPctGdp": 29.2
  },
  "AU": {
    "iso3": "AUS",
    "y": "2022",
    "basis": "general",
    "shares": {
      "GF01": 9.2,
      "GF02": 5.5,
      "GF03": 4.9,
      "GF04": 13.7,
      "GF05": 2.1,
      "GF06": 1.6,
      "GF07": 20,
      "GF08": 2.1,
      "GF09": 13.9,
      "GF10": 27
    },
    "spendingPctGdp": 37.3
  },
  "AT": {
    "iso3": "AUT",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 10.8,
      "GF02": 1.2,
      "GF03": 2.7,
      "GF04": 12.9,
      "GF05": 1.3,
      "GF06": 0.7,
      "GF07": 17.2,
      "GF08": 2.3,
      "GF09": 9.6,
      "GF10": 41.3
    },
    "spendingPctGdp": 56.2
  },
  "AZ": {
    "iso3": "AZE",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 12.8,
      "GF02": 13.8,
      "GF03": 7.4,
      "GF04": 24.4,
      "GF05": 0.8,
      "GF06": 0.8,
      "GF07": 4.1,
      "GF08": 1.2,
      "GF09": 10.4,
      "GF10": 24.4
    },
    "spendingPctGdp": 35.3
  },
  "BE": {
    "iso3": "BEL",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 13.1,
      "GF02": 2.4,
      "GF03": 3.2,
      "GF04": 11.9,
      "GF05": 2.1,
      "GF06": 0.7,
      "GF07": 14.8,
      "GF08": 2.3,
      "GF09": 11.7,
      "GF10": 37.8
    },
    "spendingPctGdp": 54.6
  },
  "BG": {
    "iso3": "BGR",
    "y": "2023",
    "basis": "general",
    "shares": {
      "GF01": 8.1,
      "GF02": 3.8,
      "GF03": 6.7,
      "GF04": 14.8,
      "GF05": 1.8,
      "GF06": 2.6,
      "GF07": 14.2,
      "GF08": 2,
      "GF09": 10.5,
      "GF10": 35.6
    },
    "spendingPctGdp": 38.8
  },
  "BY": {
    "iso3": "BLR",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 8.7,
      "GF02": 3.3,
      "GF03": 6.1,
      "GF04": 15.1,
      "GF05": 0.3,
      "GF06": 6.7,
      "GF07": 12.7,
      "GF08": 2.9,
      "GF09": 12.8,
      "GF10": 31.5
    },
    "spendingPctGdp": 43
  },
  "BR": {
    "iso3": "BRA",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 24.2,
      "GF02": 1.1,
      "GF03": 6.5,
      "GF04": 4.9,
      "GF05": 1.2,
      "GF06": 3,
      "GF07": 11,
      "GF08": 0.9,
      "GF09": 11.1,
      "GF10": 36.1
    },
    "spendingPctGdp": 45.8
  },
  "CA": {
    "iso3": "CAN",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 14,
      "GF02": 2.3,
      "GF03": 4.5,
      "GF04": 8.8,
      "GF05": 3.2,
      "GF06": 1.4,
      "GF07": 21.9,
      "GF08": 2,
      "GF09": 11.4,
      "GF10": 30.5
    },
    "spendingPctGdp": 40
  },
  "CH": {
    "iso3": "CHE",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 13.7,
      "GF02": 2.6,
      "GF03": 4.8,
      "GF04": 12,
      "GF05": 1.7,
      "GF06": 0.6,
      "GF07": 7,
      "GF08": 3,
      "GF09": 15.2,
      "GF10": 39.4
    },
    "spendingPctGdp": 32.4
  },
  "CN": {
    "iso3": "CHN",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 8.7,
      "GF02": 4.1,
      "GF03": 3.5,
      "GF04": 28.9,
      "GF05": 1.6,
      "GF06": 5.6,
      "GF07": 10.2,
      "GF08": 0.9,
      "GF09": 10.2,
      "GF10": 26.2
    },
    "spendingPctGdp": 31
  },
  "CK": {
    "iso3": "COK",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 34.6,
      "GF02": 0,
      "GF03": 5,
      "GF04": 23.8,
      "GF05": 2.6,
      "GF06": 3,
      "GF07": 8.1,
      "GF08": 1.5,
      "GF09": 8.5,
      "GF10": 13
    }
  },
  "CR": {
    "iso3": "CRI",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 18.8,
      "GF02": 0,
      "GF03": 7.1,
      "GF04": 5.4,
      "GF05": 0.4,
      "GF06": 4.6,
      "GF07": 21,
      "GF08": 0.4,
      "GF09": 18.8,
      "GF10": 23.5
    },
    "spendingPctGdp": 29.4
  },
  "CY": {
    "iso3": "CYP",
    "y": "2023",
    "basis": "general",
    "shares": {
      "GF01": 13.5,
      "GF02": 4.6,
      "GF03": 4,
      "GF04": 7.2,
      "GF05": 1.7,
      "GF06": 4.5,
      "GF07": 14.5,
      "GF08": 1.4,
      "GF09": 12.5,
      "GF10": 36.1
    },
    "spendingPctGdp": 41.9
  },
  "CZ": {
    "iso3": "CZE",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 10.7,
      "GF02": 3,
      "GF03": 3.9,
      "GF04": 12.8,
      "GF05": 2,
      "GF06": 2,
      "GF07": 21.1,
      "GF08": 3,
      "GF09": 10.6,
      "GF10": 30.9
    },
    "spendingPctGdp": 42.8
  },
  "DE": {
    "iso3": "DEU",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 12.9,
      "GF02": 2.7,
      "GF03": 3.3,
      "GF04": 11,
      "GF05": 1.1,
      "GF06": 1,
      "GF07": 15.4,
      "GF08": 2.2,
      "GF09": 9.1,
      "GF10": 41.3
    },
    "spendingPctGdp": 49.4
  },
  "DK": {
    "iso3": "DNK",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 12,
      "GF02": 3.9,
      "GF03": 2.1,
      "GF04": 6.5,
      "GF05": 0.8,
      "GF06": 0.7,
      "GF07": 17.5,
      "GF08": 3.2,
      "GF09": 11.7,
      "GF10": 41.5
    },
    "spendingPctGdp": 47.3
  },
  "DO": {
    "iso3": "DOM",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 25.8,
      "GF02": 3.4,
      "GF03": 4.6,
      "GF04": 19.6,
      "GF05": 1.3,
      "GF06": 2.3,
      "GF07": 6.7,
      "GF08": 0.9,
      "GF09": 19.9,
      "GF10": 15.4
    },
    "spendingPctGdp": 20.5
  },
  "ES": {
    "iso3": "ESP",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 12.4,
      "GF02": 2,
      "GF03": 4,
      "GF04": 10.8,
      "GF05": 2.1,
      "GF06": 1.1,
      "GF07": 14.2,
      "GF08": 2.7,
      "GF09": 9.1,
      "GF10": 41.8
    },
    "spendingPctGdp": 44.7
  },
  "EE": {
    "iso3": "EST",
    "y": "2023",
    "basis": "general",
    "shares": {
      "GF01": 9.8,
      "GF02": 6.3,
      "GF03": 4.3,
      "GF04": 11.4,
      "GF05": 1.7,
      "GF06": 1.1,
      "GF07": 15,
      "GF08": 4.7,
      "GF09": 14.5,
      "GF10": 31.2
    },
    "spendingPctGdp": 43.2
  },
  "FI": {
    "iso3": "FIN",
    "y": "2023",
    "basis": "general",
    "shares": {
      "GF01": 11.6,
      "GF02": 2.6,
      "GF03": 2.2,
      "GF04": 8.2,
      "GF05": 0.4,
      "GF06": 0.8,
      "GF07": 13.7,
      "GF08": 3,
      "GF09": 11.3,
      "GF10": 46.1
    },
    "spendingPctGdp": 55.8
  },
  "FR": {
    "iso3": "FRA",
    "y": "2023",
    "basis": "general",
    "shares": {
      "GF01": 10.8,
      "GF02": 3.2,
      "GF03": 3,
      "GF04": 11.1,
      "GF05": 1.8,
      "GF06": 2.2,
      "GF07": 15.5,
      "GF08": 2.6,
      "GF09": 8.8,
      "GF10": 41
    },
    "spendingPctGdp": 56.9
  },
  "GB": {
    "iso3": "GBR",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 13.1,
      "GF02": 4.9,
      "GF03": 4.7,
      "GF04": 8.6,
      "GF05": 1.6,
      "GF06": 1.6,
      "GF07": 19,
      "GF08": 1.4,
      "GF09": 10.6,
      "GF10": 34.5
    },
    "spendingPctGdp": 46.7
  },
  "GE": {
    "iso3": "GEO",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 11.5,
      "GF02": 5.2,
      "GF03": 8.4,
      "GF04": 18,
      "GF05": 2.5,
      "GF06": 5.3,
      "GF07": 7.1,
      "GF08": 4,
      "GF09": 15.9,
      "GF10": 22.2
    },
    "spendingPctGdp": 33.2
  },
  "GR": {
    "iso3": "GRC",
    "y": "2023",
    "basis": "general",
    "shares": {
      "GF01": 16.4,
      "GF02": 4.5,
      "GF03": 3.9,
      "GF04": 11.9,
      "GF05": 3.1,
      "GF06": 0.8,
      "GF07": 11.7,
      "GF08": 2.2,
      "GF09": 8,
      "GF10": 37.4
    },
    "spendingPctGdp": 49.4
  },
  "GT": {
    "iso3": "GTM",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 19.8,
      "GF02": 1.6,
      "GF03": 11.6,
      "GF04": 7.6,
      "GF05": 2,
      "GF06": 3.5,
      "GF07": 15.5,
      "GF08": 2.2,
      "GF09": 19.3,
      "GF10": 16.9
    },
    "spendingPctGdp": 16.4
  },
  "HK": {
    "iso3": "HKG",
    "y": "2023",
    "basis": "general",
    "shares": {
      "GF01": 6,
      "GF02": 0,
      "GF03": 11.8,
      "GF04": 12.6,
      "GF05": 5,
      "GF06": 8,
      "GF07": 16.1,
      "GF08": 5.2,
      "GF09": 14.8,
      "GF10": 20.6
    },
    "spendingPctGdp": 25.7
  },
  "HR": {
    "iso3": "HRV",
    "y": "2022",
    "basis": "general",
    "shares": {
      "GF01": 9.2,
      "GF02": 2.2,
      "GF03": 4.6,
      "GF04": 18.1,
      "GF05": 1.7,
      "GF06": 4.2,
      "GF07": 17.1,
      "GF08": 3.5,
      "GF09": 10.7,
      "GF10": 28.7
    },
    "spendingPctGdp": 44.6
  },
  "HU": {
    "iso3": "HUN",
    "y": "2023",
    "basis": "general",
    "shares": {
      "GF01": 20.4,
      "GF02": 3.8,
      "GF03": 3.4,
      "GF04": 18.7,
      "GF05": 1.2,
      "GF06": 3.3,
      "GF07": 8.3,
      "GF08": 5.2,
      "GF09": 10.7,
      "GF10": 25
    },
    "spendingPctGdp": 48.9
  },
  "ID": {
    "iso3": "IDN",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 32.1,
      "GF02": 5.1,
      "GF03": 7.5,
      "GF04": 17.5,
      "GF05": 1.1,
      "GF06": 5.7,
      "GF07": 8.1,
      "GF08": 0.8,
      "GF09": 14.5,
      "GF10": 7.6
    }
  },
  "IE": {
    "iso3": "IRL",
    "y": "2023",
    "basis": "general",
    "shares": {
      "GF01": 9.8,
      "GF02": 1.1,
      "GF03": 3.5,
      "GF04": 9,
      "GF05": 1.6,
      "GF06": 2.5,
      "GF07": 22.8,
      "GF08": 2,
      "GF09": 12.3,
      "GF10": 35.5
    },
    "spendingPctGdp": 22.1
  },
  "IS": {
    "iso3": "ISL",
    "y": "2023",
    "basis": "general",
    "shares": {
      "GF01": 19.3,
      "GF02": 0.1,
      "GF03": 3.4,
      "GF04": 10.8,
      "GF05": 1.6,
      "GF06": 1.4,
      "GF07": 18,
      "GF08": 6.6,
      "GF09": 14.8,
      "GF10": 23.9
    },
    "spendingPctGdp": 45.5
  },
  "IL": {
    "iso3": "ISR",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 10.3,
      "GF02": 20.6,
      "GF03": 3.4,
      "GF04": 7.9,
      "GF05": 1.2,
      "GF06": 0.1,
      "GF07": 11.6,
      "GF08": 3,
      "GF09": 14.9,
      "GF10": 26.9
    },
    "spendingPctGdp": 43.7
  },
  "IT": {
    "iso3": "ITA",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 15.4,
      "GF02": 2.6,
      "GF03": 3.5,
      "GF04": 10.1,
      "GF05": 1.8,
      "GF06": 1.5,
      "GF07": 13.2,
      "GF08": 1.7,
      "GF09": 8,
      "GF10": 42.2
    },
    "spendingPctGdp": 50.6
  },
  "JP": {
    "iso3": "JPN",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 9.1,
      "GF02": 3.2,
      "GF03": 3,
      "GF04": 10.7,
      "GF05": 3,
      "GF06": 1.5,
      "GF07": 19.6,
      "GF08": 1,
      "GF09": 8,
      "GF10": 40.7
    },
    "spendingPctGdp": 40.2
  },
  "KZ": {
    "iso3": "KAZ",
    "y": "2023",
    "basis": "general",
    "shares": {
      "GF01": 9.6,
      "GF02": 6.4,
      "GF03": 4.2,
      "GF04": 12.8,
      "GF05": 1.3,
      "GF06": 8.1,
      "GF07": 11,
      "GF08": 3,
      "GF09": 19.9,
      "GF10": 23.6
    },
    "spendingPctGdp": 23.4
  },
  "KE": {
    "iso3": "KEN",
    "y": "2023",
    "basis": "general",
    "shares": {
      "GF01": 46.3,
      "GF02": 5.2,
      "GF03": 5.8,
      "GF04": 13.7,
      "GF05": 0.2,
      "GF06": 1.7,
      "GF07": 2.8,
      "GF08": 0.3,
      "GF09": 18.4,
      "GF10": 5.5
    },
    "spendingPctGdp": 20.8
  },
  "KG": {
    "iso3": "KGZ",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 10.8,
      "GF02": 11.6,
      "GF03": 0,
      "GF04": 16.9,
      "GF05": 0.8,
      "GF06": 6.7,
      "GF07": 8.5,
      "GF08": 2.4,
      "GF09": 17.2,
      "GF10": 25.2
    },
    "spendingPctGdp": 32.1
  },
  "KI": {
    "iso3": "KIR",
    "y": "2023",
    "basis": "general",
    "shares": {
      "GF01": 18.8,
      "GF02": 0,
      "GF03": 4.5,
      "GF04": 34.5,
      "GF05": 1.5,
      "GF06": 0,
      "GF07": 10.4,
      "GF08": 0,
      "GF09": 13.5,
      "GF10": 16.8
    },
    "spendingPctGdp": 96.1
  },
  "XK": {
    "iso3": "KOS",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 11.3,
      "GF02": 5.4,
      "GF03": 9.2,
      "GF04": 14.7,
      "GF05": 0.2,
      "GF06": 1.4,
      "GF07": 9.1,
      "GF08": 2.8,
      "GF09": 21.4,
      "GF10": 24.4
    },
    "spendingPctGdp": 30.2
  },
  "LT": {
    "iso3": "LTU",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 8.7,
      "GF02": 6.6,
      "GF03": 4,
      "GF04": 8.1,
      "GF05": 1.4,
      "GF06": 2.1,
      "GF07": 14.7,
      "GF08": 3.2,
      "GF09": 14,
      "GF10": 37.4
    },
    "spendingPctGdp": 39.6
  },
  "LU": {
    "iso3": "LUX",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 11.5,
      "GF02": 1.5,
      "GF03": 2.8,
      "GF04": 12.6,
      "GF05": 2.2,
      "GF06": 1.2,
      "GF07": 12,
      "GF08": 2.8,
      "GF09": 10.8,
      "GF10": 42.6
    },
    "spendingPctGdp": 46.7
  },
  "LV": {
    "iso3": "LVA",
    "y": "2023",
    "basis": "general",
    "shares": {
      "GF01": 8.8,
      "GF02": 7.2,
      "GF03": 5.9,
      "GF04": 14.8,
      "GF05": 1.1,
      "GF06": 2.1,
      "GF07": 12.1,
      "GF08": 3,
      "GF09": 14,
      "GF10": 31
    },
    "spendingPctGdp": 43.6
  },
  "MO": {
    "iso3": "MAC",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 10.2,
      "GF02": 0,
      "GF03": 12.4,
      "GF04": 17.3,
      "GF05": 2.4,
      "GF06": 6.4,
      "GF07": 10.3,
      "GF08": 3,
      "GF09": 13.6,
      "GF10": 24.5
    },
    "spendingPctGdp": 24.4
  },
  "MD": {
    "iso3": "MDA",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 9,
      "GF02": 1.4,
      "GF03": 5.8,
      "GF04": 9.2,
      "GF05": 0.4,
      "GF06": 2.6,
      "GF07": 14.7,
      "GF08": 2.6,
      "GF09": 16,
      "GF10": 38.2
    },
    "spendingPctGdp": 38
  },
  "MT": {
    "iso3": "MLT",
    "y": "2023",
    "basis": "general",
    "shares": {
      "GF01": 12.9,
      "GF02": 1.2,
      "GF03": 3.9,
      "GF04": 20.1,
      "GF05": 3.3,
      "GF06": 2.1,
      "GF07": 14.1,
      "GF08": 4.2,
      "GF09": 11.4,
      "GF10": 26.7
    },
    "spendingPctGdp": 35.8
  },
  "MM": {
    "iso3": "MMR",
    "y": "2019",
    "basis": "general",
    "shares": {
      "GF01": 14,
      "GF02": 16.3,
      "GF03": 2.8,
      "GF04": 42.7,
      "GF05": 0.2,
      "GF06": 4.3,
      "GF07": 4.3,
      "GF08": 1,
      "GF09": 9.8,
      "GF10": 4.6
    },
    "spendingPctGdp": 20.4
  },
  "MN": {
    "iso3": "MNG",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 28,
      "GF02": 3.3,
      "GF03": 5.8,
      "GF04": 9.8,
      "GF05": 0.9,
      "GF06": 2.8,
      "GF07": 8.5,
      "GF08": 1.8,
      "GF09": 13.8,
      "GF10": 25.2
    },
    "spendingPctGdp": 38.1
  },
  "MU": {
    "iso3": "MUS",
    "y": "2025",
    "basis": "general",
    "shares": {
      "GF01": 23.2,
      "GF02": 0.3,
      "GF03": 6.2,
      "GF04": 8.5,
      "GF05": 2.4,
      "GF06": 1.6,
      "GF07": 7.6,
      "GF08": 1.1,
      "GF09": 10.3,
      "GF10": 38.9
    },
    "spendingPctGdp": 36.6
  },
  "NA": {
    "iso3": "NAM",
    "y": "2022",
    "basis": "general",
    "shares": {
      "GF01": 22.9,
      "GF02": 7.6,
      "GF03": 9.1,
      "GF04": 8.1,
      "GF05": 0.5,
      "GF06": 2.8,
      "GF07": 11.6,
      "GF08": 1,
      "GF09": 24,
      "GF10": 12.4
    },
    "spendingPctGdp": 38
  },
  "NL": {
    "iso3": "NLD",
    "y": "2023",
    "basis": "general",
    "shares": {
      "GF01": 8.2,
      "GF02": 3.1,
      "GF03": 4.2,
      "GF04": 11.8,
      "GF05": 3.4,
      "GF06": 1.4,
      "GF07": 16.3,
      "GF08": 2.6,
      "GF09": 11.3,
      "GF10": 37.6
    },
    "spendingPctGdp": 43.9
  },
  "NO": {
    "iso3": "NOR",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 11.3,
      "GF02": 4.5,
      "GF03": 2.1,
      "GF04": 11.3,
      "GF05": 2,
      "GF06": 1.8,
      "GF07": 16.6,
      "GF08": 3.1,
      "GF09": 9.8,
      "GF10": 37.6
    },
    "spendingPctGdp": 49.3
  },
  "NP": {
    "iso3": "NPL",
    "y": "2021",
    "basis": "general",
    "shares": {
      "GF01": 25,
      "GF02": 4.2,
      "GF03": 5,
      "GF04": 28.5,
      "GF05": 1.1,
      "GF06": 7.6,
      "GF07": 7.1,
      "GF08": 0.9,
      "GF09": 12.8,
      "GF10": 7.6
    },
    "spendingPctGdp": 28.4
  },
  "NR": {
    "iso3": "NRU",
    "y": "2018",
    "basis": "general",
    "shares": {
      "GF01": 33.9,
      "GF02": 1.4,
      "GF03": 18.1,
      "GF04": 10.5,
      "GF05": 2,
      "GF06": 3.9,
      "GF07": 11.8,
      "GF08": 2.9,
      "GF09": 9.6,
      "GF10": 5.9
    },
    "spendingPctGdp": 86.7
  },
  "NZ": {
    "iso3": "NZL",
    "y": "2025",
    "basis": "general",
    "shares": {
      "GF01": 12.2,
      "GF02": 2.2,
      "GF03": 4.8,
      "GF04": 9.6,
      "GF05": 2.9,
      "GF06": 3.4,
      "GF07": 18.2,
      "GF08": 2.7,
      "GF09": 13.1,
      "GF10": 30.8
    },
    "spendingPctGdp": 40.7
  },
  "PA": {
    "iso3": "PAN",
    "y": "2021",
    "basis": "general",
    "shares": {
      "GF01": 26.1,
      "GF02": 0,
      "GF03": 10.6,
      "GF04": 8,
      "GF05": 1.5,
      "GF06": 1.9,
      "GF07": 15.2,
      "GF08": 2.9,
      "GF09": 20.4,
      "GF10": 13.4
    },
    "spendingPctGdp": 19.2
  },
  "PL": {
    "iso3": "POL",
    "y": "2023",
    "basis": "general",
    "shares": {
      "GF01": 10.4,
      "GF02": 4.4,
      "GF03": 4.8,
      "GF04": 16,
      "GF05": 1.4,
      "GF06": 1.5,
      "GF07": 12.2,
      "GF08": 2.8,
      "GF09": 10.5,
      "GF10": 35.9
    },
    "spendingPctGdp": 46.9
  },
  "PT": {
    "iso3": "PRT",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 13.7,
      "GF02": 2.1,
      "GF03": 3.9,
      "GF04": 8.8,
      "GF05": 1.6,
      "GF06": 1.4,
      "GF07": 16.1,
      "GF08": 2,
      "GF09": 10.2,
      "GF10": 40.3
    },
    "spendingPctGdp": 43.2
  },
  "RO": {
    "iso3": "ROU",
    "y": "2023",
    "basis": "general",
    "shares": {
      "GF01": 13.1,
      "GF02": 4.2,
      "GF03": 6.5,
      "GF04": 16.9,
      "GF05": 1.8,
      "GF06": 3.6,
      "GF07": 11.6,
      "GF08": 2.5,
      "GF09": 8.4,
      "GF10": 31.4
    },
    "spendingPctGdp": 40.6
  },
  "RU": {
    "iso3": "RUS",
    "y": "2020",
    "basis": "general",
    "shares": {
      "GF01": 24,
      "GF02": 4.7,
      "GF03": 5.6,
      "GF04": 11.3,
      "GF05": 0.6,
      "GF06": 3.1,
      "GF07": 5.3,
      "GF08": 2.3,
      "GF09": 8.9,
      "GF10": 34.1
    },
    "spendingPctGdp": 41.3
  },
  "SG": {
    "iso3": "SGP",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 34.4,
      "GF02": 12,
      "GF03": 3.8,
      "GF04": 21.9,
      "GF05": 1.3,
      "GF06": 0.5,
      "GF07": 9.8,
      "GF08": 2.3,
      "GF09": 9.7,
      "GF10": 4.3
    },
    "spendingPctGdp": 25.2
  },
  "SV": {
    "iso3": "SLV",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 21.6,
      "GF02": 3.1,
      "GF03": 13.2,
      "GF04": 9.2,
      "GF05": 1.5,
      "GF06": 6,
      "GF07": 18.6,
      "GF08": 1.3,
      "GF09": 13.1,
      "GF10": 12.3
    },
    "spendingPctGdp": 31.7
  },
  "SM": {
    "iso3": "SMR",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 16.9,
      "GF02": 0,
      "GF03": 2.1,
      "GF04": 12.6,
      "GF05": 1.6,
      "GF06": 1.6,
      "GF07": 12.5,
      "GF08": 2.5,
      "GF09": 8.4,
      "GF10": 41.6
    },
    "spendingPctGdp": 40.8
  },
  "SO": {
    "iso3": "SOM",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 30.9,
      "GF02": 14,
      "GF03": 18.4,
      "GF04": 23.5,
      "GF05": 0.2,
      "GF06": 1.4,
      "GF07": 6.3,
      "GF08": 0.5,
      "GF09": 4.4,
      "GF10": 0.3
    },
    "spendingPctGdp": 9.3
  },
  "SK": {
    "iso3": "SVK",
    "y": "2023",
    "basis": "general",
    "shares": {
      "GF01": 11.2,
      "GF02": 2.5,
      "GF03": 5,
      "GF04": 15.4,
      "GF05": 1.9,
      "GF06": 1.1,
      "GF07": 13.7,
      "GF08": 2.4,
      "GF09": 10.3,
      "GF10": 36.4
    },
    "spendingPctGdp": 48
  },
  "SI": {
    "iso3": "SVN",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 9.9,
      "GF02": 3,
      "GF03": 3.3,
      "GF04": 12.3,
      "GF05": 1.5,
      "GF06": 0.9,
      "GF07": 17.2,
      "GF08": 3.2,
      "GF09": 11.8,
      "GF10": 36.7
    },
    "spendingPctGdp": 46.5
  },
  "SE": {
    "iso3": "SWE",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 10.8,
      "GF02": 4.3,
      "GF03": 3.1,
      "GF04": 9.5,
      "GF05": 1.1,
      "GF06": 1.6,
      "GF07": 14.6,
      "GF08": 2.7,
      "GF09": 14.3,
      "GF10": 37.8
    },
    "spendingPctGdp": 50.7
  },
  "TH": {
    "iso3": "THA",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 31.9,
      "GF02": 4.4,
      "GF03": 4.8,
      "GF04": 17.8,
      "GF05": 0.2,
      "GF06": 1.3,
      "GF07": 7.4,
      "GF08": 1.5,
      "GF09": 11.5,
      "GF10": 19.1
    },
    "spendingPctGdp": 22.5
  },
  "TJ": {
    "iso3": "TJK",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 8.1,
      "GF02": 11.6,
      "GF03": 0,
      "GF04": 25.6,
      "GF05": 1.5,
      "GF06": 4,
      "GF07": 9.2,
      "GF08": 5.4,
      "GF09": 20.7,
      "GF10": 14
    },
    "spendingPctGdp": 30.6
  },
  "TR": {
    "iso3": "TUR",
    "y": "2025",
    "basis": "general",
    "shares": {
      "GF01": 17.8,
      "GF02": 4.1,
      "GF03": 5.6,
      "GF04": 11.9,
      "GF05": 0.8,
      "GF06": 4.5,
      "GF07": 16.3,
      "GF08": 2,
      "GF09": 9,
      "GF10": 28
    },
    "spendingPctGdp": 34.4
  },
  "UA": {
    "iso3": "UKR",
    "y": "2023",
    "basis": "general",
    "shares": {
      "GF01": 7.2,
      "GF02": 43.1,
      "GF03": 12.1,
      "GF04": 4.7,
      "GF05": 0.1,
      "GF06": 1.4,
      "GF07": 4.5,
      "GF08": 0.8,
      "GF09": 6.3,
      "GF10": 19.7
    },
    "spendingPctGdp": 73.5
  },
  "US": {
    "iso3": "USA",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 17.3,
      "GF02": 7.9,
      "GF03": 4.5,
      "GF04": 8.4,
      "GF05": 0,
      "GF06": 1.4,
      "GF07": 26,
      "GF08": 0.6,
      "GF09": 14.1,
      "GF10": 19.7
    },
    "spendingPctGdp": 39.6
  },
  "UZ": {
    "iso3": "UZB",
    "y": "2022",
    "basis": "general",
    "shares": {
      "GF01": 15.1,
      "GF02": 0,
      "GF03": 1.4,
      "GF04": 15.8,
      "GF05": 0,
      "GF06": 1.9,
      "GF07": 9.6,
      "GF08": 1.9,
      "GF09": 21.6,
      "GF10": 23.1
    },
    "unclassified": 9.6,
    "spendingPctGdp": 30.3
  },
  "ZA": {
    "iso3": "ZAF",
    "y": "2024",
    "basis": "general",
    "shares": {
      "GF01": 22.7,
      "GF02": 1.9,
      "GF03": 7.3,
      "GF04": 17.2,
      "GF05": 0.7,
      "GF06": 4.1,
      "GF07": 10.7,
      "GF08": 1.8,
      "GF09": 20.5,
      "GF10": 13
    },
    "spendingPctGdp": 40.5
  },
  "AR": {
    "iso3": "ARG",
    "y": "2024",
    "basis": "central",
    "shares": {
      "GF01": 30.7,
      "GF02": 3.1,
      "GF03": 8.2,
      "GF04": 21,
      "GF05": 0.4,
      "GF06": 0.9,
      "GF07": 17.2,
      "GF08": 0.2,
      "GF09": 8.1,
      "GF10": 10
    },
    "spendingPctGdp": 10.4
  },
  "CL": {
    "iso3": "CHL",
    "y": "2024",
    "basis": "central",
    "shares": {
      "GF01": 8.9,
      "GF02": 2.1,
      "GF03": 5.8,
      "GF04": 10.9,
      "GF05": 0.4,
      "GF06": 1.2,
      "GF07": 21.6,
      "GF08": 0.7,
      "GF09": 19.9,
      "GF10": 28.5
    },
    "spendingPctGdp": 24.6
  },
  "CV": {
    "iso3": "CPV",
    "y": "2017",
    "basis": "central",
    "shares": {
      "GF01": 27.5,
      "GF02": 1.6,
      "GF03": 7.8,
      "GF04": 9.7,
      "GF05": 5,
      "GF06": 2.1,
      "GF07": 7.8,
      "GF08": 0.9,
      "GF09": 17.9,
      "GF10": 20.4
    },
    "spendingPctGdp": 31.4
  },
  "EC": {
    "iso3": "ECU",
    "y": "2022",
    "basis": "central",
    "shares": {
      "GF01": 23.1,
      "GF02": 4.7,
      "GF03": 7.1,
      "GF04": 23.9,
      "GF05": 0.3,
      "GF06": 0.3,
      "GF07": 10.4,
      "GF08": 0.4,
      "GF09": 12.7,
      "GF10": 17
    },
    "spendingPctGdp": 25.8
  },
  "JO": {
    "iso3": "JOR",
    "y": "2021",
    "basis": "central",
    "shares": {
      "GF01": 19,
      "GF02": 11.4,
      "GF03": 13.6,
      "GF04": 9.8,
      "GF05": 0.6,
      "GF06": 5.5,
      "GF07": 10.4,
      "GF08": 1.9,
      "GF09": 10.8,
      "GF10": 17.1
    },
    "spendingPctGdp": 33.6
  },
  "PS": {
    "iso3": "WBG",
    "y": "2021",
    "basis": "central",
    "shares": {
      "GF01": 29.3,
      "GF02": 0,
      "GF03": 23.7,
      "GF04": 2.6,
      "GF05": 0.1,
      "GF06": 1.7,
      "GF07": 13.7,
      "GF08": 2.3,
      "GF09": 20.7,
      "GF10": 6
    },
    "spendingPctGdp": 8.3
  }
};

/** The same, keyed by ISO alpha-3 — for pages, like Economies, that key by it. */
export const COUNTRY_BUDGET_BY_ISO3: Record<string, CountryBudget> = Object.fromEntries(
  Object.values(COUNTRY_BUDGET).map((b) => [b.iso3, b]),
);
