/**
 * The site's data log: when each of its data sets was last read from its
 * sources, newest first.
 *
 * GENERATED by build-data-log.cjs — do not edit by hand; run it after any
 * other build script. Each date is read from the header of the data file
 * itself; nothing here is typed in.
 */
export interface DataLogEntry {
  /** What the data set holds. */
  what: string;
  /** Whose figures they are. */
  from: string;
  /** The page that shows them, and its name. */
  page: string;
  where: string;
  /** The day its sources were last read, ISO. */
  read: string;
  /** How many of the site's data files it is. */
  files: number;
}

export const DATA_LOG: DataLogEntry[] = [
  {
    "what": "Each city's population, land and built-up area, 1975 to 2050",
    "from": "United Nations (World Urbanization Prospects), Wikidata",
    "page": "/dashboard/cities",
    "where": "Cities",
    "read": "2026-10-06",
    "files": 1
  },
  {
    "what": "Free schooling, public health cover and what care costs",
    "from": "UNESCO, OECD, WHO (via the World Bank)",
    "page": "/dashboard/countries",
    "where": "Countries",
    "read": "2026-10-06",
    "files": 1
  },
  {
    "what": "Geography, languages, religions, heritage sites and dependencies",
    "from": "CIA World Factbook (final edition), Wikidata, UNESCO",
    "page": "/dashboard/countries",
    "where": "Countries",
    "read": "2026-10-06",
    "files": 3
  },
  {
    "what": "Modern slavery: the world's and the regions' estimates",
    "from": "ILO, Walk Free and IOM (Global Estimates), Walk Free (Global Slavery Index)",
    "page": "/dashboard/crime",
    "where": "Crime statistics",
    "read": "2026-10-06",
    "files": 1
  },
  {
    "what": "Public security: stability, conflict deaths, terrorism and displacement, by country",
    "from": "World Bank (Worldwide Governance Indicators), UCDP, Global Terrorism Database, UNHCR, IDMC",
    "page": "/dashboard/countries",
    "where": "Countries",
    "read": "2026-10-06",
    "files": 1
  },
  {
    "what": "When each state's senators', representatives' and governor's terms end",
    "from": "congress-legislators, Wikipedia (citing the National Governors Association)",
    "page": "/dashboard/states",
    "where": "US states",
    "read": "2026-10-06",
    "files": 1
  },
  {
    "what": "Renewable power: generation, capacity, cost and investment",
    "from": "IRENA, Ember, U.S. EIA, OECD",
    "page": "/dashboard/trends",
    "where": "Trends",
    "read": "2026-10-02",
    "files": 1
  },
  {
    "what": "Technology and the trends, by region, country and name",
    "from": "World Bank, ITU, Epoch AI, OpenAlex and others",
    "page": "/dashboard/trends",
    "where": "Trends",
    "read": "2026-10-02",
    "files": 2
  },
  {
    "what": "The world's figures, year by year, and by region",
    "from": "World Bank, V-Dem, UNDP, IMF, UCDP and others",
    "page": "/dashboard/worldview",
    "where": "Worldview",
    "read": "2026-10-02",
    "files": 2
  },
  {
    "what": "Commodity prices, month by month",
    "from": "World Bank, IMF",
    "page": "/dashboard/economies?view=resources",
    "where": "Resources",
    "read": "2026-10-01",
    "files": 1
  },
  {
    "what": "Projections: the economy to five years out, people to 2100",
    "from": "IMF World Economic Outlook, UN World Population Prospects",
    "page": "/dashboard/trends",
    "where": "Trends",
    "read": "2026-10-01",
    "files": 1
  },
  {
    "what": "Recorded crime and prison populations",
    "from": "UNODC, World Prison Brief",
    "page": "/dashboard/crime",
    "where": "Crime statistics",
    "read": "2026-10-01",
    "files": 3
  },
  {
    "what": "The fifty states: people, incomes, budgets and power",
    "from": "US Census Bureau, BEA, BLS, BJS, U.S. EIA and others",
    "page": "/dashboard/states",
    "where": "US states",
    "read": "2026-10-01",
    "files": 3
  },
  {
    "what": "Every economy's figures and what it is made of",
    "from": "World Bank, IMF, UN Statistics Division, Eurostat and others",
    "page": "/dashboard/economies",
    "where": "Economies",
    "read": "2026-09-29",
    "files": 5
  },
  {
    "what": "Each country's headline figures and GDP history",
    "from": "World Bank, IMF, UN",
    "page": "/dashboard/countries",
    "where": "Countries",
    "read": "2026-09-24",
    "files": 3
  },
  {
    "what": "Each country's people, health, schooling, land, energy and forces",
    "from": "World Bank, UN, UNDP, FAO, U.S. EIA, SIPRI",
    "page": "/dashboard/countries",
    "where": "Countries",
    "read": "2026-09-24",
    "files": 4
  },
  {
    "what": "Who produces and holds each commodity",
    "from": "USGS, U.S. EIA, OPEC, USDA and others",
    "page": "/dashboard/economies?view=resources",
    "where": "Resources",
    "read": "2026-09-23",
    "files": 4
  },
  {
    "what": "What governments spend, by function, and what they give in aid",
    "from": "IMF, OECD",
    "page": "/dashboard/economies",
    "where": "Economies",
    "read": "2026-09-21",
    "files": 2
  },
  {
    "what": "The air people breathe: PM2.5 exposure by country",
    "from": "World Bank",
    "page": "/dashboard/maps",
    "where": "World maps",
    "read": "2026-09-15",
    "files": 1
  },
  {
    "what": "The measured state of the climate",
    "from": "NOAA, NASA GISS, NSIDC",
    "page": "/dashboard/planetary-boundaries",
    "where": "Climate",
    "read": "2026-09-15",
    "files": 1
  }
];

/** How many data files the log covers. */
export const DATA_LOG_FILES = 41;
