/**
 * The dependencies the CIA World Factbook lists that have no card on the
 * site, and the Factbook entries a card stands for where ISO 3166-1 lists
 * several as one place.
 *
 * GENERATED by build-dependencies.cjs on 2026-10-06 — do not edit by hand; change
 * the script and re-run it. The script checks every Factbook dependency
 * against the site's places and stops if one is missing or under another
 * state.
 *
 * From the Factbook's final edition: the CIA closed it in February 2026, and
 * the factbook.json mirror last copied it on 2026-01-22.
 */
export const DEPENDENCIES_RETRIEVED = "2026-10-06";
/** The day the mirror last copied the Factbook. */
export const FACTBOOK_LAST_COPY = "2026-01-22";

export const DEPENDENCIES_SOURCE = {
  label: "CIA World Factbook, final edition (January 2026) — dependency status, from the factbook.json archive",
  url: "https://github.com/factbook/factbook.json",
} as const;

/** A dependency the Factbook lists that ISO 3166-1 has no entry for, so it has no card of its own. */
export interface ListedDependency {
  name: string;
  /** The Factbook's dependency status: its first clause, and the whole of it. */
  status: string;
  statusFull: string;
  /** Where it is, in the Factbook's words. */
  location: string;
  areaKm2: number;
  /** The Factbook gives the area as less than this. */
  areaUnder?: boolean;
  /** No permanent population. */
  uninhabited: boolean;
  /** The state whose flag it flies, where the Factbook says it uses that flag. */
  flag?: string;
}

/** How many Factbook entries carry a dependency status. */
export const FACTBOOK_DEPENDENCIES = 52;

/** The dependencies with no card, by the ISO code of the state that administers them. */
export const UNCARDED_DEPENDENCIES: Record<string, ListedDependency[]> = {
  "AU": [
    {
      "name": "Ashmore and Cartier Islands",
      "status": "Territory of Australia",
      "statusFull": "Territory of Australia; administered from Canberra by the Department of Regional Australia, Local Government, Arts and Sport",
      "location": "Southeastern Asia, islands in the Indian Ocean, midway between northwestern Australia and Timor island",
      "areaKm2": 5,
      "uninhabited": true,
      "flag": "AU"
    },
    {
      "name": "Coral Sea Islands",
      "status": "Territory of Australia",
      "statusFull": "Territory of Australia; administered from Canberra by the Department of Regional Australia, Local Government, Arts and Sport",
      "location": "Oceania, islands in the Coral Sea, northeast of Australia",
      "areaKm2": 3,
      "areaUnder": true,
      "uninhabited": true,
      "flag": "AU"
    }
  ],
  "FR": [
    {
      "name": "Clipperton Island",
      "status": "Possession of France",
      "statusFull": "Possession of France; administered directly by the Minister of Overseas France",
      "location": "Middle America, atoll in the North Pacific Ocean, 1,120 km southwest of Mexico",
      "areaKm2": 6,
      "uninhabited": true,
      "flag": "FR"
    }
  ],
  "GB": [
    {
      "name": "Akrotiri",
      "status": "A special form of UK overseas territory",
      "statusFull": "A special form of UK overseas territory; administered by an administrator who is also the Commander, British Forces Cyprus",
      "location": "Eastern Mediterranean, peninsula on the southwest coast of Cyprus",
      "areaKm2": 123,
      "uninhabited": false,
      "flag": "GB"
    },
    {
      "name": "Dhekelia",
      "status": "A special form of UK overseas territory",
      "statusFull": "A special form of UK overseas territory; administered by an administrator who is also the Commander, British Forces Cyprus",
      "location": "Eastern Mediterranean, on the southeast coast of Cyprus near Famagusta",
      "areaKm2": 131,
      "uninhabited": false,
      "flag": "GB"
    }
  ]
};

/** The Factbook's entries that one card stands for, where ISO 3166-1 lists them as one place: by the card's code. */
export const CARD_COVERS: Record<string, string[]> = {
  "SJ": [
    "Jan Mayen",
    "Svalbard"
  ],
  "UM": [
    "Baker Island",
    "Howland Island",
    "Jarvis Island",
    "Johnston Atoll",
    "Kingman Reef",
    "Midway Islands",
    "Navassa Island",
    "Palmyra Atoll",
    "Wake Island"
  ]
};

/** The Factbook's dependency status for each dependency with a card, in its own words: by the card's code. */
export const FACTBOOK_STATUS: Record<string, string> = {
  "AI": "Overseas territory of the UK",
  "AS": "Unincorporated, unorganized Territory of the US; administered by the Office of Insular Affairs, US Department of the Interior",
  "AW": "One of four constituent countries of the Kingdom of the Netherlands; full autonomy in internal affairs obtained in 1986 upon separation from the Netherlands Antilles; Dutch government responsible for defense and foreign affairs",
  "BL": "Overseas collectivity of France",
  "BM": "Overseas territory of the UK",
  "BV": "Territory of Norway; administered by the Polar Department of the Ministry of Justice and Oslo Police",
  "CC": "Non-self-governing territory of Australia; administered from Canberra by the Department of Infrastructure, Transport, Cities & Regional Development",
  "CK": "Self-governing in free association with New Zealand; Cook Islands is fully responsible for internal affairs and conducts its own international relations, including establishing diplomatic relationships with foreign countries; New Zealand has a constitutional responsibility to respond to requests for assistance with foreign affairs, disasters, and defense",
  "CW": "One of four constituent countries of the Kingdom of the Netherlands; full autonomy in internal affairs granted in 2010; Dutch government responsible for defense and foreign affairs",
  "CX": "Non-self-governing territory of Australia; administered from Canberra by the Department of Infrastructure, Transport, Cities & Regional Development",
  "FK": "Overseas territory of the UK; also claimed by Argentina",
  "FO": "Part of the Kingdom of Denmark; self-governing overseas administrative division of Denmark since 1948",
  "GG": "British crown dependency",
  "GI": "Overseas territory of the UK",
  "GL": "Part of the Kingdom of Denmark; self-governing overseas administrative division of Denmark since 1979",
  "GS": "Overseas territory of the UK, also claimed by Argentina; administered from the Falkland Islands by a commissioner, who is concurrently governor of the Falkland Islands, representing the British monarch",
  "GU": "Unincorporated, organized territory of the US, with policy relations between Guam and the Federal government under the jurisdiction of the Office of Insular Affairs, US Department of the Interior",
  "HK": "Special administrative region of the People's Republic of China",
  "HM": "Territory of Australia; administered from Canberra by the Department of Agriculture, Water, and the Environment (Australian Antarctic Division)",
  "IM": "British crown dependency",
  "IO": "Overseas territory of the UK; administered by a commissioner, resident in the Foreign, Commonwealth, and Development Office in London",
  "JE": "British crown dependency",
  "KY": "Overseas territory of the UK",
  "MF": "Overseas collectivity of France",
  "MO": "Special administrative region of the People's Republic of China",
  "MP": "Commonwealth in political union with and under the sovereignty of the US; federal funds administered by the US Department of the Interior, Office of Insular Affairs",
  "MS": "Overseas territory of the UK",
  "NC": "Special collectivity of France",
  "NF": "Administered as a territory of Australia; administered by the Australian Government through the Department of Infrastructure, Transport, Cities, & Regional Development",
  "NU": "Self-governing in free association with New Zealand since 1974; Niue is fully responsible for internal affairs; under the Niue Constitution Act of 1974, New Zealand provides necessary economic and administrative assistance to Niue, as well as assistance with foreign affairs, defense, and security if requested",
  "PF": "Overseas country of France",
  "PM": "Overseas collectivity of France",
  "PN": "Overseas territory of the UK",
  "PR": "Unincorporated organized territory of the US with commonwealth status; policy relations between Puerto Rico and the US conducted under the jurisdiction of the Office of the President",
  "SH": "Overseas territory of the UK",
  "SJ": "Jan Mayen: territory of Norway; since 1994, administered from Oslo through the county governor (fylkesmann) of Nordland; however, authority has been delegated to a station commander of the Norwegian Defense Communication Service; in 2010, Norway designated the majority of Jan Mayen as a nature reserve · Svalbard: territory of Norway; administered by the Polar Department of the Ministry of Justice, through a governor (sysselmann) residing in Longyearbyen, Spitsbergen; by treaty (9 February 1920), sovereignty was awarded to Norway",
  "SX": "One of four constituent countries of the Kingdom of the Netherlands; full autonomy in internal affairs granted in 2010; Dutch government responsible for defense and foreign affairs",
  "TC": "Overseas territory of the UK",
  "TF": "Overseas territory of France since 1955",
  "TK": "Tokelau is a non-self-governing territory of New Zealand and part of the Realm of New Zealand; Tokelau has its own political institutions, judicial system, public services (including telecommunications and shipping), and budget control",
  "UM": "Baker Island, Howland Island, Jarvis Island, Johnston Atoll, Kingman Reef, Midway Islands, Palmyra Atoll: with the exception of Palmyra Atoll, the constituent islands are unincorporated, unorganized territories of the US; administered by the Fish and Wildlife Service of the US Department of the Interior as part of the National Wildlife Refuge System · Wake Island: unincorporated, unorganized territory of the US; administered by the Department of the Interior; the 11th US Air Force currently conducts activities on the atoll, and it is managed from Pacific Air Force Support Center · Navassa Island: unorganized, unincorporated territory of the US; administered by the Fish and Wildlife Service, US Department of the Interior, from the Caribbean Islands National Wildlife Refuge in Boqueron, Puerto Rico; Haiti has claimed the island since the 19th century",
  "VG": "Overseas territory of the UK; internal self-governing",
  "VI": "Unincorporated, organized territory of the US, with policy relations with the US federal government under the jurisdiction of the Office of Insular Affairs, US Department of the Interior",
  "WF": "Overseas collectivity of France"
};
