import { countriesData, type Country } from "./countriesData";

/**
 * Global North and Global South, as the world map uses them.
 *
 * GENERATED by build-development-status.cjs on 2026-09-12 — do not edit by hand;
 * change the script and re-run it.
 *
 * Neither term is an official category and no body publishes a membership
 * list, so these are not invented here. They are the UN Statistics Division's
 * M49 "Developed / Developing Countries" classification, the published split
 * that carries ISO codes. UNSD notes that the designations are for statistical
 * convenience and do not express a judgement about the stage a country or area
 * has reached in the development process; the map says so where it offers
 * these scopes.
 *
 * Of the 204 countries in this dataset: 53 are classified developed,
 * 149 developing, and 2 are not classified by M49 (Kosovo, Taiwan).
 * Unclassified countries belong to neither scope and are drawn as out of scope,
 * rather than assigned to one.
 */
export const DEVELOPMENT_STATUS_SOURCE = {
  label: "UN M49 — developed / developing classification",
  url: "https://unstats.un.org/unsd/methodology/m49/overview/",
  retrieved: "2026-09-12",
};

/** M49 "Developed" — 65 countries and areas. */
export const GLOBAL_NORTH_CODES = ["AD", "AL", "AT", "AU", "AX", "BA", "BE", "BG", "BM", "BY", "CA", "CC", "CH", "CX", "CY", "CZ", "DE", "DK", "EE", "ES", "FI", "FO", "FR", "GB", "GG", "GI", "GL", "GR", "HM", "HR", "HU", "IE", "IL", "IM", "IS", "IT", "JE", "JP", "LI", "LT", "LU", "LV", "MC", "MD", "ME", "MK", "MT", "NF", "NL", "NO", "NZ", "PL", "PM", "PT", "RO", "RS", "RU", "SE", "SI", "SJ", "SK", "SM", "UA", "US", "VA"] as const;

/** M49 "Developing" — 182 countries and areas. */
export const GLOBAL_SOUTH_CODES = ["AE", "AF", "AG", "AI", "AM", "AO", "AR", "AS", "AW", "AZ", "BB", "BD", "BF", "BH", "BI", "BJ", "BL", "BN", "BO", "BQ", "BR", "BS", "BT", "BV", "BW", "BZ", "CD", "CF", "CG", "CI", "CK", "CL", "CM", "CN", "CO", "CR", "CU", "CV", "CW", "DJ", "DM", "DO", "DZ", "EC", "EG", "EH", "ER", "ET", "FJ", "FK", "FM", "GA", "GD", "GE", "GF", "GH", "GM", "GN", "GP", "GQ", "GS", "GT", "GU", "GW", "GY", "HK", "HN", "HT", "ID", "IN", "IO", "IQ", "IR", "JM", "JO", "KE", "KG", "KH", "KI", "KM", "KN", "KP", "KR", "KW", "KY", "KZ", "LA", "LB", "LC", "LK", "LR", "LS", "LY", "MA", "MF", "MG", "MH", "ML", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MU", "MV", "MW", "MX", "MY", "MZ", "NA", "NC", "NE", "NG", "NI", "NP", "NR", "NU", "OM", "PA", "PE", "PF", "PG", "PH", "PK", "PN", "PR", "PS", "PW", "PY", "QA", "RE", "RW", "SA", "SB", "SC", "SD", "SG", "SH", "SL", "SN", "SO", "SR", "SS", "ST", "SV", "SX", "SY", "SZ", "TC", "TD", "TF", "TG", "TH", "TJ", "TK", "TL", "TM", "TN", "TO", "TR", "TT", "TV", "TZ", "UG", "UM", "UY", "UZ", "VC", "VE", "VG", "VI", "VN", "VU", "WF", "WS", "YE", "YT", "ZA", "ZM", "ZW"] as const;

const northSet = new Set<string>(GLOBAL_NORTH_CODES);
const southSet = new Set<string>(GLOBAL_SOUTH_CODES);

export function isGlobalNorth(country: Country): boolean {
  return northSet.has(country.code);
}

export function isGlobalSouth(country: Country): boolean {
  return southSet.has(country.code);
}

export const globalNorthCountries: Country[] = countriesData.filter(isGlobalNorth);
export const globalSouthCountries: Country[] = countriesData.filter(isGlobalSouth);
