/**
 * Official development assistance by donor country.
 *
 * GENERATED by build-donor-aid.cjs on 2026-09-21 — do not edit by hand;
 * change the script and re-run it. See that script for the source and method.
 */

export interface DonorAid {
  iso3: string;
  name: string;
  /** ODA, grant-equivalent basis, current US dollars, in `year`. */
  usd: number;
  year: string;
  /**
   * Change on the year before in real terms (constant prices), as the OECD
   * reports it, in percent. Null where the year before was not reported.
   */
  realChangePct: number | null;
  /** ODA as a percentage of gross national income, in `year`. */
  pctGni: number | null;
}

export const DONOR_AID_SOURCE = {
  label: "OECD — DAC1, official development assistance by provider (2025 preliminary)",
  url: "https://data-explorer.oecd.org/vis?df%5Bag%5D=OECD.DCD.FSD&df%5Bid%5D=DSD_DAC1%40DF_DAC1",
};
export const DONOR_AID_RETRIEVED = "2026-09-21";

/** The DAC members' combined total, for the headline. */
export const DAC_TOTAL = {"usd":174262320000,"year":"2025","realChangePct":-23.1,"pctGni":0.26};

/** Every reporting country, largest first. */
export const DONOR_AID: DonorAid[] = [
  {
    "iso3": "DEU",
    "name": "Germany",
    "usd": 29088640000,
    "year": "2025",
    "realChangePct": -17.4,
    "pctGni": 0.56
  },
  {
    "iso3": "USA",
    "name": "United States",
    "usd": 28953610000,
    "year": "2025",
    "realChangePct": -56.9,
    "pctGni": 0.09
  },
  {
    "iso3": "GBR",
    "name": "United Kingdom",
    "usd": 17175720000,
    "year": "2025",
    "realChangePct": -10.8,
    "pctGni": 0.43
  },
  {
    "iso3": "JPN",
    "name": "Japan",
    "usd": 16217980000,
    "year": "2025",
    "realChangePct": -5.6,
    "pctGni": 0.35
  },
  {
    "iso3": "FRA",
    "name": "France",
    "usd": 14532900000,
    "year": "2025",
    "realChangePct": -10.9,
    "pctGni": 0.42
  },
  {
    "iso3": "NLD",
    "name": "Netherlands",
    "usd": 7686110000,
    "year": "2025",
    "realChangePct": -4.9,
    "pctGni": 0.58
  },
  {
    "iso3": "TUR",
    "name": "Türkiye",
    "usd": 7522350000,
    "year": "2025",
    "realChangePct": -9,
    "pctGni": 0.5
  },
  {
    "iso3": "ITA",
    "name": "Italy",
    "usd": 7282680000,
    "year": "2025",
    "realChangePct": 0,
    "pctGni": 0.3
  },
  {
    "iso3": "CAN",
    "name": "Canada",
    "usd": 7244350000,
    "year": "2025",
    "realChangePct": -2.3,
    "pctGni": 0.32
  },
  {
    "iso3": "SWE",
    "name": "Sweden",
    "usd": 5956460000,
    "year": "2025",
    "realChangePct": 9.6,
    "pctGni": 0.85
  },
  {
    "iso3": "NOR",
    "name": "Norway",
    "usd": 5666940000,
    "year": "2025",
    "realChangePct": 1.7,
    "pctGni": 1.03
  },
  {
    "iso3": "SAU",
    "name": "Saudi Arabia",
    "usd": 5553680000,
    "year": "2024",
    "realChangePct": -0.9,
    "pctGni": 0.45
  },
  {
    "iso3": "ESP",
    "name": "Spain",
    "usd": 5135910000,
    "year": "2025",
    "realChangePct": 10.7,
    "pctGni": 0.27
  },
  {
    "iso3": "CHE",
    "name": "Switzerland",
    "usd": 4572530000,
    "year": "2025",
    "realChangePct": -7.1,
    "pctGni": 0.46
  },
  {
    "iso3": "KOR",
    "name": "South Korea",
    "usd": 3874520000,
    "year": "2025",
    "realChangePct": -2.3,
    "pctGni": 0.2
  },
  {
    "iso3": "DNK",
    "name": "Denmark",
    "usd": 3431140000,
    "year": "2025",
    "realChangePct": 3,
    "pctGni": 0.72
  },
  {
    "iso3": "ARE",
    "name": "United Arab Emirates",
    "usd": 3408850000,
    "year": "2025",
    "realChangePct": 55.5,
    "pctGni": 0.61
  },
  {
    "iso3": "AUS",
    "name": "Australia",
    "usd": 3291200000,
    "year": "2025",
    "realChangePct": -2.7,
    "pctGni": 0.18
  },
  {
    "iso3": "BEL",
    "name": "Belgium",
    "usd": 2717710000,
    "year": "2025",
    "realChangePct": -21.4,
    "pctGni": 0.37
  },
  {
    "iso3": "IRL",
    "name": "Ireland",
    "usd": 2094380000,
    "year": "2025",
    "realChangePct": -22.5,
    "pctGni": 0.42
  },
  {
    "iso3": "AUT",
    "name": "Austria",
    "usd": 1832970000,
    "year": "2025",
    "realChangePct": -6.3,
    "pctGni": 0.33
  },
  {
    "iso3": "POL",
    "name": "Poland",
    "usd": 1620880000,
    "year": "2025",
    "realChangePct": -19,
    "pctGni": 0.16
  },
  {
    "iso3": "FIN",
    "name": "Finland",
    "usd": 1411260000,
    "year": "2025",
    "realChangePct": -5.4,
    "pctGni": 0.44
  },
  {
    "iso3": "QAT",
    "name": "Qatar",
    "usd": 911190000,
    "year": "2025",
    "realChangePct": 23.4,
    "pctGni": 0.43
  },
  {
    "iso3": "LUX",
    "name": "Luxembourg",
    "usd": 694210000,
    "year": "2025",
    "realChangePct": 8.9,
    "pctGni": 0.99
  },
  {
    "iso3": "NZL",
    "name": "New Zealand",
    "usd": 681140000,
    "year": "2025",
    "realChangePct": -12.8,
    "pctGni": 0.27
  },
  {
    "iso3": "PRT",
    "name": "Portugal",
    "usd": 570980000,
    "year": "2025",
    "realChangePct": -19.3,
    "pctGni": 0.18
  },
  {
    "iso3": "ROU",
    "name": "Romania",
    "usd": 563030000,
    "year": "2025",
    "realChangePct": -12.4,
    "pctGni": 0.14
  },
  {
    "iso3": "TWN",
    "name": "Taiwan",
    "usd": 445700000,
    "year": "2025",
    "realChangePct": 5,
    "pctGni": 0.05
  },
  {
    "iso3": "CZE",
    "name": "Czech Republic",
    "usd": 435460000,
    "year": "2025",
    "realChangePct": -28,
    "pctGni": 0.12
  },
  {
    "iso3": "GRC",
    "name": "Greece",
    "usd": 357800000,
    "year": "2025",
    "realChangePct": -10.9,
    "pctGni": 0.13
  },
  {
    "iso3": "ISR",
    "name": "Israel",
    "usd": 308750000,
    "year": "2025",
    "realChangePct": -9.9,
    "pctGni": 0.05
  },
  {
    "iso3": "HUN",
    "name": "Hungary",
    "usd": 303360000,
    "year": "2025",
    "realChangePct": 45.7,
    "pctGni": 0.14
  },
  {
    "iso3": "HRV",
    "name": "Croatia",
    "usd": 225610000,
    "year": "2025",
    "realChangePct": -6.9,
    "pctGni": 0.24
  },
  {
    "iso3": "KWT",
    "name": "Kuwait",
    "usd": 217570000,
    "year": "2025",
    "realChangePct": -20.3,
    "pctGni": 0.11
  },
  {
    "iso3": "SVK",
    "name": "Slovakia",
    "usd": 199890000,
    "year": "2025",
    "realChangePct": -6.4,
    "pctGni": 0.13
  },
  {
    "iso3": "LTU",
    "name": "Lithuania",
    "usd": 192330000,
    "year": "2025",
    "realChangePct": -9.7,
    "pctGni": 0.21
  },
  {
    "iso3": "SVN",
    "name": "Slovenia",
    "usd": 170520000,
    "year": "2025",
    "realChangePct": -4.2,
    "pctGni": 0.22
  },
  {
    "iso3": "BGR",
    "name": "Bulgaria",
    "usd": 136750000,
    "year": "2025",
    "realChangePct": -13.2,
    "pctGni": 0.12
  },
  {
    "iso3": "ISL",
    "name": "Iceland",
    "usd": 129680000,
    "year": "2025",
    "realChangePct": 3.6,
    "pctGni": 0.34
  },
  {
    "iso3": "EST",
    "name": "Estonia",
    "usd": 89520000,
    "year": "2025",
    "realChangePct": -2,
    "pctGni": 0.19
  },
  {
    "iso3": "LVA",
    "name": "Latvia",
    "usd": 86510000,
    "year": "2025",
    "realChangePct": -9,
    "pctGni": 0.18
  },
  {
    "iso3": "THA",
    "name": "Thailand",
    "usd": 60360000,
    "year": "2024",
    "realChangePct": -13.2,
    "pctGni": 0.01
  },
  {
    "iso3": "MLT",
    "name": "Malta",
    "usd": 51100000,
    "year": "2025",
    "realChangePct": -24,
    "pctGni": 0.21
  },
  {
    "iso3": "KAZ",
    "name": "Kazakhstan",
    "usd": 50350000,
    "year": "2024",
    "realChangePct": 55.2,
    "pctGni": 0.02
  },
  {
    "iso3": "AZE",
    "name": "Azerbaijan",
    "usd": 47470000,
    "year": "2025",
    "realChangePct": -25.7,
    "pctGni": 0.06
  },
  {
    "iso3": "LIE",
    "name": "Liechtenstein",
    "usd": 40790000,
    "year": "2025",
    "realChangePct": -6.2,
    "pctGni": null
  },
  {
    "iso3": "MCO",
    "name": "Monaco",
    "usd": 33290000,
    "year": "2025",
    "realChangePct": 10.7,
    "pctGni": null
  },
  {
    "iso3": "CYP",
    "name": "Cyprus",
    "usd": 12890000,
    "year": "2024",
    "realChangePct": 7.2,
    "pctGni": 0.04
  }
];
