/**
 * GDP composition by sector, per economy.
 *
 * GENERATED by build-economy-sectors.cjs on 2026-09-23 — do not edit by hand;
 * change the script and re-run it.
 *
 * Three shares that partition value added, from the World Bank's national
 * accounts, all four figures for an economy taken from the same year:
 *
 *   agriculture    NV.AGR.TOTL.ZS   ISIC rev.4 01-03
 *   industry       NV.IND.TOTL.ZS   ISIC rev.4 05-43, including construction
 *   services       NV.SRV.TOTL.ZS   ISIC rev.4 45-99
 *
 * `manufacturing` (NV.IND.MANF.ZS) is part of industry, not a fourth sector —
 * the World Bank's definition has industry "comprised of mining, manufacturing,
 * construction, electricity, water, and gas". It is here to be quoted as an
 * "of which" figure and must never be given a slice of its own. Finance is
 * likewise inside services, whose definition covers "financial intermediation".
 *
 * `other` is what is left of GDP once the three are counted: taxes less
 * subsidies on products, plus any statistical discrepancy, arising because
 * value added is measured at basic prices and GDP at purchaser prices. It is
 * kept rather than scaled away, because scaling it away would overstate every
 * other share.
 *
 * 206 of the 214 economies on the page have a figure; years 2015, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025.
 */
export const ECONOMY_SECTORS_SOURCE = {
  label: "World Bank — national accounts, value added by sector (% of GDP)",
  url: "https://data.worldbank.org/indicator/NV.AGR.TOTL.ZS",
  retrieved: "2026-09-23",
};

export type EconomySectors = {
  name: string;
  /** World Bank entity code the figures were read from. */
  code: string;
  year: string;
  /**
   * What the slices are shares of. "gdp" is the usual case, and the slices
   * include taxes less subsidies on products. "valueAdded" is used where
   * subsidies on products exceed taxes, so value added comes to more than GDP
   * and there is no positive remainder to draw.
   */
  basis: "gdp" | "valueAdded";
  /** Sums to exactly 100, so each slice's size is the number printed on it. */
  slices: { name: string; pct: number }[];
  /** Part of the industry slice, never a slice of its own. Percent of GDP. */
  manufacturing: number | null;
  /**
   * The largest single industry within manufacturing, where the source breaks
   * it down that far. Only Taiwan's statistics office does; the World Bank and
   * the UN both stop at the aggregate, so this is absent for everyone else
   * rather than guessed at.
   */
  topSubSector?: { name: string; pct: number };
  /**
   * Which body published the figures. The World Bank covers all but a few; the
   * UN Statistics Division fills gaps the World Bank does not report, and its
   * shares are of value added rather than of GDP. Taiwan comes from its own
   * statistics office, which neither of the others covers.
   */
  source: "worldBank" | "un" | "dgbas";
};

/** Keyed by the economy id used in economiesData.ts. */
export const ECONOMY_SECTORS: Record<string, EconomySectors> = {
  "afghanistan-eco": {
    name: "Afghanistan", code: "AFG", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 8.4,
    slices: [{ name: "Agriculture", pct: 34.3 }, { name: "Industry", pct: 14.5 }, { name: "Services", pct: 45.2 }, { name: "Taxes less subsidies", pct: 6 }],
  },
  "albania-eco": {
    name: "Albania", code: "ALB", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 6,
    slices: [{ name: "Agriculture", pct: 14.8 }, { name: "Industry", pct: 21.8 }, { name: "Services", pct: 49.7 }, { name: "Taxes less subsidies", pct: 13.7 }],
  },
  "algeria-eco": {
    name: "Algeria", code: "DZA", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 14.5 }, { name: "Industry", pct: 34.8 }, { name: "Services", pct: 45.7 }, { name: "Taxes less subsidies", pct: 5 }],
  },
  "andorra-eco": {
    name: "Andorra", code: "AND", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 0.5 }, { name: "Industry", pct: 12.8 }, { name: "Services", pct: 77.8 }, { name: "Taxes less subsidies", pct: 8.9 }],
  },
  "angola-eco": {
    name: "Angola", code: "AGO", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 6.8,
    slices: [{ name: "Agriculture", pct: 25.2 }, { name: "Industry", pct: 27.1 }, { name: "Services", pct: 46.8 }, { name: "Taxes less subsidies", pct: 0.9 }],
  },
  "antiguabarbuda-eco": {
    name: "Antigua & Barbuda", code: "ATG", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 2.4,
    slices: [{ name: "Agriculture", pct: 1.5 }, { name: "Industry", pct: 18.2 }, { name: "Services", pct: 68.6 }, { name: "Taxes less subsidies", pct: 11.7 }],
  },
  "argentina-eco": {
    name: "Argentina", code: "ARG", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 13.6,
    slices: [{ name: "Agriculture", pct: 5.5 }, { name: "Industry", pct: 22.9 }, { name: "Services", pct: 56.2 }, { name: "Taxes less subsidies", pct: 15.4 }],
  },
  "armenia-eco": {
    name: "Armenia", code: "ARM", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 11,
    slices: [{ name: "Agriculture", pct: 7.9 }, { name: "Industry", pct: 23.1 }, { name: "Services", pct: 61.3 }, { name: "Taxes less subsidies", pct: 7.7 }],
  },
  "aruba-eco": {
    name: "Aruba", code: "ABW", year: "2023", basis: "gdp", source: "worldBank",
    manufacturing: 2.4,
    slices: [{ name: "Agriculture", pct: 0 }, { name: "Industry", pct: 10.8 }, { name: "Services", pct: 76.4 }, { name: "Taxes less subsidies", pct: 12.8 }],
  },
  "australia-eco": {
    name: "Australia", code: "AUS", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 5.3,
    slices: [{ name: "Agriculture", pct: 2.3 }, { name: "Industry", pct: 23.9 }, { name: "Services", pct: 67.4 }, { name: "Taxes less subsidies", pct: 6.4 }],
  },
  "austria-eco": {
    name: "Austria", code: "AUT", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 15.2,
    slices: [{ name: "Agriculture", pct: 1.3 }, { name: "Industry", pct: 24 }, { name: "Services", pct: 64 }, { name: "Taxes less subsidies", pct: 10.7 }],
  },
  "azerbaijan-eco": {
    name: "Azerbaijan", code: "AZE", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 6,
    slices: [{ name: "Agriculture", pct: 5.9 }, { name: "Industry", pct: 39.5 }, { name: "Services", pct: 45.3 }, { name: "Taxes less subsidies", pct: 9.3 }],
  },
  "bahamas-eco": {
    name: "Bahamas", code: "BHS", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 0.6,
    slices: [{ name: "Agriculture", pct: 0.5 }, { name: "Industry", pct: 9.6 }, { name: "Services", pct: 77.2 }, { name: "Taxes less subsidies", pct: 12.7 }],
  },
  "bahrain-eco": {
    name: "Bahrain", code: "BHR", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 19.9,
    slices: [{ name: "Agriculture", pct: 0.2 }, { name: "Industry", pct: 41.2 }, { name: "Services", pct: 54.4 }, { name: "Taxes less subsidies", pct: 4.2 }],
  },
  "bangladesh-eco": {
    name: "Bangladesh", code: "BGD", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 22.4,
    slices: [{ name: "Agriculture", pct: 11.4 }, { name: "Industry", pct: 34 }, { name: "Services", pct: 52.2 }, { name: "Taxes less subsidies", pct: 2.4 }],
  },
  "barbados-eco": {
    name: "Barbados", code: "BRB", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 4.9,
    slices: [{ name: "Agriculture", pct: 1.6 }, { name: "Industry", pct: 12.2 }, { name: "Services", pct: 75.8 }, { name: "Taxes less subsidies", pct: 10.4 }],
  },
  "belarus-eco": {
    name: "Belarus", code: "BLR", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 20.5,
    slices: [{ name: "Agriculture", pct: 6.9 }, { name: "Industry", pct: 31.6 }, { name: "Services", pct: 50 }, { name: "Taxes less subsidies", pct: 11.5 }],
  },
  "belgium-eco": {
    name: "Belgium", code: "BEL", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 11.2,
    slices: [{ name: "Agriculture", pct: 0.7 }, { name: "Industry", pct: 18.6 }, { name: "Services", pct: 71.3 }, { name: "Taxes less subsidies", pct: 9.4 }],
  },
  "belize-eco": {
    name: "Belize", code: "BLZ", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 6.6,
    slices: [{ name: "Agriculture", pct: 7.9 }, { name: "Industry", pct: 14.6 }, { name: "Services", pct: 62.5 }, { name: "Taxes less subsidies", pct: 15 }],
  },
  "benin-eco": {
    name: "Benin", code: "BEN", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 10.2,
    slices: [{ name: "Agriculture", pct: 22.9 }, { name: "Industry", pct: 17.5 }, { name: "Services", pct: 50.1 }, { name: "Taxes less subsidies", pct: 9.5 }],
  },
  "bermuda-eco": {
    name: "Bermuda", code: "BMU", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 0.3,
    slices: [{ name: "Agriculture", pct: 0.2 }, { name: "Industry", pct: 4.9 }, { name: "Services", pct: 91.3 }, { name: "Taxes less subsidies", pct: 3.6 }],
  },
  "bhutan-eco": {
    name: "Bhutan", code: "BTN", year: "2025", basis: "valueAdded", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 13.7 }, { name: "Industry", pct: 33.2 }, { name: "Services", pct: 53.1 }],
  },
  "bolivia-eco": {
    name: "Bolivia", code: "BOL", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 13.1,
    slices: [{ name: "Agriculture", pct: 8.8 }, { name: "Industry", pct: 31.3 }, { name: "Services", pct: 53.3 }, { name: "Taxes less subsidies", pct: 6.6 }],
  },
  "bosniaherzegovina-eco": {
    name: "Bosnia & Herzegovina", code: "BIH", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 12,
    slices: [{ name: "Agriculture", pct: 4.4 }, { name: "Industry", pct: 21.5 }, { name: "Services", pct: 57.7 }, { name: "Taxes less subsidies", pct: 16.4 }],
  },
  "botswana-eco": {
    name: "Botswana", code: "BWA", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 5.7,
    slices: [{ name: "Agriculture", pct: 1.8 }, { name: "Industry", pct: 27.9 }, { name: "Services", pct: 64.6 }, { name: "Taxes less subsidies", pct: 5.7 }],
  },
  "brazil-eco": {
    name: "Brazil", code: "BRA", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 11.8,
    slices: [{ name: "Agriculture", pct: 6.1 }, { name: "Industry", pct: 20.1 }, { name: "Services", pct: 59.8 }, { name: "Taxes less subsidies", pct: 14 }],
  },
  "brunei-eco": {
    name: "Brunei", code: "BRN", year: "2025", basis: "valueAdded", source: "worldBank",
    manufacturing: 9.9,
    slices: [{ name: "Agriculture", pct: 1.2 }, { name: "Industry", pct: 59.1 }, { name: "Services", pct: 39.7 }],
  },
  "bulgaria-eco": {
    name: "Bulgaria", code: "BGR", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 2.5 }, { name: "Industry", pct: 21.2 }, { name: "Services", pct: 63.3 }, { name: "Taxes less subsidies", pct: 13 }],
  },
  "burkinafaso-eco": {
    name: "Burkina Faso", code: "BFA", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 6.6,
    slices: [{ name: "Agriculture", pct: 19.9 }, { name: "Industry", pct: 30.1 }, { name: "Services", pct: 41.5 }, { name: "Taxes less subsidies", pct: 8.5 }],
  },
  "burundi-eco": {
    name: "Burundi", code: "BDI", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 13.1,
    slices: [{ name: "Agriculture", pct: 34.3 }, { name: "Industry", pct: 18.2 }, { name: "Services", pct: 42.1 }, { name: "Taxes less subsidies", pct: 5.4 }],
  },
  "cambodia-eco": {
    name: "Cambodia", code: "KHM", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 29,
    slices: [{ name: "Agriculture", pct: 16.1 }, { name: "Industry", pct: 43.1 }, { name: "Services", pct: 35 }, { name: "Taxes less subsidies", pct: 5.8 }],
  },
  "cameroon-eco": {
    name: "Cameroon", code: "CMR", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 14.6,
    slices: [{ name: "Agriculture", pct: 16.8 }, { name: "Industry", pct: 24.8 }, { name: "Services", pct: 50.4 }, { name: "Taxes less subsidies", pct: 8 }],
  },
  "canada-eco": {
    name: "Canada", code: "CAN", year: "2022", basis: "gdp", source: "worldBank",
    manufacturing: 9.3,
    slices: [{ name: "Agriculture", pct: 1.9 }, { name: "Industry", pct: 27.4 }, { name: "Services", pct: 64.1 }, { name: "Taxes less subsidies", pct: 6.6 }],
  },
  "capeverde-eco": {
    name: "Cape Verde", code: "CPV", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 5.2,
    slices: [{ name: "Agriculture", pct: 5 }, { name: "Industry", pct: 10.7 }, { name: "Services", pct: 68 }, { name: "Taxes less subsidies", pct: 16.3 }],
  },
  "caymanislands-eco": {
    name: "Cayman Islands", code: "CYM", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 0.9,
    slices: [{ name: "Agriculture", pct: 0.5 }, { name: "Industry", pct: 7.6 }, { name: "Services", pct: 86.5 }, { name: "Taxes less subsidies", pct: 5.4 }],
  },
  "centralafricanrepublic-eco": {
    name: "Central African Republic", code: "CAF", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 27.6 }, { name: "Industry", pct: 21.2 }, { name: "Services", pct: 41.4 }, { name: "Taxes less subsidies", pct: 9.8 }],
  },
  "chad-eco": {
    name: "Chad", code: "TCD", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 36.4 }, { name: "Industry", pct: 26.7 }, { name: "Services", pct: 33.9 }, { name: "Taxes less subsidies", pct: 3 }],
  },
  "chile-eco": {
    name: "Chile", code: "CHL", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 9,
    slices: [{ name: "Agriculture", pct: 3.5 }, { name: "Industry", pct: 31.4 }, { name: "Services", pct: 55.5 }, { name: "Taxes less subsidies", pct: 9.6 }],
  },
  "china-eco": {
    name: "China", code: "CHN", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 24.7,
    slices: [{ name: "Agriculture", pct: 6.7 }, { name: "Industry", pct: 35.6 }, { name: "Services", pct: 57.7 }, { name: "Taxes less subsidies", pct: 0 }],
  },
  "colombia-eco": {
    name: "Colombia", code: "COL", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 9.9,
    slices: [{ name: "Agriculture", pct: 9.9 }, { name: "Industry", pct: 21.8 }, { name: "Services", pct: 58.5 }, { name: "Taxes less subsidies", pct: 9.8 }],
  },
  "comoros-eco": {
    name: "Comoros", code: "COM", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 7.2,
    slices: [{ name: "Agriculture", pct: 36.6 }, { name: "Industry", pct: 9.9 }, { name: "Services", pct: 48.8 }, { name: "Taxes less subsidies", pct: 4.7 }],
  },
  "costarica-eco": {
    name: "Costa Rica", code: "CRI", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 13.6,
    slices: [{ name: "Agriculture", pct: 3.4 }, { name: "Industry", pct: 19.9 }, { name: "Services", pct: 69.2 }, { name: "Taxes less subsidies", pct: 7.5 }],
  },
  "cotedivoire-eco": {
    name: "Côte d'Ivoire", code: "CIV", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 12.3,
    slices: [{ name: "Agriculture", pct: 16.8 }, { name: "Industry", pct: 23.9 }, { name: "Services", pct: 51.2 }, { name: "Taxes less subsidies", pct: 8.1 }],
  },
  "croatia-eco": {
    name: "Croatia", code: "HRV", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 10.1,
    slices: [{ name: "Agriculture", pct: 2.8 }, { name: "Industry", pct: 19 }, { name: "Services", pct: 60.9 }, { name: "Taxes less subsidies", pct: 17.3 }],
  },
  "cuba-eco": {
    name: "Cuba", code: "CUB", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 10.7,
    slices: [{ name: "Agriculture", pct: 1.2 }, { name: "Industry", pct: 23.8 }, { name: "Services", pct: 73.5 }, { name: "Taxes less subsidies", pct: 1.5 }],
  },
  "curacao-eco": {
    name: "Curaçao", code: "CUW", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 2.9,
    slices: [{ name: "Agriculture", pct: 0.3 }, { name: "Industry", pct: 12.2 }, { name: "Services", pct: 72.3 }, { name: "Taxes less subsidies", pct: 15.2 }],
  },
  "cyprus-eco": {
    name: "Cyprus", code: "CYP", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 4.4,
    slices: [{ name: "Agriculture", pct: 1.1 }, { name: "Industry", pct: 11.1 }, { name: "Services", pct: 76.9 }, { name: "Taxes less subsidies", pct: 10.9 }],
  },
  "czechia-eco": {
    name: "Czechia", code: "CZE", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 19.4,
    slices: [{ name: "Agriculture", pct: 1.9 }, { name: "Industry", pct: 28.7 }, { name: "Services", pct: 60.9 }, { name: "Taxes less subsidies", pct: 8.5 }],
  },
  "denmark-eco": {
    name: "Denmark", code: "DNK", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 18.7,
    slices: [{ name: "Agriculture", pct: 1.2 }, { name: "Industry", pct: 24.8 }, { name: "Services", pct: 62.7 }, { name: "Taxes less subsidies", pct: 11.3 }],
  },
  "djibouti-eco": {
    name: "Djibouti", code: "DJI", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 2.3 }, { name: "Industry", pct: 16.6 }, { name: "Services", pct: 75.6 }, { name: "Taxes less subsidies", pct: 5.5 }],
  },
  "dominica-eco": {
    name: "Dominica", code: "DMA", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 4.8,
    slices: [{ name: "Agriculture", pct: 12.1 }, { name: "Industry", pct: 14.1 }, { name: "Services", pct: 57.2 }, { name: "Taxes less subsidies", pct: 16.6 }],
  },
  "dominicanrepublic-eco": {
    name: "Dominican Republic", code: "DOM", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 12.3,
    slices: [{ name: "Agriculture", pct: 4.6 }, { name: "Industry", pct: 28.4 }, { name: "Services", pct: 60.1 }, { name: "Taxes less subsidies", pct: 6.9 }],
  },
  "drcongo-eco": {
    name: "DR Congo", code: "COD", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 7.9,
    slices: [{ name: "Agriculture", pct: 8.9 }, { name: "Industry", pct: 39.7 }, { name: "Services", pct: 48 }, { name: "Taxes less subsidies", pct: 3.4 }],
  },
  "ecuador-eco": {
    name: "Ecuador", code: "ECU", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 13.2,
    slices: [{ name: "Agriculture", pct: 9.7 }, { name: "Industry", pct: 25.7 }, { name: "Services", pct: 56.9 }, { name: "Taxes less subsidies", pct: 7.7 }],
  },
  "egypt-eco": {
    name: "Egypt", code: "EGY", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 14.5,
    slices: [{ name: "Agriculture", pct: 16.6 }, { name: "Industry", pct: 32.1 }, { name: "Services", pct: 47.2 }, { name: "Taxes less subsidies", pct: 4.1 }],
  },
  "elsalvador-eco": {
    name: "El Salvador", code: "SLV", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 12.7,
    slices: [{ name: "Agriculture", pct: 4.4 }, { name: "Industry", pct: 24.5 }, { name: "Services", pct: 58.9 }, { name: "Taxes less subsidies", pct: 12.2 }],
  },
  "equatorialguinea-eco": {
    name: "Equatorial Guinea", code: "GNQ", year: "2025", basis: "valueAdded", source: "worldBank",
    manufacturing: 22.3,
    slices: [{ name: "Agriculture", pct: 3.2 }, { name: "Industry", pct: 41.4 }, { name: "Services", pct: 55.4 }],
  },
  "estonia-eco": {
    name: "Estonia", code: "EST", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 10.8,
    slices: [{ name: "Agriculture", pct: 1.6 }, { name: "Industry", pct: 19.7 }, { name: "Services", pct: 65.9 }, { name: "Taxes less subsidies", pct: 12.8 }],
  },
  "eswatini-eco": {
    name: "Eswatini", code: "SWZ", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 28.1,
    slices: [{ name: "Agriculture", pct: 6.4 }, { name: "Industry", pct: 33.6 }, { name: "Services", pct: 52.4 }, { name: "Taxes less subsidies", pct: 7.6 }],
  },
  "ethiopia-eco": {
    name: "Ethiopia", code: "ETH", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 4.2,
    slices: [{ name: "Agriculture", pct: 32.8 }, { name: "Industry", pct: 27.8 }, { name: "Services", pct: 36.6 }, { name: "Taxes less subsidies", pct: 2.8 }],
  },
  "eu-eco": {
    name: "European Union", code: "EUU", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 14.3,
    slices: [{ name: "Agriculture", pct: 1.6 }, { name: "Industry", pct: 22.2 }, { name: "Services", pct: 65.9 }, { name: "Taxes less subsidies", pct: 10.3 }],
  },
  "faroeislands-eco": {
    name: "Faroe Islands", code: "FRO", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 9.5,
    slices: [{ name: "Agriculture", pct: 16.1 }, { name: "Industry", pct: 18.3 }, { name: "Services", pct: 53.8 }, { name: "Taxes less subsidies", pct: 11.8 }],
  },
  "fiji-eco": {
    name: "Fiji", code: "FJI", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 9.1,
    slices: [{ name: "Agriculture", pct: 14 }, { name: "Industry", pct: 13.9 }, { name: "Services", pct: 57 }, { name: "Taxes less subsidies", pct: 15.1 }],
  },
  "finland-eco": {
    name: "Finland", code: "FIN", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 14.2,
    slices: [{ name: "Agriculture", pct: 2.6 }, { name: "Industry", pct: 22.5 }, { name: "Services", pct: 62.1 }, { name: "Taxes less subsidies", pct: 12.8 }],
  },
  "france-eco": {
    name: "France", code: "FRA", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 9.5,
    slices: [{ name: "Agriculture", pct: 1.4 }, { name: "Industry", pct: 16.8 }, { name: "Services", pct: 70.8 }, { name: "Taxes less subsidies", pct: 11 }],
  },
  "frenchpolynesia-eco": {
    name: "French Polynesia", code: "PYF", year: "2020", basis: "gdp", source: "worldBank",
    manufacturing: 4.7,
    slices: [{ name: "Agriculture", pct: 2.2 }, { name: "Industry", pct: 10.6 }, { name: "Services", pct: 76 }, { name: "Taxes less subsidies", pct: 11.2 }],
  },
  "gabon-eco": {
    name: "Gabon", code: "GAB", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 19.1,
    slices: [{ name: "Agriculture", pct: 6.8 }, { name: "Industry", pct: 47.2 }, { name: "Services", pct: 42.3 }, { name: "Taxes less subsidies", pct: 3.7 }],
  },
  "gambia-eco": {
    name: "Gambia", code: "GMB", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 23.8 }, { name: "Industry", pct: 15.8 }, { name: "Services", pct: 53.1 }, { name: "Taxes less subsidies", pct: 7.3 }],
  },
  "georgia-eco": {
    name: "Georgia", code: "GEO", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 8,
    slices: [{ name: "Agriculture", pct: 5.2 }, { name: "Industry", pct: 18.6 }, { name: "Services", pct: 63.9 }, { name: "Taxes less subsidies", pct: 12.3 }],
  },
  "germany-eco": {
    name: "Germany", code: "DEU", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 17.6,
    slices: [{ name: "Agriculture", pct: 0.9 }, { name: "Industry", pct: 25.2 }, { name: "Services", pct: 64.4 }, { name: "Taxes less subsidies", pct: 9.5 }],
  },
  "ghana-eco": {
    name: "Ghana", code: "GHA", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 10.1,
    slices: [{ name: "Agriculture", pct: 21.3 }, { name: "Industry", pct: 29.3 }, { name: "Services", pct: 42.8 }, { name: "Taxes less subsidies", pct: 6.6 }],
  },
  "greece-eco": {
    name: "Greece", code: "GRC", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 9.1,
    slices: [{ name: "Agriculture", pct: 3.6 }, { name: "Industry", pct: 15.2 }, { name: "Services", pct: 67.4 }, { name: "Taxes less subsidies", pct: 13.8 }],
  },
  "greenland-eco": {
    name: "Greenland", code: "GRL", year: "2023", basis: "gdp", source: "worldBank",
    manufacturing: 2.7,
    slices: [{ name: "Agriculture", pct: 16.6 }, { name: "Industry", pct: 18.4 }, { name: "Services", pct: 61 }, { name: "Taxes less subsidies", pct: 4 }],
  },
  "grenada-eco": {
    name: "Grenada", code: "GRD", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 3.3,
    slices: [{ name: "Agriculture", pct: 2.5 }, { name: "Industry", pct: 15.5 }, { name: "Services", pct: 65 }, { name: "Taxes less subsidies", pct: 17 }],
  },
  "guatemala-eco": {
    name: "Guatemala", code: "GTM", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 13.2,
    slices: [{ name: "Agriculture", pct: 9.6 }, { name: "Industry", pct: 21.8 }, { name: "Services", pct: 62.1 }, { name: "Taxes less subsidies", pct: 6.5 }],
  },
  "guinea-eco": {
    name: "Guinea", code: "GIN", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 31.3 }, { name: "Industry", pct: 25.4 }, { name: "Services", pct: 35.7 }, { name: "Taxes less subsidies", pct: 7.6 }],
  },
  "guineabissau-eco": {
    name: "Guinea-Bissau", code: "GNB", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 8.6,
    slices: [{ name: "Agriculture", pct: 40.6 }, { name: "Industry", pct: 15.7 }, { name: "Services", pct: 39.1 }, { name: "Taxes less subsidies", pct: 4.6 }],
  },
  "guyana-eco": {
    name: "Guyana", code: "GUY", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 1.9,
    slices: [{ name: "Agriculture", pct: 7.7 }, { name: "Industry", pct: 75.2 }, { name: "Services", pct: 14.8 }, { name: "Taxes less subsidies", pct: 2.3 }],
  },
  "haiti-eco": {
    name: "Haiti", code: "HTI", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 20.2,
    slices: [{ name: "Agriculture", pct: 15.8 }, { name: "Industry", pct: 27.5 }, { name: "Services", pct: 54.2 }, { name: "Taxes less subsidies", pct: 2.5 }],
  },
  "honduras-eco": {
    name: "Honduras", code: "HND", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 15,
    slices: [{ name: "Agriculture", pct: 13.3 }, { name: "Industry", pct: 25.4 }, { name: "Services", pct: 57.6 }, { name: "Taxes less subsidies", pct: 3.7 }],
  },
  "hongkong-eco": {
    name: "Hong Kong", code: "HKG", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 0.9,
    slices: [{ name: "Agriculture", pct: 0 }, { name: "Industry", pct: 6.2 }, { name: "Services", pct: 91.5 }, { name: "Taxes less subsidies", pct: 2.3 }],
  },
  "hungary-eco": {
    name: "Hungary", code: "HUN", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 15.1,
    slices: [{ name: "Agriculture", pct: 2.7 }, { name: "Industry", pct: 23 }, { name: "Services", pct: 60 }, { name: "Taxes less subsidies", pct: 14.3 }],
  },
  "iceland-eco": {
    name: "Iceland", code: "ISL", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 8.5,
    slices: [{ name: "Agriculture", pct: 3.7 }, { name: "Industry", pct: 20.1 }, { name: "Services", pct: 66.1 }, { name: "Taxes less subsidies", pct: 10.1 }],
  },
  "india-eco": {
    name: "India", code: "IND", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 13.5,
    slices: [{ name: "Agriculture", pct: 16.2 }, { name: "Industry", pct: 25.2 }, { name: "Services", pct: 49.4 }, { name: "Taxes less subsidies", pct: 9.2 }],
  },
  "indonesia-eco": {
    name: "Indonesia", code: "IDN", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 19.1,
    slices: [{ name: "Agriculture", pct: 13.1 }, { name: "Industry", pct: 38.7 }, { name: "Services", pct: 43.9 }, { name: "Taxes less subsidies", pct: 4.3 }],
  },
  "iran-eco": {
    name: "Iran", code: "IRN", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 10.6 }, { name: "Industry", pct: 39.6 }, { name: "Services", pct: 47.1 }, { name: "Taxes less subsidies", pct: 2.7 }],
  },
  "iraq-eco": {
    name: "Iraq", code: "IRQ", year: "2025", basis: "valueAdded", source: "worldBank",
    manufacturing: 4,
    slices: [{ name: "Agriculture", pct: 3.4 }, { name: "Industry", pct: 44.9 }, { name: "Services", pct: 51.7 }],
  },
  "ireland-eco": {
    name: "Ireland", code: "IRL", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 33.9,
    slices: [{ name: "Agriculture", pct: 1.1 }, { name: "Industry", pct: 37.8 }, { name: "Services", pct: 56.6 }, { name: "Taxes less subsidies", pct: 4.5 }],
  },
  "isleofman-eco": {
    name: "Isle of Man", code: "IMN", year: "2023", basis: "valueAdded", source: "worldBank",
    manufacturing: 2,
    slices: [{ name: "Agriculture", pct: 0.4 }, { name: "Industry", pct: 7.2 }, { name: "Services", pct: 92.4 }],
  },
  "israel-eco": {
    name: "Israel", code: "ISR", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 11.2,
    slices: [{ name: "Agriculture", pct: 1.3 }, { name: "Industry", pct: 17.2 }, { name: "Services", pct: 72.9 }, { name: "Taxes less subsidies", pct: 8.6 }],
  },
  "italy-eco": {
    name: "Italy", code: "ITA", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 15,
    slices: [{ name: "Agriculture", pct: 2.1 }, { name: "Industry", pct: 22.6 }, { name: "Services", pct: 64.5 }, { name: "Taxes less subsidies", pct: 10.8 }],
  },
  "jamaica-eco": {
    name: "Jamaica", code: "JAM", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 7.7,
    slices: [{ name: "Agriculture", pct: 8.7 }, { name: "Industry", pct: 16.3 }, { name: "Services", pct: 59.9 }, { name: "Taxes less subsidies", pct: 15.1 }],
  },
  "japan-eco": {
    name: "Japan", code: "JPN", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 18.8,
    slices: [{ name: "Agriculture", pct: 1 }, { name: "Industry", pct: 26.8 }, { name: "Services", pct: 71.4 }, { name: "Taxes less subsidies", pct: 0.8 }],
  },
  "jordan-eco": {
    name: "Jordan", code: "JOR", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 17.4,
    slices: [{ name: "Agriculture", pct: 5.6 }, { name: "Industry", pct: 27.4 }, { name: "Services", pct: 56.7 }, { name: "Taxes less subsidies", pct: 10.3 }],
  },
  "kazakhstan-eco": {
    name: "Kazakhstan", code: "KAZ", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 12.7,
    slices: [{ name: "Agriculture", pct: 3.7 }, { name: "Industry", pct: 32.3 }, { name: "Services", pct: 57.8 }, { name: "Taxes less subsidies", pct: 6.2 }],
  },
  "kenya-eco": {
    name: "Kenya", code: "KEN", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 7.1,
    slices: [{ name: "Agriculture", pct: 23.2 }, { name: "Industry", pct: 16.3 }, { name: "Services", pct: 55 }, { name: "Taxes less subsidies", pct: 5.5 }],
  },
  "kiribati-eco": {
    name: "Kiribati", code: "KIR", year: "2024", basis: "valueAdded", source: "worldBank",
    manufacturing: 4.2,
    slices: [{ name: "Agriculture", pct: 22 }, { name: "Industry", pct: 11.2 }, { name: "Services", pct: 66.8 }],
  },
  "kosovo-eco": {
    name: "Kosovo", code: "XKX", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 12.5,
    slices: [{ name: "Agriculture", pct: 7.4 }, { name: "Industry", pct: 25 }, { name: "Services", pct: 46.1 }, { name: "Taxes less subsidies", pct: 21.5 }],
  },
  "kuwait-eco": {
    name: "Kuwait", code: "KWT", year: "2025", basis: "valueAdded", source: "worldBank",
    manufacturing: 7.7,
    slices: [{ name: "Agriculture", pct: 0.5 }, { name: "Industry", pct: 47.4 }, { name: "Services", pct: 52.1 }],
  },
  "kyrgyzstan-eco": {
    name: "Kyrgyzstan", code: "KGZ", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 13.7,
    slices: [{ name: "Agriculture", pct: 8 }, { name: "Industry", pct: 26.5 }, { name: "Services", pct: 51.1 }, { name: "Taxes less subsidies", pct: 14.4 }],
  },
  "laos-eco": {
    name: "Laos", code: "LAO", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 9.1,
    slices: [{ name: "Agriculture", pct: 16.6 }, { name: "Industry", pct: 29.2 }, { name: "Services", pct: 43.6 }, { name: "Taxes less subsidies", pct: 10.6 }],
  },
  "latvia-eco": {
    name: "Latvia", code: "LVA", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 10,
    slices: [{ name: "Agriculture", pct: 4 }, { name: "Industry", pct: 18.7 }, { name: "Services", pct: 64.2 }, { name: "Taxes less subsidies", pct: 13.1 }],
  },
  "lebanon-eco": {
    name: "Lebanon", code: "LBN", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 1 }, { name: "Industry", pct: 2.6 }, { name: "Services", pct: 35.7 }, { name: "Taxes less subsidies", pct: 60.7 }],
  },
  "lesotho-eco": {
    name: "Lesotho", code: "LSO", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 6.5 }, { name: "Industry", pct: 25.2 }, { name: "Services", pct: 55.5 }, { name: "Taxes less subsidies", pct: 12.8 }],
  },
  "liberia-eco": {
    name: "Liberia", code: "LBR", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 32.7 }, { name: "Industry", pct: 24.5 }, { name: "Services", pct: 40 }, { name: "Taxes less subsidies", pct: 2.8 }],
  },
  "libya-eco": {
    name: "Libya", code: "LBY", year: "2025", basis: "valueAdded", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 1.5 }, { name: "Industry", pct: 72 }, { name: "Services", pct: 26.5 }],
  },
  "liechtenstein-eco": {
    name: "Liechtenstein", code: "LIE", year: "2023", basis: "gdp", source: "worldBank",
    manufacturing: 34.2,
    slices: [{ name: "Agriculture", pct: 0.2 }, { name: "Industry", pct: 39.1 }, { name: "Services", pct: 57.4 }, { name: "Taxes less subsidies", pct: 3.3 }],
  },
  "lithuania-eco": {
    name: "Lithuania", code: "LTU", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 13.1,
    slices: [{ name: "Agriculture", pct: 2.3 }, { name: "Industry", pct: 22.1 }, { name: "Services", pct: 64.8 }, { name: "Taxes less subsidies", pct: 10.8 }],
  },
  "luxembourg-eco": {
    name: "Luxembourg", code: "LUX", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 3.7,
    slices: [{ name: "Agriculture", pct: 0.2 }, { name: "Industry", pct: 8.9 }, { name: "Services", pct: 81.5 }, { name: "Taxes less subsidies", pct: 9.4 }],
  },
  "madagascar-eco": {
    name: "Madagascar", code: "MDG", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 21.7 }, { name: "Industry", pct: 23.9 }, { name: "Services", pct: 48.8 }, { name: "Taxes less subsidies", pct: 5.6 }],
  },
  "malawi-eco": {
    name: "Malawi", code: "MWI", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 30 }, { name: "Industry", pct: 14.3 }, { name: "Services", pct: 48.7 }, { name: "Taxes less subsidies", pct: 7 }],
  },
  "malaysia-eco": {
    name: "Malaysia", code: "MYS", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 22.1,
    slices: [{ name: "Agriculture", pct: 8.2 }, { name: "Industry", pct: 35.7 }, { name: "Services", pct: 54.8 }, { name: "Taxes less subsidies", pct: 1.3 }],
  },
  "maldives-eco": {
    name: "Maldives", code: "MDV", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 1.8,
    slices: [{ name: "Agriculture", pct: 4.6 }, { name: "Industry", pct: 9.3 }, { name: "Services", pct: 69.9 }, { name: "Taxes less subsidies", pct: 16.2 }],
  },
  "mali-eco": {
    name: "Mali", code: "MLI", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 7.5,
    slices: [{ name: "Agriculture", pct: 33 }, { name: "Industry", pct: 23.4 }, { name: "Services", pct: 36.5 }, { name: "Taxes less subsidies", pct: 7.1 }],
  },
  "malta-eco": {
    name: "Malta", code: "MLT", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 5.3,
    slices: [{ name: "Agriculture", pct: 0.5 }, { name: "Industry", pct: 10.1 }, { name: "Services", pct: 81.3 }, { name: "Taxes less subsidies", pct: 8.1 }],
  },
  "marshallislands-eco": {
    name: "Marshall Islands", code: "MHL", year: "2024", basis: "valueAdded", source: "worldBank",
    manufacturing: 3.2,
    slices: [{ name: "Agriculture", pct: 19.6 }, { name: "Industry", pct: 13.2 }, { name: "Services", pct: 67.2 }],
  },
  "mauritania-eco": {
    name: "Mauritania", code: "MRT", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 4.6,
    slices: [{ name: "Agriculture", pct: 20 }, { name: "Industry", pct: 29.7 }, { name: "Services", pct: 42.4 }, { name: "Taxes less subsidies", pct: 7.9 }],
  },
  "mauritius-eco": {
    name: "Mauritius", code: "MUS", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 11.2,
    slices: [{ name: "Agriculture", pct: 4.6 }, { name: "Industry", pct: 17.7 }, { name: "Services", pct: 63.9 }, { name: "Taxes less subsidies", pct: 13.8 }],
  },
  "mexico-eco": {
    name: "Mexico", code: "MEX", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 20,
    slices: [{ name: "Agriculture", pct: 3.9 }, { name: "Industry", pct: 30.6 }, { name: "Services", pct: 58.8 }, { name: "Taxes less subsidies", pct: 6.7 }],
  },
  "micronesia-eco": {
    name: "Micronesia", code: "FSM", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 0.5,
    slices: [{ name: "Agriculture", pct: 24.2 }, { name: "Industry", pct: 5.3 }, { name: "Services", pct: 65.2 }, { name: "Taxes less subsidies", pct: 5.3 }],
  },
  "moldova-eco": {
    name: "Moldova", code: "MDA", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 7.4,
    slices: [{ name: "Agriculture", pct: 7.4 }, { name: "Industry", pct: 16.9 }, { name: "Services", pct: 61.5 }, { name: "Taxes less subsidies", pct: 14.2 }],
  },
  "mongolia-eco": {
    name: "Mongolia", code: "MNG", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 5.9,
    slices: [{ name: "Agriculture", pct: 8.9 }, { name: "Industry", pct: 37.2 }, { name: "Services", pct: 44.4 }, { name: "Taxes less subsidies", pct: 9.5 }],
  },
  "montenegro-eco": {
    name: "Montenegro", code: "MNE", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 3.4 }, { name: "Industry", pct: 11.3 }, { name: "Services", pct: 63.3 }, { name: "Taxes less subsidies", pct: 22 }],
  },
  "morocco-eco": {
    name: "Morocco", code: "MAR", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 14.9,
    slices: [{ name: "Agriculture", pct: 10.5 }, { name: "Industry", pct: 25.2 }, { name: "Services", pct: 52.4 }, { name: "Taxes less subsidies", pct: 11.9 }],
  },
  "mozambique-eco": {
    name: "Mozambique", code: "MOZ", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 6.2,
    slices: [{ name: "Agriculture", pct: 25.6 }, { name: "Industry", pct: 22.1 }, { name: "Services", pct: 42 }, { name: "Taxes less subsidies", pct: 10.3 }],
  },
  "myanmar-eco": {
    name: "Myanmar", code: "MMR", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 25.1,
    slices: [{ name: "Agriculture", pct: 25.3 }, { name: "Industry", pct: 36.2 }, { name: "Services", pct: 38.5 }, { name: "Taxes less subsidies", pct: 0 }],
  },
  "namibia-eco": {
    name: "Namibia", code: "NAM", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 10,
    slices: [{ name: "Agriculture", pct: 7 }, { name: "Industry", pct: 28.9 }, { name: "Services", pct: 55 }, { name: "Taxes less subsidies", pct: 9.1 }],
  },
  "nauru-eco": {
    name: "Nauru", code: "NRU", year: "2024", basis: "valueAdded", source: "un",
    manufacturing: 19.6,
    slices: [{ name: "Agriculture", pct: 2.4 }, { name: "Industry", pct: 36.6 }, { name: "Services", pct: 61 }],
  },
  "nepal-eco": {
    name: "Nepal", code: "NPL", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 5,
    slices: [{ name: "Agriculture", pct: 21.6 }, { name: "Industry", pct: 12.1 }, { name: "Services", pct: 54.3 }, { name: "Taxes less subsidies", pct: 12 }],
  },
  "netherlands-eco": {
    name: "Netherlands", code: "NLD", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 10.1,
    slices: [{ name: "Agriculture", pct: 1.7 }, { name: "Industry", pct: 17.7 }, { name: "Services", pct: 70.4 }, { name: "Taxes less subsidies", pct: 10.2 }],
  },
  "newcaledonia-eco": {
    name: "New Caledonia", code: "NCL", year: "2019", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 1.8 }, { name: "Industry", pct: 22.3 }, { name: "Services", pct: 65.2 }, { name: "Taxes less subsidies", pct: 10.7 }],
  },
  "newzealand-eco": {
    name: "New Zealand", code: "NZL", year: "2023", basis: "gdp", source: "worldBank",
    manufacturing: 8.3,
    slices: [{ name: "Agriculture", pct: 4 }, { name: "Industry", pct: 19.4 }, { name: "Services", pct: 68.3 }, { name: "Taxes less subsidies", pct: 8.3 }],
  },
  "nicaragua-eco": {
    name: "Nicaragua", code: "NIC", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 12.6,
    slices: [{ name: "Agriculture", pct: 14.5 }, { name: "Industry", pct: 29.3 }, { name: "Services", pct: 45.1 }, { name: "Taxes less subsidies", pct: 11.1 }],
  },
  "niger-eco": {
    name: "Niger", code: "NER", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 47.6 }, { name: "Industry", pct: 18.7 }, { name: "Services", pct: 31.1 }, { name: "Taxes less subsidies", pct: 2.6 }],
  },
  "nigeria-eco": {
    name: "Nigeria", code: "NGA", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 8.3,
    slices: [{ name: "Agriculture", pct: 23 }, { name: "Industry", pct: 16.4 }, { name: "Services", pct: 58.3 }, { name: "Taxes less subsidies", pct: 2.3 }],
  },
  "northmacedonia-eco": {
    name: "North Macedonia", code: "MKD", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 14.3,
    slices: [{ name: "Agriculture", pct: 6 }, { name: "Industry", pct: 24.1 }, { name: "Services", pct: 56.9 }, { name: "Taxes less subsidies", pct: 13 }],
  },
  "norway-eco": {
    name: "Norway", code: "NOR", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 6.1,
    slices: [{ name: "Agriculture", pct: 1.6 }, { name: "Industry", pct: 34.5 }, { name: "Services", pct: 55 }, { name: "Taxes less subsidies", pct: 8.9 }],
  },
  "oman-eco": {
    name: "Oman", code: "OMN", year: "2025", basis: "valueAdded", source: "worldBank",
    manufacturing: 9.4,
    slices: [{ name: "Agriculture", pct: 2.7 }, { name: "Industry", pct: 51.4 }, { name: "Services", pct: 45.9 }],
  },
  "pakistan-eco": {
    name: "Pakistan", code: "PAK", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 13,
    slices: [{ name: "Agriculture", pct: 23 }, { name: "Industry", pct: 20.1 }, { name: "Services", pct: 50.9 }, { name: "Taxes less subsidies", pct: 6 }],
  },
  "palau-eco": {
    name: "Palau", code: "PLW", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 1.2,
    slices: [{ name: "Agriculture", pct: 2.7 }, { name: "Industry", pct: 13 }, { name: "Services", pct: 73.1 }, { name: "Taxes less subsidies", pct: 11.2 }],
  },
  "palestine-eco": {
    name: "Palestine", code: "PSE", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 11.3,
    slices: [{ name: "Agriculture", pct: 5.5 }, { name: "Industry", pct: 16.3 }, { name: "Services", pct: 60.2 }, { name: "Taxes less subsidies", pct: 18 }],
  },
  "panama-eco": {
    name: "Panama", code: "PAN", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 4.8,
    slices: [{ name: "Agriculture", pct: 2.6 }, { name: "Industry", pct: 24.9 }, { name: "Services", pct: 70 }, { name: "Taxes less subsidies", pct: 2.5 }],
  },
  "papuanewguinea-eco": {
    name: "Papua New Guinea", code: "PNG", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 1.6,
    slices: [{ name: "Agriculture", pct: 17 }, { name: "Industry", pct: 36.5 }, { name: "Services", pct: 42 }, { name: "Taxes less subsidies", pct: 4.5 }],
  },
  "paraguay-eco": {
    name: "Paraguay", code: "PRY", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 19.4,
    slices: [{ name: "Agriculture", pct: 11.6 }, { name: "Industry", pct: 32.3 }, { name: "Services", pct: 48.1 }, { name: "Taxes less subsidies", pct: 8 }],
  },
  "peru-eco": {
    name: "Peru", code: "PER", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 12.2,
    slices: [{ name: "Agriculture", pct: 7.5 }, { name: "Industry", pct: 34.3 }, { name: "Services", pct: 50.9 }, { name: "Taxes less subsidies", pct: 7.3 }],
  },
  "philippines-eco": {
    name: "Philippines", code: "PHL", year: "2025", basis: "valueAdded", source: "worldBank",
    manufacturing: 15.3,
    slices: [{ name: "Agriculture", pct: 8.6 }, { name: "Industry", pct: 27 }, { name: "Services", pct: 64.4 }],
  },
  "poland-eco": {
    name: "Poland", code: "POL", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 15,
    slices: [{ name: "Agriculture", pct: 2.5 }, { name: "Industry", pct: 25.8 }, { name: "Services", pct: 59.7 }, { name: "Taxes less subsidies", pct: 12 }],
  },
  "portugal-eco": {
    name: "Portugal", code: "PRT", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 11.3,
    slices: [{ name: "Agriculture", pct: 2 }, { name: "Industry", pct: 18.3 }, { name: "Services", pct: 66.5 }, { name: "Taxes less subsidies", pct: 13.2 }],
  },
  "puertorico-eco": {
    name: "Puerto Rico", code: "PRI", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 44,
    slices: [{ name: "Agriculture", pct: 0.7 }, { name: "Industry", pct: 47 }, { name: "Services", pct: 51.9 }, { name: "Taxes less subsidies", pct: 0.4 }],
  },
  "qatar-eco": {
    name: "Qatar", code: "QAT", year: "2025", basis: "valueAdded", source: "worldBank",
    manufacturing: 7.9,
    slices: [{ name: "Agriculture", pct: 0.3 }, { name: "Industry", pct: 54.7 }, { name: "Services", pct: 45 }],
  },
  "republicofthecongo-eco": {
    name: "Republic of the Congo", code: "COG", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 10.1 }, { name: "Industry", pct: 35.6 }, { name: "Services", pct: 54.3 }, { name: "Taxes less subsidies", pct: 0 }],
  },
  "romania-eco": {
    name: "Romania", code: "ROU", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 11.8,
    slices: [{ name: "Agriculture", pct: 3 }, { name: "Industry", pct: 25.3 }, { name: "Services", pct: 61.8 }, { name: "Taxes less subsidies", pct: 9.9 }],
  },
  "russia-eco": {
    name: "Russia", code: "RUS", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 13.7,
    slices: [{ name: "Agriculture", pct: 3.1 }, { name: "Industry", pct: 29.7 }, { name: "Services", pct: 58.8 }, { name: "Taxes less subsidies", pct: 8.4 }],
  },
  "rwanda-eco": {
    name: "Rwanda", code: "RWA", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 8.3,
    slices: [{ name: "Agriculture", pct: 20.3 }, { name: "Industry", pct: 22 }, { name: "Services", pct: 52.4 }, { name: "Taxes less subsidies", pct: 5.3 }],
  },
  "saintkittsnevis-eco": {
    name: "Saint Kitts & Nevis", code: "KNA", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 4,
    slices: [{ name: "Agriculture", pct: 1.3 }, { name: "Industry", pct: 20.8 }, { name: "Services", pct: 66.2 }, { name: "Taxes less subsidies", pct: 11.7 }],
  },
  "saintlucia-eco": {
    name: "Saint Lucia", code: "LCA", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 3.6,
    slices: [{ name: "Agriculture", pct: 1.7 }, { name: "Industry", pct: 10.7 }, { name: "Services", pct: 73.8 }, { name: "Taxes less subsidies", pct: 13.8 }],
  },
  "saintvincentthegrenadines-eco": {
    name: "Saint Vincent & the Grenadines", code: "VCT", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 3.9,
    slices: [{ name: "Agriculture", pct: 3.4 }, { name: "Industry", pct: 15.1 }, { name: "Services", pct: 66.4 }, { name: "Taxes less subsidies", pct: 15.1 }],
  },
  "samoa-eco": {
    name: "Samoa", code: "WSM", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 4.9,
    slices: [{ name: "Agriculture", pct: 9.1 }, { name: "Industry", pct: 10.2 }, { name: "Services", pct: 72 }, { name: "Taxes less subsidies", pct: 8.7 }],
  },
  "sanmarino-eco": {
    name: "San Marino", code: "SMR", year: "2023", basis: "gdp", source: "worldBank",
    manufacturing: 31.8,
    slices: [{ name: "Agriculture", pct: 0 }, { name: "Industry", pct: 35.8 }, { name: "Services", pct: 56.9 }, { name: "Taxes less subsidies", pct: 7.3 }],
  },
  "saotomeprincipe-eco": {
    name: "São Tomé & Príncipe", code: "STP", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 0.6,
    slices: [{ name: "Agriculture", pct: 12.2 }, { name: "Industry", pct: 2.2 }, { name: "Services", pct: 81.4 }, { name: "Taxes less subsidies", pct: 4.2 }],
  },
  "saudiarabia-eco": {
    name: "Saudi Arabia", code: "SAU", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 15.8,
    slices: [{ name: "Agriculture", pct: 2.6 }, { name: "Industry", pct: 43 }, { name: "Services", pct: 48.9 }, { name: "Taxes less subsidies", pct: 5.5 }],
  },
  "senegal-eco": {
    name: "Senegal", code: "SEN", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 13.2,
    slices: [{ name: "Agriculture", pct: 17.1 }, { name: "Industry", pct: 26.1 }, { name: "Services", pct: 46.4 }, { name: "Taxes less subsidies", pct: 10.4 }],
  },
  "serbia-eco": {
    name: "Serbia", code: "SRB", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 3.3 }, { name: "Industry", pct: 22.3 }, { name: "Services", pct: 59.7 }, { name: "Taxes less subsidies", pct: 14.7 }],
  },
  "seychelles-eco": {
    name: "Seychelles", code: "SYC", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 5.4,
    slices: [{ name: "Agriculture", pct: 2.6 }, { name: "Industry", pct: 14.3 }, { name: "Services", pct: 68 }, { name: "Taxes less subsidies", pct: 15.1 }],
  },
  "sierraleone-eco": {
    name: "Sierra Leone", code: "SLE", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 29.5 }, { name: "Industry", pct: 25.7 }, { name: "Services", pct: 41.6 }, { name: "Taxes less subsidies", pct: 3.2 }],
  },
  "singapore-eco": {
    name: "Singapore", code: "SGP", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 17.4,
    slices: [{ name: "Agriculture", pct: 0 }, { name: "Industry", pct: 22.7 }, { name: "Services", pct: 71.6 }, { name: "Taxes less subsidies", pct: 5.7 }],
  },
  "slovakia-eco": {
    name: "Slovakia", code: "SVK", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 16.2,
    slices: [{ name: "Agriculture", pct: 1.6 }, { name: "Industry", pct: 28.1 }, { name: "Services", pct: 59.8 }, { name: "Taxes less subsidies", pct: 10.5 }],
  },
  "slovenia-eco": {
    name: "Slovenia", code: "SVN", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 18.6,
    slices: [{ name: "Agriculture", pct: 1.6 }, { name: "Industry", pct: 28.3 }, { name: "Services", pct: 58.7 }, { name: "Taxes less subsidies", pct: 11.4 }],
  },
  "solomonislands-eco": {
    name: "Solomon Islands", code: "SLB", year: "2024", basis: "valueAdded", source: "worldBank",
    manufacturing: 10.1,
    slices: [{ name: "Agriculture", pct: 29.7 }, { name: "Industry", pct: 23.4 }, { name: "Services", pct: 46.9 }],
  },
  "somalia-eco": {
    name: "Somalia", code: "SOM", year: "2024", basis: "valueAdded", source: "un",
    manufacturing: 2.5,
    slices: [{ name: "Agriculture", pct: 60.1 }, { name: "Industry", pct: 7.4 }, { name: "Services", pct: 32.5 }],
  },
  "southafrica-eco": {
    name: "South Africa", code: "ZAF", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 12.3,
    slices: [{ name: "Agriculture", pct: 2.8 }, { name: "Industry", pct: 24.1 }, { name: "Services", pct: 63.1 }, { name: "Taxes less subsidies", pct: 10 }],
  },
  "southkorea-eco": {
    name: "South Korea", code: "KOR", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 27.4,
    slices: [{ name: "Agriculture", pct: 1.5 }, { name: "Industry", pct: 34.3 }, { name: "Services", pct: 57.2 }, { name: "Taxes less subsidies", pct: 7 }],
  },
  "southsudan-eco": {
    name: "South Sudan", code: "SSD", year: "2015", basis: "valueAdded", source: "worldBank",
    manufacturing: 3.5,
    slices: [{ name: "Agriculture", pct: 10.4 }, { name: "Industry", pct: 33.1 }, { name: "Services", pct: 56.5 }],
  },
  "spain-eco": {
    name: "Spain", code: "ESP", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 10.6,
    slices: [{ name: "Agriculture", pct: 2.7 }, { name: "Industry", pct: 19.6 }, { name: "Services", pct: 68.3 }, { name: "Taxes less subsidies", pct: 9.4 }],
  },
  "srilanka-eco": {
    name: "Sri Lanka", code: "LKA", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 17.1,
    slices: [{ name: "Agriculture", pct: 8.4 }, { name: "Industry", pct: 25.4 }, { name: "Services", pct: 54.6 }, { name: "Taxes less subsidies", pct: 11.6 }],
  },
  "sudan-eco": {
    name: "Sudan", code: "SDN", year: "2025", basis: "valueAdded", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 29.4 }, { name: "Industry", pct: 33.6 }, { name: "Services", pct: 37 }],
  },
  "suriname-eco": {
    name: "Suriname", code: "SUR", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 19.8,
    slices: [{ name: "Agriculture", pct: 6.8 }, { name: "Industry", pct: 35.1 }, { name: "Services", pct: 50.8 }, { name: "Taxes less subsidies", pct: 7.3 }],
  },
  "sweden-eco": {
    name: "Sweden", code: "SWE", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 12.5,
    slices: [{ name: "Agriculture", pct: 1.5 }, { name: "Industry", pct: 21 }, { name: "Services", pct: 67.1 }, { name: "Taxes less subsidies", pct: 10.4 }],
  },
  "switzerland-eco": {
    name: "Switzerland", code: "CHE", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 18.9,
    slices: [{ name: "Agriculture", pct: 0.6 }, { name: "Industry", pct: 25 }, { name: "Services", pct: 71.8 }, { name: "Taxes less subsidies", pct: 2.6 }],
  },
  "syria-eco": {
    name: "Syria", code: "SYR", year: "2022", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 42.9 }, { name: "Industry", pct: 11.9 }, { name: "Services", pct: 44.7 }, { name: "Taxes less subsidies", pct: 0.5 }],
  },
  "taiwan-eco": {
    name: "Taiwan", code: "TWN", year: "2024", basis: "gdp", source: "dgbas",
    manufacturing: 35.6,
    topSubSector: { name: "Electronic Parts and Components", pct: 17.2 },
    slices: [{ name: "Agriculture", pct: 1.5 }, { name: "Industry", pct: 40.3 }, { name: "Services", pct: 57.9 }, { name: "Statistical discrepancy", pct: 0.3 }],
  },
  "tajikistan-eco": {
    name: "Tajikistan", code: "TJK", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 13.2,
    slices: [{ name: "Agriculture", pct: 23.1 }, { name: "Industry", pct: 32.4 }, { name: "Services", pct: 36.5 }, { name: "Taxes less subsidies", pct: 8 }],
  },
  "tanzania-eco": {
    name: "Tanzania", code: "TZA", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 22.9 }, { name: "Industry", pct: 29.8 }, { name: "Services", pct: 28.8 }, { name: "Taxes less subsidies", pct: 18.5 }],
  },
  "thailand-eco": {
    name: "Thailand", code: "THA", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 23.7,
    slices: [{ name: "Agriculture", pct: 8.7 }, { name: "Industry", pct: 31.1 }, { name: "Services", pct: 60.2 }, { name: "Taxes less subsidies", pct: 0 }],
  },
  "timorleste-eco": {
    name: "Timor-Leste", code: "TLS", year: "2024", basis: "valueAdded", source: "worldBank",
    manufacturing: 1.9,
    slices: [{ name: "Agriculture", pct: 19.5 }, { name: "Industry", pct: 11.4 }, { name: "Services", pct: 69.1 }],
  },
  "togo-eco": {
    name: "Togo", code: "TGO", year: "2025", basis: "valueAdded", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 19.7 }, { name: "Industry", pct: 20.4 }, { name: "Services", pct: 59.9 }],
  },
  "tonga-eco": {
    name: "Tonga", code: "TON", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 5.5,
    slices: [{ name: "Agriculture", pct: 18.6 }, { name: "Industry", pct: 17.7 }, { name: "Services", pct: 49.5 }, { name: "Taxes less subsidies", pct: 14.2 }],
  },
  "trinidadtobago-eco": {
    name: "Trinidad & Tobago", code: "TTO", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 14.4,
    slices: [{ name: "Agriculture", pct: 0.8 }, { name: "Industry", pct: 34.6 }, { name: "Services", pct: 59.2 }, { name: "Taxes less subsidies", pct: 5.4 }],
  },
  "tunisia-eco": {
    name: "Tunisia", code: "TUN", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 10.3 }, { name: "Industry", pct: 22 }, { name: "Services", pct: 62.6 }, { name: "Taxes less subsidies", pct: 5.1 }],
  },
  "turkey-eco": {
    name: "Turkey", code: "TUR", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 5.2 }, { name: "Industry", pct: 24 }, { name: "Services", pct: 59.5 }, { name: "Taxes less subsidies", pct: 11.3 }],
  },
  "turkmenistan-eco": {
    name: "Turkmenistan", code: "TKM", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 12.4 }, { name: "Industry", pct: 36 }, { name: "Services", pct: 48.8 }, { name: "Taxes less subsidies", pct: 2.8 }],
  },
  "turksandcaicosislands-eco": {
    name: "Turks and Caicos Islands", code: "TCA", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 0.4,
    slices: [{ name: "Agriculture", pct: 0.4 }, { name: "Industry", pct: 9.3 }, { name: "Services", pct: 72.6 }, { name: "Taxes less subsidies", pct: 17.7 }],
  },
  "tuvalu-eco": {
    name: "Tuvalu", code: "TUV", year: "2024", basis: "valueAdded", source: "un",
    manufacturing: 1.7,
    slices: [{ name: "Agriculture", pct: 8.2 }, { name: "Industry", pct: 9.5 }, { name: "Services", pct: 82.3 }],
  },
  "uganda-eco": {
    name: "Uganda", code: "UGA", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 14.5,
    slices: [{ name: "Agriculture", pct: 26.1 }, { name: "Industry", pct: 24.3 }, { name: "Services", pct: 42.1 }, { name: "Taxes less subsidies", pct: 7.5 }],
  },
  "ukraine-eco": {
    name: "Ukraine", code: "UKR", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 8.3,
    slices: [{ name: "Agriculture", pct: 7.6 }, { name: "Industry", pct: 17.9 }, { name: "Services", pct: 60.9 }, { name: "Taxes less subsidies", pct: 13.6 }],
  },
  "uae-eco": {
    name: "United Arab Emirates", code: "ARE", year: "2024", basis: "valueAdded", source: "worldBank",
    manufacturing: 9.4,
    slices: [{ name: "Agriculture", pct: 0.8 }, { name: "Industry", pct: 44.3 }, { name: "Services", pct: 54.9 }],
  },
  "uk-eco": {
    name: "United Kingdom", code: "GBR", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 7.7,
    slices: [{ name: "Agriculture", pct: 0.6 }, { name: "Industry", pct: 16.5 }, { name: "Services", pct: 73.1 }, { name: "Taxes less subsidies", pct: 9.8 }],
  },
  "usa-eco": {
    name: "United States", code: "USA", year: "2021", basis: "gdp", source: "worldBank",
    manufacturing: 10.5,
    slices: [{ name: "Agriculture", pct: 0.9 }, { name: "Industry", pct: 17.6 }, { name: "Services", pct: 76.3 }, { name: "Taxes less subsidies", pct: 5.2 }],
  },
  "uruguay-eco": {
    name: "Uruguay", code: "URY", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 10,
    slices: [{ name: "Agriculture", pct: 6.4 }, { name: "Industry", pct: 16.9 }, { name: "Services", pct: 65.1 }, { name: "Taxes less subsidies", pct: 11.6 }],
  },
  "uzbekistan-eco": {
    name: "Uzbekistan", code: "UZB", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 20.8,
    slices: [{ name: "Agriculture", pct: 16.6 }, { name: "Industry", pct: 32.5 }, { name: "Services", pct: 46.5 }, { name: "Taxes less subsidies", pct: 4.4 }],
  },
  "vanuatu-eco": {
    name: "Vanuatu", code: "VUT", year: "2024", basis: "gdp", source: "worldBank",
    manufacturing: 4,
    slices: [{ name: "Agriculture", pct: 26.6 }, { name: "Industry", pct: 10.1 }, { name: "Services", pct: 56.8 }, { name: "Taxes less subsidies", pct: 6.5 }],
  },
  "venezuela-eco": {
    name: "Venezuela", code: "VEN", year: "2024", basis: "valueAdded", source: "un",
    manufacturing: 16.9,
    slices: [{ name: "Agriculture", pct: 4.5 }, { name: "Industry", pct: 52.2 }, { name: "Services", pct: 43.3 }],
  },
  "vietnam-eco": {
    name: "Vietnam", code: "VNM", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 24.5,
    slices: [{ name: "Agriculture", pct: 11.6 }, { name: "Industry", pct: 37.6 }, { name: "Services", pct: 42.8 }, { name: "Taxes less subsidies", pct: 8 }],
  },
  "yemen-eco": {
    name: "Yemen", code: "YEM", year: "2018", basis: "gdp", source: "worldBank",
    manufacturing: null,
    slices: [{ name: "Agriculture", pct: 28.7 }, { name: "Industry", pct: 25.4 }, { name: "Services", pct: 41.9 }, { name: "Taxes less subsidies", pct: 4 }],
  },
  "zambia-eco": {
    name: "Zambia", code: "ZMB", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 8.7,
    slices: [{ name: "Agriculture", pct: 4.1 }, { name: "Industry", pct: 35.3 }, { name: "Services", pct: 57.1 }, { name: "Taxes less subsidies", pct: 3.5 }],
  },
  "zimbabwe-eco": {
    name: "Zimbabwe", code: "ZWE", year: "2025", basis: "gdp", source: "worldBank",
    manufacturing: 14.9,
    slices: [{ name: "Agriculture", pct: 9.5 }, { name: "Industry", pct: 37.1 }, { name: "Services", pct: 48.1 }, { name: "Taxes less subsidies", pct: 5.3 }],
  },
};
