/**
 * Headline figures per economy, each with the year it is for.
 *
 * GENERATED by build-economy-indicators.cjs on 2026-09-15 — do not edit by hand;
 * change the script and re-run it.
 *
 * GDP, GDP per capita, growth, inflation and unemployment are the World Bank's
 * most recent year for that economy. Debt is the IMF's general government
 * gross debt as a share of GDP, which is the measure that series reports.
 * The current year and later are skipped because the WEO publishes projections
 * for them; even the latest year kept may still be an IMF estimate rather than
 * a final outturn, which is why the year is shown with the figure.
 *
 * Note that the IMF's general government measure is wider than a
 * central-government one, so some economies move a long way - Switzerland from
 * 18 to 38.5 - because the measure changed, not the country.
 *
 * Keyed by the economy id used in economiesData.ts. An economy neither body
 * covers has no entry and keeps the figure it had.
 */
export const ECONOMY_INDICATORS_SOURCE = {
  worldBank: { label: "World Bank — World Development Indicators", url: "https://data.worldbank.org/" },
  imf: { label: "IMF — World Economic Outlook, general government gross debt", url: "https://www.imf.org/external/datamapper/GGXWDG_NGDP" },
  retrieved: "2026-09-15",
};

/** A figure and the year it is for. */
export type MeasuredEconomy = { v: number; y: string };

export type EconomyIndicators = Partial<{
  gdpTrillions: MeasuredEconomy;
  gdpPerCapita: MeasuredEconomy;
  gdpGrowthRate: MeasuredEconomy;
  inflationRate: MeasuredEconomy;
  unemploymentRate: MeasuredEconomy;
  debtToGDPRatio: MeasuredEconomy;
}>;

export const ECONOMY_INDICATORS: Record<string, EconomyIndicators> = {
  "usa-eco": { gdpTrillions: { v: 30.77, y: "2025" }, gdpPerCapita: { v: 90027, y: "2025" }, gdpGrowthRate: { v: 2.2, y: "2025" }, inflationRate: { v: 2.9, y: "2024" }, unemploymentRate: { v: 4.2, y: "2025" }, debtToGDPRatio: { v: 123.9, y: "2025" } },
  "china-eco": { gdpTrillions: { v: 19.498, y: "2025" }, gdpPerCapita: { v: 13862, y: "2025" }, gdpGrowthRate: { v: 5, y: "2025" }, inflationRate: { v: 0.1, y: "2025" }, unemploymentRate: { v: 4.6, y: "2025" }, debtToGDPRatio: { v: 99.2, y: "2025" } },
  "eu-eco": { gdpTrillions: { v: 21.243, y: "2025" }, gdpPerCapita: { v: 47089, y: "2025" }, gdpGrowthRate: { v: 1.5, y: "2025" }, inflationRate: { v: 2.5, y: "2025" }, unemploymentRate: { v: 5.9, y: "2025" } },
  "japan-eco": { gdpTrillions: { v: 4.435, y: "2025" }, gdpPerCapita: { v: 35951, y: "2025" }, gdpGrowthRate: { v: 1.2, y: "2025" }, inflationRate: { v: 3.2, y: "2025" }, unemploymentRate: { v: 2.5, y: "2025" }, debtToGDPRatio: { v: 206.5, y: "2025" } },
  "india-eco": { gdpTrillions: { v: 3.956, y: "2025" }, gdpPerCapita: { v: 2702, y: "2025" }, gdpGrowthRate: { v: 7.6, y: "2025" }, inflationRate: { v: 2.4, y: "2025" }, unemploymentRate: { v: 4.2, y: "2025" }, debtToGDPRatio: { v: 84.1, y: "2025" } },
  "uk-eco": { gdpTrillions: { v: 4.003, y: "2025" }, gdpPerCapita: { v: 57602, y: "2025" }, gdpGrowthRate: { v: 1.4, y: "2025" }, inflationRate: { v: 3.9, y: "2025" }, unemploymentRate: { v: 4.7, y: "2025" }, debtToGDPRatio: { v: 102.3, y: "2025" } },
  "germany-eco": { gdpTrillions: { v: 5.051, y: "2025" }, gdpPerCapita: { v: 60496, y: "2025" }, gdpGrowthRate: { v: 0.2, y: "2025" }, inflationRate: { v: 2.2, y: "2025" }, unemploymentRate: { v: 3.7, y: "2025" }, debtToGDPRatio: { v: 62.9, y: "2025" } },
  "france-eco": { gdpTrillions: { v: 3.366, y: "2025" }, gdpPerCapita: { v: 48986, y: "2025" }, gdpGrowthRate: { v: 0.8, y: "2025" }, inflationRate: { v: 0.9, y: "2025" }, unemploymentRate: { v: 7.5, y: "2025" }, debtToGDPRatio: { v: 116, y: "2025" } },
  "brazil-eco": { gdpTrillions: { v: 2.28, y: "2025" }, gdpPerCapita: { v: 10713, y: "2025" }, gdpGrowthRate: { v: 2.3, y: "2025" }, inflationRate: { v: 5, y: "2025" }, unemploymentRate: { v: 6, y: "2025" }, debtToGDPRatio: { v: 93.3, y: "2025" } },
  "canada-eco": { gdpTrillions: { v: 2.32, y: "2025" }, gdpPerCapita: { v: 55698, y: "2025" }, gdpGrowthRate: { v: 1.7, y: "2025" }, inflationRate: { v: 2.1, y: "2025" }, unemploymentRate: { v: 6.9, y: "2025" }, debtToGDPRatio: { v: 113.5, y: "2025" } },
  "southkorea-eco": { gdpTrillions: { v: 1.872, y: "2025" }, gdpPerCapita: { v: 36227, y: "2025" }, gdpGrowthRate: { v: 1, y: "2025" }, inflationRate: { v: 2.1, y: "2025" }, unemploymentRate: { v: 2.7, y: "2025" }, debtToGDPRatio: { v: 52.3, y: "2025" } },
  "australia-eco": { gdpTrillions: { v: 1.799, y: "2025" }, gdpPerCapita: { v: 65130, y: "2025" }, gdpGrowthRate: { v: 1.4, y: "2025" }, inflationRate: { v: 2.9, y: "2025" }, unemploymentRate: { v: 4.1, y: "2025" }, debtToGDPRatio: { v: 51, y: "2025" } },
  "russia-eco": { gdpTrillions: { v: 2.561, y: "2025" }, gdpPerCapita: { v: 17547, y: "2025" }, gdpGrowthRate: { v: 1, y: "2025" }, inflationRate: { v: 8.7, y: "2025" }, unemploymentRate: { v: 2.1, y: "2025" }, debtToGDPRatio: { v: 17.2, y: "2025" } },
  "mexico-eco": { gdpTrillions: { v: 1.833, y: "2025" }, gdpPerCapita: { v: 13889, y: "2025" }, gdpGrowthRate: { v: 0.6, y: "2025" }, inflationRate: { v: 3.8, y: "2025" }, unemploymentRate: { v: 2.7, y: "2025" }, debtToGDPRatio: { v: 61.8, y: "2025" } },
  "indonesia-eco": { gdpTrillions: { v: 1.446, y: "2025" }, gdpPerCapita: { v: 5060, y: "2025" }, gdpGrowthRate: { v: 5.1, y: "2025" }, inflationRate: { v: 1.9, y: "2025" }, unemploymentRate: { v: 3.2, y: "2025" }, debtToGDPRatio: { v: 41, y: "2025" } },
  "netherlands-eco": { gdpTrillions: { v: 1.333, y: "2025" }, gdpPerCapita: { v: 73684, y: "2025" }, gdpGrowthRate: { v: 1.8, y: "2025" }, inflationRate: { v: 3.3, y: "2025" }, unemploymentRate: { v: 3.9, y: "2025" }, debtToGDPRatio: { v: 43.3, y: "2025" } },
  "saudiarabia-eco": { gdpTrillions: { v: 1.277, y: "2025" }, gdpPerCapita: { v: 34537, y: "2025" }, gdpGrowthRate: { v: 4.5, y: "2025" }, inflationRate: { v: 2.1, y: "2025" }, unemploymentRate: { v: 3, y: "2025" }, debtToGDPRatio: { v: 31.7, y: "2025" } },
  "turkey-eco": { gdpTrillions: { v: 1.597, y: "2025" }, gdpPerCapita: { v: 18599, y: "2025" }, gdpGrowthRate: { v: 3.6, y: "2025" }, inflationRate: { v: 34.9, y: "2025" }, unemploymentRate: { v: 8.5, y: "2025" }, debtToGDPRatio: { v: 23.5, y: "2025" } },
  "spain-eco": { gdpTrillions: { v: 1.906, y: "2025" }, gdpPerCapita: { v: 38627, y: "2025" }, gdpGrowthRate: { v: 2.8, y: "2025" }, inflationRate: { v: 2.7, y: "2025" }, unemploymentRate: { v: 10.4, y: "2025" }, debtToGDPRatio: { v: 100.4, y: "2025" } },
  "switzerland-eco": { gdpTrillions: { v: 1.044, y: "2025" }, gdpPerCapita: { v: 114769, y: "2025" }, gdpGrowthRate: { v: 1.3, y: "2025" }, inflationRate: { v: 0.2, y: "2025" }, unemploymentRate: { v: 4.9, y: "2025" }, debtToGDPRatio: { v: 39.4, y: "2025" } },
  "argentina-eco": { gdpTrillions: { v: 0.683, y: "2025" }, gdpPerCapita: { v: 14898, y: "2025" }, gdpGrowthRate: { v: 4.4, y: "2025" }, inflationRate: { v: 219.9, y: "2024" }, unemploymentRate: { v: 7.1, y: "2025" }, debtToGDPRatio: { v: 80.3, y: "2025" } },
  "uae-eco": { gdpTrillions: { v: 0.552, y: "2024" }, gdpPerCapita: { v: 50274, y: "2024" }, gdpGrowthRate: { v: 4, y: "2024" }, inflationRate: { v: 1.3, y: "2025" }, unemploymentRate: { v: 2.2, y: "2025" }, debtToGDPRatio: { v: 34.3, y: "2025" } },
  "poland-eco": { gdpTrillions: { v: 1.035, y: "2025" }, gdpPerCapita: { v: 28420, y: "2025" }, gdpGrowthRate: { v: 3.6, y: "2025" }, inflationRate: { v: 3.8, y: "2025" }, unemploymentRate: { v: 3, y: "2025" }, debtToGDPRatio: { v: 58.8, y: "2025" } },
  "sweden-eco": { gdpTrillions: { v: 0.669, y: "2025" }, gdpPerCapita: { v: 63133, y: "2025" }, gdpGrowthRate: { v: 1.5, y: "2025" }, inflationRate: { v: 0.7, y: "2025" }, unemploymentRate: { v: 8.7, y: "2025" }, debtToGDPRatio: { v: 34.9, y: "2025" } },
  "belgium-eco": { gdpTrillions: { v: 0.725, y: "2025" }, gdpPerCapita: { v: 60750, y: "2025" }, gdpGrowthRate: { v: 1, y: "2025" }, inflationRate: { v: 2.5, y: "2025" }, unemploymentRate: { v: 5.9, y: "2025" }, debtToGDPRatio: { v: 106.3, y: "2025" } },
  "norway-eco": { gdpTrillions: { v: 0.531, y: "2025" }, gdpPerCapita: { v: 94594, y: "2025" }, gdpGrowthRate: { v: 1.1, y: "2025" }, inflationRate: { v: 3.1, y: "2025" }, unemploymentRate: { v: 4.6, y: "2025" }, debtToGDPRatio: { v: 45, y: "2025" } },
  "singapore-eco": { gdpTrillions: { v: 0.604, y: "2025" }, gdpPerCapita: { v: 98814, y: "2025" }, gdpGrowthRate: { v: 5, y: "2025" }, inflationRate: { v: 0.9, y: "2025" }, unemploymentRate: { v: 2.8, y: "2025" }, debtToGDPRatio: { v: 171.3, y: "2025" } },
  "malaysia-eco": { gdpTrillions: { v: 0.472, y: "2025" }, gdpPerCapita: { v: 13125, y: "2025" }, gdpGrowthRate: { v: 5.2, y: "2025" }, inflationRate: { v: 1.4, y: "2025" }, unemploymentRate: { v: 3.8, y: "2025" }, debtToGDPRatio: { v: 70.7, y: "2025" } },
  "israel-eco": { gdpTrillions: { v: 0.611, y: "2025" }, gdpPerCapita: { v: 60337, y: "2025" }, gdpGrowthRate: { v: 2.9, y: "2025" }, inflationRate: { v: 3, y: "2025" }, unemploymentRate: { v: 3.5, y: "2025" }, debtToGDPRatio: { v: 68.5, y: "2025" } },
  "colombia-eco": { gdpTrillions: { v: 0.457, y: "2025" }, gdpPerCapita: { v: 8562, y: "2025" }, gdpGrowthRate: { v: 2.6, y: "2025" }, inflationRate: { v: 5.1, y: "2025" }, unemploymentRate: { v: 8.3, y: "2025" }, debtToGDPRatio: { v: 59.9, y: "2025" } },
  "egypt-eco": { gdpTrillions: { v: 0.365, y: "2025" }, gdpPerCapita: { v: 3086, y: "2025" }, gdpGrowthRate: { v: 4.4, y: "2025" }, inflationRate: { v: 14.1, y: "2025" }, unemploymentRate: { v: 6.8, y: "2025" }, debtToGDPRatio: { v: 86.8, y: "2025" } },
  "southafrica-eco": { gdpTrillions: { v: 0.427, y: "2025" }, gdpPerCapita: { v: 6598, y: "2025" }, gdpGrowthRate: { v: 1.1, y: "2025" }, inflationRate: { v: 3.2, y: "2025" }, unemploymentRate: { v: 32.4, y: "2025" }, debtToGDPRatio: { v: 78.6, y: "2025" } },
  "thailand-eco": { gdpTrillions: { v: 0.577, y: "2025" }, gdpPerCapita: { v: 8057, y: "2025" }, gdpGrowthRate: { v: 2.4, y: "2025" }, inflationRate: { v: -0.1, y: "2025" }, unemploymentRate: { v: 0.8, y: "2025" }, debtToGDPRatio: { v: 64.7, y: "2025" } },
  "denmark-eco": { gdpTrillions: { v: 0.463, y: "2025" }, gdpPerCapita: { v: 76970, y: "2025" }, gdpGrowthRate: { v: 2.9, y: "2025" }, inflationRate: { v: 1.9, y: "2025" }, unemploymentRate: { v: 5.5, y: "2025" }, debtToGDPRatio: { v: 27.5, y: "2025" } },
  "nigeria-eco": { gdpTrillions: { v: 0.291, y: "2025" }, gdpPerCapita: { v: 1224, y: "2025" }, gdpGrowthRate: { v: 4, y: "2025" }, inflationRate: { v: 23, y: "2025" }, unemploymentRate: { v: 3.1, y: "2025" }, debtToGDPRatio: { v: 35.5, y: "2025" } },
  "pakistan-eco": { gdpTrillions: { v: 0.407, y: "2025" }, gdpPerCapita: { v: 1596, y: "2025" }, gdpGrowthRate: { v: 3.7, y: "2025" }, inflationRate: { v: 3.5, y: "2025" }, unemploymentRate: { v: 5.4, y: "2025" }, debtToGDPRatio: { v: 72.8, y: "2025" } },
  "vietnam-eco": { gdpTrillions: { v: 0.515, y: "2025" }, gdpPerCapita: { v: 5066, y: "2025" }, gdpGrowthRate: { v: 8, y: "2025" }, inflationRate: { v: 3.3, y: "2025" }, unemploymentRate: { v: 1.5, y: "2025" }, debtToGDPRatio: { v: 30.3, y: "2025" } },
  "chile-eco": { gdpTrillions: { v: 0.357, y: "2025" }, gdpPerCapita: { v: 17995, y: "2025" }, gdpGrowthRate: { v: 2.5, y: "2025" }, inflationRate: { v: 4.2, y: "2025" }, unemploymentRate: { v: 9, y: "2025" }, debtToGDPRatio: { v: 41.8, y: "2025" } },
  "philippines-eco": { gdpTrillions: { v: 0.487, y: "2025" }, gdpPerCapita: { v: 4171, y: "2025" }, gdpGrowthRate: { v: 4.4, y: "2025" }, inflationRate: { v: 1.7, y: "2025" }, unemploymentRate: { v: 2.2, y: "2025" }, debtToGDPRatio: { v: 59.4, y: "2025" } },
  "bangladesh-eco": { gdpTrillions: { v: 0.456, y: "2025" }, gdpPerCapita: { v: 2597, y: "2025" }, gdpGrowthRate: { v: 3.5, y: "2025" }, inflationRate: { v: 8.8, y: "2025" }, unemploymentRate: { v: 3.8, y: "2025" }, debtToGDPRatio: { v: 42, y: "2025" } },
  "austria-eco": { gdpTrillions: { v: 0.579, y: "2025" }, gdpPerCapita: { v: 62930, y: "2025" }, gdpGrowthRate: { v: 0.6, y: "2025" }, inflationRate: { v: 3.5, y: "2025" }, unemploymentRate: { v: 5.6, y: "2025" }, debtToGDPRatio: { v: 80.5, y: "2025" } },
  "iran-eco": { gdpTrillions: { v: 0.363, y: "2025" }, gdpPerCapita: { v: 3924, y: "2025" }, gdpGrowthRate: { v: -2.8, y: "2025" }, inflationRate: { v: 42.2, y: "2025" }, unemploymentRate: { v: 8.3, y: "2025" }, debtToGDPRatio: { v: 37.3, y: "2025" } },
  "iraq-eco": { gdpTrillions: { v: 0.254, y: "2025" }, gdpPerCapita: { v: 5410, y: "2025" }, gdpGrowthRate: { v: -2.2, y: "2025" }, inflationRate: { v: 0.3, y: "2025" }, unemploymentRate: { v: 15.5, y: "2025" }, debtToGDPRatio: { v: 53.9, y: "2025" } },
  "portugal-eco": { gdpTrillions: { v: 0.347, y: "2025" }, gdpPerCapita: { v: 32082, y: "2025" }, gdpGrowthRate: { v: 1.9, y: "2025" }, inflationRate: { v: 2.3, y: "2025" }, unemploymentRate: { v: 6.2, y: "2025" }, debtToGDPRatio: { v: 89.9, y: "2025" } },
  "czechia-eco": { gdpTrillions: { v: 0.391, y: "2025" }, gdpPerCapita: { v: 35917, y: "2025" }, gdpGrowthRate: { v: 2.6, y: "2025" }, inflationRate: { v: 2.5, y: "2025" }, unemploymentRate: { v: 2.8, y: "2025" }, debtToGDPRatio: { v: 44.6, y: "2025" } },
  "greece-eco": { gdpTrillions: { v: 0.281, y: "2025" }, gdpPerCapita: { v: 26948, y: "2025" }, gdpGrowthRate: { v: 2.1, y: "2025" }, inflationRate: { v: 2.5, y: "2025" }, unemploymentRate: { v: 8.5, y: "2025" }, debtToGDPRatio: { v: 145.7, y: "2025" } },
  "kuwait-eco": { gdpTrillions: { v: 0.157, y: "2025" }, gdpPerCapita: { v: 32312, y: "2025" }, gdpGrowthRate: { v: 2.7, y: "2025" }, inflationRate: { v: 2.4, y: "2025" }, unemploymentRate: { v: 2.2, y: "2025" }, debtToGDPRatio: { v: 14.6, y: "2025" } },
  "qatar-eco": { gdpTrillions: { v: 0.216, y: "2025" }, gdpPerCapita: { v: 72525, y: "2025" }, gdpGrowthRate: { v: 2.9, y: "2025" }, inflationRate: { v: 1.3, y: "2024" }, unemploymentRate: { v: 0.1, y: "2025" }, debtToGDPRatio: { v: 41.4, y: "2025" } },
  "ethiopia-eco": { gdpTrillions: { v: 0.126, y: "2025" }, gdpPerCapita: { v: 933, y: "2025" }, gdpGrowthRate: { v: 9.8, y: "2025" }, inflationRate: { v: 13.2, y: "2025" }, unemploymentRate: { v: 3.3, y: "2025" }, debtToGDPRatio: { v: 43.1, y: "2025" } },
  "kenya-eco": { gdpTrillions: { v: 0.136, y: "2025" }, gdpPerCapita: { v: 2363, y: "2025" }, gdpGrowthRate: { v: 4.6, y: "2025" }, inflationRate: { v: 4.1, y: "2025" }, unemploymentRate: { v: 5.4, y: "2025" }, debtToGDPRatio: { v: 69.3, y: "2025" } },
  "ghana-eco": { gdpTrillions: { v: 0.114, y: "2025" }, gdpPerCapita: { v: 3257, y: "2025" }, gdpGrowthRate: { v: 6, y: "2025" }, inflationRate: { v: 14.2, y: "2025" }, unemploymentRate: { v: 3, y: "2025" }, debtToGDPRatio: { v: 48.8, y: "2025" } },
  "tanzania-eco": { gdpTrillions: { v: 0.09, y: "2025" }, gdpPerCapita: { v: 1319, y: "2025" }, gdpGrowthRate: { v: 5.9, y: "2025" }, inflationRate: { v: 3.3, y: "2025" }, unemploymentRate: { v: 1.6, y: "2025" }, debtToGDPRatio: { v: 49.7, y: "2025" } },
  "angola-eco": { gdpTrillions: { v: 0.122, y: "2025" }, gdpPerCapita: { v: 3129, y: "2025" }, gdpGrowthRate: { v: 3.1, y: "2025" }, inflationRate: { v: 20.2, y: "2025" }, unemploymentRate: { v: 14.1, y: "2025" }, debtToGDPRatio: { v: 51.3, y: "2025" } },
  "morocco-eco": { gdpTrillions: { v: 0.182, y: "2025" }, gdpPerCapita: { v: 4672, y: "2025" }, gdpGrowthRate: { v: 4.6, y: "2025" }, inflationRate: { v: 0.7, y: "2025" }, unemploymentRate: { v: 9, y: "2025" }, debtToGDPRatio: { v: 67.1, y: "2025" } },
  "mozambique-eco": { gdpTrillions: { v: 0.022, y: "2025" }, gdpPerCapita: { v: 627, y: "2025" }, gdpGrowthRate: { v: -0.5, y: "2025" }, inflationRate: { v: 4.4, y: "2025" }, unemploymentRate: { v: 6.6, y: "2025" }, debtToGDPRatio: { v: 102.5, y: "2025" } },
  "peru-eco": { gdpTrillions: { v: 0.335, y: "2025" }, gdpPerCapita: { v: 9684, y: "2025" }, gdpGrowthRate: { v: 3.4, y: "2025" }, inflationRate: { v: 1.5, y: "2025" }, unemploymentRate: { v: 5.1, y: "2025" }, debtToGDPRatio: { v: 30.2, y: "2025" } },
  "venezuela-eco": { gdpTrillions: { v: 0.1, y: "2025" }, gdpPerCapita: { v: 3495, y: "2025" }, gdpGrowthRate: { v: 1.6, y: "2025" }, unemploymentRate: { v: 5.3, y: "2025" }, debtToGDPRatio: { v: 308.7, y: "2025" } },
  "ecuador-eco": { gdpTrillions: { v: 0.13, y: "2025" }, gdpPerCapita: { v: 7125, y: "2025" }, gdpGrowthRate: { v: 3.7, y: "2025" }, inflationRate: { v: 0.7, y: "2025" }, unemploymentRate: { v: 3.3, y: "2025" }, debtToGDPRatio: { v: 54.4, y: "2025" } },
  "myanmar-eco": { gdpTrillions: { v: 0.082, y: "2025" }, gdpPerCapita: { v: 1489, y: "2025" }, gdpGrowthRate: { v: -2, y: "2025" }, inflationRate: { v: 8.8, y: "2019" }, unemploymentRate: { v: 3, y: "2025" }, debtToGDPRatio: { v: 51.9, y: "2025" } },
  "cambodia-eco": { gdpTrillions: { v: 0.051, y: "2025" }, gdpPerCapita: { v: 2872, y: "2025" }, gdpGrowthRate: { v: 5.3, y: "2025" }, inflationRate: { v: 2.4, y: "2025" }, unemploymentRate: { v: 0.3, y: "2025" }, debtToGDPRatio: { v: 26.5, y: "2025" } },
  "srilanka-eco": { gdpTrillions: { v: 0.109, y: "2025" }, gdpPerCapita: { v: 5002, y: "2025" }, gdpGrowthRate: { v: 5, y: "2025" }, inflationRate: { v: -4.8, y: "2025" }, unemploymentRate: { v: 4, y: "2025" }, debtToGDPRatio: { v: 100.8, y: "2024" } },
  "nepal-eco": { gdpTrillions: { v: 0.045, y: "2025" }, gdpPerCapita: { v: 1536, y: "2025" }, gdpGrowthRate: { v: 4.4, y: "2025" }, inflationRate: { v: 2.7, y: "2025" }, unemploymentRate: { v: 10.5, y: "2025" }, debtToGDPRatio: { v: 48.1, y: "2025" } },
  "newzealand-eco": { gdpTrillions: { v: 0.264, y: "2025" }, gdpPerCapita: { v: 49591, y: "2025" }, gdpGrowthRate: { v: 0.5, y: "2025" }, inflationRate: { v: 2.8, y: "2025" }, unemploymentRate: { v: 5.1, y: "2025" }, debtToGDPRatio: { v: 54.7, y: "2025" } },
  "finland-eco": { gdpTrillions: { v: 0.317, y: "2025" }, gdpPerCapita: { v: 56149, y: "2025" }, gdpGrowthRate: { v: 0.2, y: "2025" }, inflationRate: { v: 0.3, y: "2025" }, unemploymentRate: { v: 9.5, y: "2025" }, debtToGDPRatio: { v: 89.3, y: "2025" } },
  "romania-eco": { gdpTrillions: { v: 0.429, y: "2025" }, gdpPerCapita: { v: 22538, y: "2025" }, gdpGrowthRate: { v: 0.7, y: "2025" }, inflationRate: { v: 7.2, y: "2025" }, unemploymentRate: { v: 6, y: "2025" }, debtToGDPRatio: { v: 60.6, y: "2025" } },
  "hungary-eco": { gdpTrillions: { v: 0.246, y: "2025" }, gdpPerCapita: { v: 25907, y: "2025" }, gdpGrowthRate: { v: 0.5, y: "2025" }, inflationRate: { v: 4.4, y: "2025" }, unemploymentRate: { v: 4.5, y: "2025" }, debtToGDPRatio: { v: 75.2, y: "2025" } },
  "ukraine-eco": { gdpTrillions: { v: 0.214, y: "2025" }, gdpPerCapita: { v: 5866, y: "2025" }, gdpGrowthRate: { v: 1.8, y: "2025" }, inflationRate: { v: 12.7, y: "2025" }, unemploymentRate: { v: 9.8, y: "2021" }, debtToGDPRatio: { v: 108.7, y: "2025" } },
  "slovakia-eco": { gdpTrillions: { v: 0.155, y: "2025" }, gdpPerCapita: { v: 28544, y: "2025" }, gdpGrowthRate: { v: 0.8, y: "2025" }, inflationRate: { v: 4, y: "2025" }, unemploymentRate: { v: 5.4, y: "2025" }, debtToGDPRatio: { v: 61.6, y: "2025" } },
  "bulgaria-eco": { gdpTrillions: { v: 0.131, y: "2025" }, gdpPerCapita: { v: 20328, y: "2025" }, gdpGrowthRate: { v: 3.1, y: "2025" }, inflationRate: { v: 4.6, y: "2025" }, unemploymentRate: { v: 3.5, y: "2025" }, debtToGDPRatio: { v: 27.1, y: "2025" } },
  "croatia-eco": { gdpTrillions: { v: 0.105, y: "2025" }, gdpPerCapita: { v: 27104, y: "2025" }, gdpGrowthRate: { v: 3.4, y: "2025" }, inflationRate: { v: 3.7, y: "2025" }, unemploymentRate: { v: 5, y: "2025" }, debtToGDPRatio: { v: 55.9, y: "2025" } },
  "serbia-eco": { gdpTrillions: { v: 0.1, y: "2025" }, gdpPerCapita: { v: 15262, y: "2025" }, gdpGrowthRate: { v: 2, y: "2025" }, inflationRate: { v: 3.9, y: "2025" }, unemploymentRate: { v: 7.1, y: "2025" }, debtToGDPRatio: { v: 42.4, y: "2025" } },
  "ireland-eco": { gdpTrillions: { v: 0.722, y: "2025" }, gdpPerCapita: { v: 131592, y: "2025" }, gdpGrowthRate: { v: 12.3, y: "2025" }, inflationRate: { v: 2.2, y: "2025" }, unemploymentRate: { v: 4.6, y: "2025" }, debtToGDPRatio: { v: 32.9, y: "2025" } },
  "italy-eco": { gdpTrillions: { v: 2.552, y: "2025" }, gdpPerCapita: { v: 43309, y: "2025" }, gdpGrowthRate: { v: 0.5, y: "2025" }, inflationRate: { v: 1.5, y: "2025" }, unemploymentRate: { v: 6.4, y: "2025" }, debtToGDPRatio: { v: 137.1, y: "2025" } },
  "hongkong-eco": { gdpTrillions: { v: 0.427, y: "2025" }, gdpPerCapita: { v: 56983, y: "2025" }, gdpGrowthRate: { v: 3.5, y: "2025" }, inflationRate: { v: 1.4, y: "2025" }, unemploymentRate: { v: 2.8, y: "2025" }, debtToGDPRatio: { v: 11.9, y: "2025" } },
  "uzbekistan-eco": { gdpTrillions: { v: 0.147, y: "2025" }, gdpPerCapita: { v: 3968, y: "2025" }, gdpGrowthRate: { v: 7.7, y: "2025" }, inflationRate: { v: 8.8, y: "2025" }, unemploymentRate: { v: 4.6, y: "2025" }, debtToGDPRatio: { v: 28.6, y: "2025" } },
  "kazakhstan-eco": { gdpTrillions: { v: 0.306, y: "2025" }, gdpPerCapita: { v: 14692, y: "2025" }, gdpGrowthRate: { v: 6.5, y: "2025" }, inflationRate: { v: 11.4, y: "2025" }, unemploymentRate: { v: 4.8, y: "2025" }, debtToGDPRatio: { v: 24.6, y: "2025" } },
};
