/**
 * Producing and reserve-holding countries for the fossil-fuel cards.
 *
 * GENERATED by build-energy-producers.cjs on 2026-09-21 — do not edit by
 * hand; change the script and re-run it. See that script for the sources.
 */
import type { ResourceProducers } from "./resourceProducerTypes";

export const ENERGY_PRODUCERS: Record<string, ResourceProducers> = {
  "Crude Oil": {
    "measure": "Crude oil production including lease condensate (EIA); proven reserves at year-end (OPEC)",
    "productionYear": "2025",
    "reservesYear": "2025",
    "productionUnit": "kb/d",
    "reservesUnit": "mb",
    "worldProduction": {
      "value": 84383.37418562062,
      "lowerBound": false
    },
    "worldReserves": {
      "value": 1572459,
      "lowerBound": false
    },
    "countries": [
      {
        "name": "United States",
        "production": {
          "value": 13586.086904109588,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 16.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 41909,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.7,
          "bound": "exact"
        }
      },
      {
        "name": "Russia",
        "production": {
          "value": 9885.10903296257,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 11.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 80000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 5.1,
          "bound": "exact"
        }
      },
      {
        "name": "Saudi Arabia",
        "production": {
          "value": 9556.054035616438,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 11.3,
          "bound": "exact"
        },
        "reserves": {
          "value": 267200,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 17,
          "bound": "exact"
        }
      },
      {
        "name": "Canada",
        "production": {
          "value": 4963.934906849316,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 5.9,
          "bound": "exact"
        },
        "reserves": {
          "value": 5080,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.3,
          "bound": "exact"
        }
      },
      {
        "name": "Iraq",
        "production": {
          "value": 4388.068493150685,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 5.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 140000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 8.9,
          "bound": "exact"
        }
      },
      {
        "name": "China",
        "production": {
          "value": 4324.684931506849,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 5.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 34472,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.2,
          "bound": "exact"
        }
      },
      {
        "name": "Iran",
        "production": {
          "value": 4051.4246575342468,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.8,
          "bound": "exact"
        },
        "reserves": {
          "value": 208600,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 13.3,
          "bound": "exact"
        }
      },
      {
        "name": "United Arab Emirates",
        "production": {
          "value": 3771.219178082192,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.5,
          "bound": "exact"
        },
        "reserves": {
          "value": 120000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 7.6,
          "bound": "exact"
        }
      },
      {
        "name": "Brazil",
        "production": {
          "value": 3769.407010164946,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.5,
          "bound": "exact"
        },
        "reserves": {
          "value": 16841,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.1,
          "bound": "exact"
        }
      },
      {
        "name": "Kuwait",
        "production": {
          "value": 2583.5479452054797,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 101500,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 6.5,
          "bound": "exact"
        }
      },
      {
        "name": "Kazakhstan",
        "production": {
          "value": 2046.610159015274,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.4,
          "bound": "exact"
        },
        "reserves": {
          "value": 30000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.9,
          "bound": "exact"
        }
      },
      {
        "name": "Norway",
        "production": {
          "value": 1858.4642345479451,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 5919,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.4,
          "bound": "exact"
        }
      },
      {
        "name": "Mexico",
        "production": {
          "value": 1726.046087671233,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2,
          "bound": "exact"
        },
        "reserves": {
          "value": 5136,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.3,
          "bound": "exact"
        }
      },
      {
        "name": "Nigeria",
        "production": {
          "value": 1605.4142781736975,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.9,
          "bound": "exact"
        },
        "reserves": {
          "value": 37010,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.4,
          "bound": "exact"
        }
      },
      {
        "name": "Libya",
        "production": {
          "value": 1363.041095890411,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.6,
          "bound": "exact"
        },
        "reserves": {
          "value": 48363,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3.1,
          "bound": "exact"
        }
      },
      {
        "name": "Qatar",
        "production": {
          "value": 1297.384436580822,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.5,
          "bound": "exact"
        },
        "reserves": {
          "value": 25244,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.6,
          "bound": "exact"
        }
      },
      {
        "name": "Algeria",
        "production": {
          "value": 1142.958904109589,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.4,
          "bound": "exact"
        },
        "reserves": {
          "value": 12200,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.8,
          "bound": "exact"
        }
      },
      {
        "name": "Angola",
        "production": {
          "value": 1030.8147238615236,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 2550,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.2,
          "bound": "exact"
        }
      },
      {
        "name": "Oman",
        "production": {
          "value": 1002.0691753424658,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 4825,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.3,
          "bound": "exact"
        }
      },
      {
        "name": "Venezuela",
        "production": {
          "value": 972.6164383561644,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 303701,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 19.3,
          "bound": "exact"
        }
      },
      {
        "name": "Azerbaijan",
        "production": {
          "value": 560.6209743572489,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 7000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.4,
          "bound": "exact"
        }
      },
      {
        "name": "Ecuador",
        "production": {
          "value": 440.7002074273973,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.5,
          "bound": "exact"
        },
        "reserves": {
          "value": 8273,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.5,
          "bound": "exact"
        }
      }
    ],
    "sources": [
      {
        "label": "US EIA — International Energy Data",
        "url": "https://www.eia.gov/international/data/world"
      },
      {
        "label": "OPEC — Annual Statistical Bulletin 2026",
        "url": "https://publications.opec.org/ASSETS/assetdb/asb-2026.pdf"
      }
    ],
    "notes": [
      "OPEC's reserve figure for Canada excludes oil sands; counting them, Canada's reserves are several times larger."
    ]
  },
  "Natural Gas": {
    "measure": "Dry natural gas production (EIA); proven reserves at year-end (OPEC)",
    "productionYear": "2024",
    "reservesYear": "2025",
    "productionUnit": "bcm",
    "reservesUnit": "bcm",
    "worldProduction": {
      "value": 4218.349190550455,
      "lowerBound": false
    },
    "worldReserves": {
      "value": 220307,
      "lowerBound": false
    },
    "countries": [
      {
        "name": "United States",
        "production": {
          "value": 1069.4311709782937,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 25.4,
          "bound": "exact"
        },
        "reserves": {
          "value": 13894,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 6.3,
          "bound": "exact"
        }
      },
      {
        "name": "Russia",
        "production": {
          "value": 642.0409745112812,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 15.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 41997,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 19.1,
          "bound": "exact"
        }
      },
      {
        "name": "Iran",
        "production": {
          "value": 279.00145892607986,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 6.6,
          "bound": "exact"
        },
        "reserves": {
          "value": 33988,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 15.4,
          "bound": "exact"
        }
      },
      {
        "name": "China",
        "production": {
          "value": 258.4436224064633,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 6.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 3243,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.5,
          "bound": "exact"
        }
      },
      {
        "name": "Canada",
        "production": {
          "value": 198.95219361392827,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 5558,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.5,
          "bound": "exact"
        }
      },
      {
        "name": "Qatar",
        "production": {
          "value": 169.95443088929267,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4,
          "bound": "exact"
        },
        "reserves": {
          "value": 23831,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 10.8,
          "bound": "exact"
        }
      },
      {
        "name": "Australia",
        "production": {
          "value": 152.17628088921506,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.6,
          "bound": "exact"
        },
        "reserves": {
          "value": 2741,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.2,
          "bound": "exact"
        }
      },
      {
        "name": "Norway",
        "production": {
          "value": 130.91798200357718,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 1646,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.7,
          "bound": "exact"
        }
      },
      {
        "name": "Saudi Arabia",
        "production": {
          "value": 123.38515474590736,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.9,
          "bound": "exact"
        },
        "reserves": {
          "value": 9786,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 4.4,
          "bound": "exact"
        }
      },
      {
        "name": "Algeria",
        "production": {
          "value": 98.80507972803824,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.3,
          "bound": "exact"
        },
        "reserves": {
          "value": 4504,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2,
          "bound": "exact"
        }
      },
      {
        "name": "Malaysia",
        "production": {
          "value": 80.5776454368299,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.9,
          "bound": "exact"
        },
        "reserves": {
          "value": 2156,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1,
          "bound": "exact"
        }
      },
      {
        "name": "Turkmenistan",
        "production": {
          "value": 77.60007314770155,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.8,
          "bound": "exact"
        },
        "reserves": {
          "value": 13900,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 6.3,
          "bound": "exact"
        }
      },
      {
        "name": "Indonesia",
        "production": {
          "value": 69.79688711592816,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 918,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.4,
          "bound": "exact"
        }
      },
      {
        "name": "United Arab Emirates",
        "production": {
          "value": 59.411250179407254,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.4,
          "bound": "exact"
        },
        "reserves": {
          "value": 8410,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3.8,
          "bound": "exact"
        }
      },
      {
        "name": "Egypt",
        "production": {
          "value": 47.47230389274829,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 2209,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1,
          "bound": "exact"
        }
      },
      {
        "name": "Argentina",
        "production": {
          "value": 46.78011811623545,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 530,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.2,
          "bound": "exact"
        }
      },
      {
        "name": "Uzbekistan",
        "production": {
          "value": 46.19846063755099,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 846,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.4,
          "bound": "exact"
        }
      },
      {
        "name": "Oman",
        "production": {
          "value": 44.349334903661116,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 652,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.3,
          "bound": "exact"
        }
      },
      {
        "name": "Nigeria",
        "production": {
          "value": 39.08910879088156,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.9,
          "bound": "exact"
        },
        "reserves": {
          "value": 6111,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.8,
          "bound": "exact"
        }
      },
      {
        "name": "Azerbaijan",
        "production": {
          "value": 37.87513969554177,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.9,
          "bound": "exact"
        },
        "reserves": {
          "value": 2600,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.2,
          "bound": "exact"
        }
      },
      {
        "name": "Kazakhstan",
        "production": {
          "value": 29.26409059562564,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 1830,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.8,
          "bound": "exact"
        }
      },
      {
        "name": "Venezuela",
        "production": {
          "value": 25.42990465225774,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.6,
          "bound": "exact"
        },
        "reserves": {
          "value": 5418,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.5,
          "bound": "exact"
        }
      },
      {
        "name": "Kuwait",
        "production": {
          "value": 19.912355646578344,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.5,
          "bound": "exact"
        },
        "reserves": {
          "value": 1784,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.8,
          "bound": "exact"
        }
      },
      {
        "name": "Mozambique",
        "production": {
          "value": 12.169101900653486,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.3,
          "bound": "exact"
        },
        "reserves": {
          "value": 2840,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.3,
          "bound": "exact"
        }
      },
      {
        "name": "Iraq",
        "production": {
          "value": 10.322209728831307,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 3605,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.6,
          "bound": "exact"
        }
      }
    ],
    "sources": [
      {
        "label": "US EIA — International Energy Data",
        "url": "https://www.eia.gov/international/data/world"
      },
      {
        "label": "OPEC — Annual Statistical Bulletin 2026",
        "url": "https://publications.opec.org/ASSETS/assetdb/asb-2026.pdf"
      }
    ]
  },
  "Coal": {
    "measure": "Coal production and recoverable reserves (EIA)",
    "productionYear": "2024",
    "reservesYear": "2023",
    "productionUnit": "t",
    "reservesUnit": "t",
    "worldProduction": {
      "value": 8797184379.389578,
      "lowerBound": false
    },
    "worldReserves": {
      "value": 1165892613459.861,
      "lowerBound": false
    },
    "countries": [
      {
        "name": "China",
        "production": {
          "value": 4402501222.000046,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 50,
          "bound": "exact"
        },
        "reserves": {
          "value": 157040813238.89655,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 13.5,
          "bound": "exact"
        }
      },
      {
        "name": "India",
        "production": {
          "value": 1012945838.1122031,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 11.5,
          "bound": "exact"
        },
        "reserves": {
          "value": 127726848100.58862,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 11,
          "bound": "exact"
        }
      },
      {
        "name": "Indonesia",
        "production": {
          "value": 836000000.0000056,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 9.5,
          "bound": "exact"
        },
        "reserves": {
          "value": 35054958310.82022,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3,
          "bound": "exact"
        }
      },
      {
        "name": "Russia",
        "production": {
          "value": 476207872.65377164,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 5.4,
          "bound": "exact"
        },
        "reserves": {
          "value": 162165807143.9872,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 13.9,
          "bound": "exact"
        }
      },
      {
        "name": "Australia",
        "production": {
          "value": 467739250.9999969,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 5.3,
          "bound": "exact"
        },
        "reserves": {
          "value": 149471822240.33432,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 12.8,
          "bound": "exact"
        }
      },
      {
        "name": "United States",
        "production": {
          "value": 464968760.56745577,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 5.3,
          "bound": "exact"
        },
        "reserves": {
          "value": 247882705204.99353,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 21.3,
          "bound": "exact"
        }
      },
      {
        "name": "South Africa",
        "production": {
          "value": 237425368.16400373,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 9892988234.743814,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.8,
          "bound": "exact"
        }
      },
      {
        "name": "Kazakhstan",
        "production": {
          "value": 112888131.45402461,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.3,
          "bound": "exact"
        },
        "reserves": {
          "value": 25604969549.238388,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.2,
          "bound": "exact"
        }
      },
      {
        "name": "Germany",
        "production": {
          "value": 91940856.99999848,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1,
          "bound": "exact"
        },
        "reserves": {
          "value": 35399957900.52876,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3,
          "bound": "exact"
        }
      },
      {
        "name": "Poland",
        "production": {
          "value": 85159604.23662537,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1,
          "bound": "exact"
        },
        "reserves": {
          "value": 27757966988.781845,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.4,
          "bound": "exact"
        }
      },
      {
        "name": "Mongolia",
        "production": {
          "value": 82637774.87622464,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.9,
          "bound": "exact"
        },
        "reserves": {
          "value": 2519997003.088488,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.2,
          "bound": "exact"
        }
      },
      {
        "name": "Türkiye",
        "production": {
          "value": 78997958.99999984,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.9,
          "bound": "exact"
        },
        "reserves": {
          "value": 10974986947.974665,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.9,
          "bound": "exact"
        }
      },
      {
        "name": "Colombia",
        "production": {
          "value": 58077777.14759395,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 4553994584.152768,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.4,
          "bound": "exact"
        }
      },
      {
        "name": "Canada",
        "production": {
          "value": 48642803.876221664,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.6,
          "bound": "exact"
        },
        "reserves": {
          "value": 6581992172.352551,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.6,
          "bound": "exact"
        }
      },
      {
        "name": "Vietnam",
        "production": {
          "value": 44648584.00000031,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.5,
          "bound": "exact"
        },
        "reserves": {
          "value": 3115996294.2951307,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.3,
          "bound": "exact"
        }
      },
      {
        "name": "Serbia",
        "production": {
          "value": 31249439.999999996,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.4,
          "bound": "exact"
        },
        "reserves": {
          "value": 7111991542.049733,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.6,
          "bound": "exact"
        }
      },
      {
        "name": "Czechia",
        "production": {
          "value": 25031996.999999605,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.3,
          "bound": "exact"
        },
        "reserves": {
          "value": 3594995724.644093,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.3,
          "bound": "exact"
        }
      },
      {
        "name": "North Korea",
        "production": {
          "value": 23004557.00000018,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.3,
          "bound": "exact"
        },
        "reserves": {
          "value": 10599987393.94364,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.9,
          "bound": "exact"
        }
      },
      {
        "name": "Ukraine",
        "production": {
          "value": 19769000.000000343,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 34374959119.51063,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.9,
          "bound": "exact"
        }
      },
      {
        "name": "Laos",
        "production": {
          "value": 18020838.000000432,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 61999926.2664628,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0,
          "bound": "exact"
        }
      },
      {
        "name": "Brazil",
        "production": {
          "value": 6078811.183472004,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 6595992155.703043,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.6,
          "bound": "exact"
        }
      },
      {
        "name": "Kyrgyzstan",
        "production": {
          "value": 4396322.000000003,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0,
          "bound": "exact"
        },
        "reserves": {
          "value": 28498966107.547153,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.4,
          "bound": "exact"
        }
      },
      {
        "name": "New Zealand",
        "production": {
          "value": 2509426.000000079,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0,
          "bound": "exact"
        },
        "reserves": {
          "value": 6749991972.558451,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.6,
          "bound": "exact"
        }
      },
      {
        "name": "Eswatini",
        "production": {
          "value": 354062.99999999854,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0,
          "bound": "exact"
        },
        "reserves": {
          "value": 4643994477.1202135,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.4,
          "bound": "exact"
        }
      }
    ],
    "sources": [
      {
        "label": "US EIA — International Energy Data",
        "url": "https://www.eia.gov/international/data/world"
      }
    ]
  }
};
