/**
 * The published estimates of modern slavery: the world, its five regions,
 * and the countries the Global Slavery Index names.
 *
 * GENERATED by build-modern-slavery.cjs on 2026-10-06 — do not edit by hand;
 * change the script and re-run it.
 *
 * Every figure was read by the script out of the sentence that states it on
 * Walk Free's findings pages for the Global Slavery Index 2023, which reports
 * the Global Estimates of Modern Slavery that the ILO, Walk Free and the IOM
 * published in 2022. They are estimates for any given day in 2021, from
 * household surveys and case data, not counts.
 *
 * There is no figure for every country here: Walk Free gives its
 * country-level dataset on request, and the site does not hold it. The ten
 * countries with the highest and the lowest prevalence are given by name, as
 * the page names them; their rates are printed only in a chart.
 */
export const MODERN_SLAVERY_SOURCES = {
  estimates: { label: "ILO, Walk Free and IOM — Global Estimates of Modern Slavery (2022), as reported by Walk Free", url: "https://www.walkfree.org/global-slavery-index/findings/global-findings/" },
  index: { label: "Walk Free — Global Slavery Index 2023", url: "https://www.walkfree.org/global-slavery-index/" },
  ilo: { label: "ILO — main figures on forced labour (2022 Global Estimates; Profits and Poverty, 2024)", url: "https://www.ilo.org/topics-and-sectors/forced-labour-modern-slavery-and-trafficking-persons/data-and-research-forced-labour" },
  retrieved: "2026-10-06",
};

export const MODERN_SLAVERY = {
  /** The estimates are for any given day in this year. */
  year: 2021,
  /** Millions of people. */
  world: { people: 50, forcedLabour: 27.6, forcedMarriage: 22, /** "More than" this many are children. */ childrenOver: 12, womenAndGirlsPct: 54, /** The rise since the 2016 estimates. */ risenSince2016: 10 },
  /**
   * The forms forced labour takes, millions of people, as the ILO gives them: in the private economy outside the sex
   * trade, in forced commercial sexual exploitation, and imposed by the state. Rounded each on its own, so they come
   * to within a tenth of the total.
   */
  forcedLabourForms: { privateEconomy: 17.3, sexualExploitation: 6.3, stateImposed: 3.9 },
  /** Of the people in forced labour: the share who are women and girls, and the millions of them in each kind; the share who are children, and how many. */
  forcedLabourWho: { womenAndGirlsPct: 39.4, womenInSexualExploitation: 4.9, womenInOtherSectors: 6, childrenPct: 12, children: 3.3 },
  /** Illegal profits made from forced labour each year, US$ billions, and the year of the ILO report that estimates them. */
  profits: { billions: 236, report: 2024 },
  /** Each region: millions of people, and people per thousand - in all, in forced labour, in forced marriage. */
  regions: [
    { name: "Asia and the Pacific", millions: 29.3, per1000: 6.8, labourPer1000: 3.5, marriagePer1000: 3.3, url: "https://www.walkfree.org/global-slavery-index/findings/regional-findings/asia-and-the-pacific/" },
    { name: "Africa", millions: 7, per1000: 5.2, labourPer1000: 2.9, marriagePer1000: 2.4, url: "https://www.walkfree.org/global-slavery-index/findings/regional-findings/africa/" },
    { name: "Europe and Central Asia", millions: 6.4, per1000: 6.9, labourPer1000: 4.4, marriagePer1000: 2.5, url: "https://www.walkfree.org/global-slavery-index/findings/regional-findings/europe-and-central-asia/" },
    { name: "Americas", millions: 5.1, per1000: 5, labourPer1000: 3.5, marriagePer1000: 1.5, url: "https://www.walkfree.org/global-slavery-index/findings/regional-findings/americas/" },
    { name: "Arab States", millions: 1.7, per1000: 10.1, labourPer1000: 5.3, marriagePer1000: 4.8, url: "https://www.walkfree.org/global-slavery-index/findings/regional-findings/arab-states/" },
  ],
  /** The ten countries with the largest estimated numbers, millions of people. */
  largest: [
    { country: "India", millions: 11 },
    { country: "China", millions: 5.8 },
    { country: "North Korea", millions: 2.7 },
    { country: "Pakistan", millions: 2.3 },
    { country: "Russia", millions: 1.9 },
    { country: "Indonesia", millions: 1.8 },
    { country: "Nigeria", millions: 1.6 },
    { country: "Türkiye", millions: 1.3 },
    { country: "Bangladesh", millions: 1.2 },
    { country: "United States", millions: 1.1 },
  ],
  /** The ten countries with the highest prevalence, highest first, as the page lists them. */
  highestPrevalence: ["North Korea","Eritrea","Mauritania","Saudi Arabia","Türkiye","Tajikistan","United Arab Emirates","Russia","Afghanistan","Kuwait"],
  /** The ten countries with the lowest prevalence, as the page names them. */
  lowestPrevalence: ["Switzerland","Norway","Germany","Netherlands","Sweden","Denmark","Belgium","Ireland","Finland","Japan"],
};
