/**
 * The events behind the yearly charts: the deadliest natural disaster of each
 * year by name, and where most of each year's conflict deaths were.
 *
 * GENERATED by build-named-events.cjs on 2026-10-07 — do not edit by hand; change
 * the script and re-run it.
 *
 * A disaster's name, kind, place, date and death toll are as Wikipedia's list
 * of natural disasters by death toll gives them for the year (revision
 * 1378170748; epidemics and famines are left out, as the list leaves them) - a
 * range where the counts differ. An earthquake's magnitude, damage and second
 * death count are NOAA's, attached only where its database has exactly one
 * such earthquake that year in a country the list names. A storm's damage is
 * the figure in its article's infobox. The event is the year's deadliest, not
 * the year's whole toll.
 *
 * Conflict deaths are the Uppsala Conflict Data Program's, counted where they
 * took place: the three countries with the most in each year, and the world's
 * total for the year.
 */
export const NAMED_EVENTS_SOURCES = {
  list: {
    label: "Wikipedia — List of natural disasters by death toll: deadliest by year (revision 1378170748)",
    url: "https://en.wikipedia.org/w/index.php?title=List_of_natural_disasters_by_death_toll&oldid=1378170748",
  },
  noaa: {
    label: "NOAA National Centers for Environmental Information — Significant Earthquake Database",
    url: "https://www.ngdc.noaa.gov/hazel/view/hazards/earthquake/search",
  },
  ucdp: { label: "Uppsala Conflict Data Program (via Our World in Data) — deaths by country and kind of conflict", url: "https://ourworldindata.org/grapher/deaths-in-armed-conflicts-by-type" },
  retrieved: "2026-10-07",
};

export type DisasterEvent = {
  year: number;
  name: string;
  /** The title of its Wikipedia article. */
  article: string;
  kind: string;
  where: string;
  when: string;
  /** The death toll as the list writes it, and its lowest and highest figures. */
  deaths: string;
  low: number;
  high: number;
  /** An earthquake's magnitude, and NOAA's own count of the dead. */
  magnitude?: number;
  noaaDeaths?: number;
  noaaId?: number;
  /** Damage in US dollars of the year, and whose figure it is. */
  damageUsd?: number;
  damageFrom?: "NOAA" | "Wikipedia";
};

/** One a year, 1990 to 2025. */
export const DEADLIEST_DISASTERS: DisasterEvent[] = [
  { year: 1990, name: "1990 Manjil–Rudbar earthquake", article: "1990 Manjil–Rudbar earthquake", kind: "Earthquake", where: "Iran", when: "June 21", deaths: "35,000–45,000", low: 35000, high: 45000, magnitude: 7.3, noaaDeaths: 40000, noaaId: 5248, damageUsd: 7200000000, damageFrom: "NOAA" },
  { year: 1991, name: "1991 Bangladesh cyclone", article: "1991 Bangladesh cyclone", kind: "Tropical cyclone", where: "Bangladesh", when: "April 24–30", deaths: "138,866", low: 138866, high: 138866, damageUsd: 1700000000, damageFrom: "Wikipedia" },
  { year: 1992, name: "1992 Flores earthquake and tsunami", article: "1992 Flores earthquake and tsunami", kind: "Earthquake, Tsunami", where: "Indonesia", when: "December 12", deaths: "2,500", low: 2500, high: 2500, magnitude: 7.8, noaaDeaths: 2500, noaaId: 5343, damageUsd: 100000000, damageFrom: "NOAA" },
  { year: 1993, name: "1993 Latur earthquake", article: "1993 Latur earthquake", kind: "Earthquake", where: "India", when: "September 30", deaths: "9,748", low: 9748, high: 9748, magnitude: 6.2, noaaDeaths: 11000, noaaId: 5364, damageUsd: 300000000, damageFrom: "NOAA" },
  { year: 1994, name: "Typhoon Fred", article: "Typhoon Fred", kind: "Tropical cyclone", where: "China, Taiwan", when: "August 21", deaths: "3,063", low: 3063, high: 3063, damageUsd: 1190000000, damageFrom: "Wikipedia" },
  { year: 1995, name: "Great Hanshin earthquake", article: "Great Hanshin earthquake", kind: "Earthquake", where: "Japan", when: "January 17", deaths: "6,434", low: 6434, high: 6434, magnitude: 6.9, noaaDeaths: 6434, noaaId: 5399, damageUsd: 100000000000, damageFrom: "NOAA" },
  { year: 1996, name: "1996 Andhra Pradesh cyclone", article: "1996 Andhra Pradesh cyclone", kind: "Tropical cyclone", where: "India", when: "November 4–7", deaths: "1,077", low: 1077, high: 1077, damageUsd: 602000000, damageFrom: "Wikipedia" },
  { year: 1997, name: "Tropical Storm Linda", article: "Tropical Storm Linda (1997)", kind: "Tropical cyclone, Flood", where: "Vietnam, Thailand", when: "November 1–9", deaths: "3,123", low: 3123, high: 3123, damageUsd: 385000000, damageFrom: "Wikipedia" },
  { year: 1998, name: "Hurricane Mitch", article: "Hurricane Mitch", kind: "Tropical cyclone", where: "Honduras, Nicaragua, El Salvador, Guatemala, Belize, Mexico", when: "October 22 – November 9", deaths: "11,374", low: 11374, high: 11374, damageUsd: 6080000000, damageFrom: "Wikipedia" },
  { year: 1999, name: "Vargas tragedy", article: "Vargas tragedy", kind: "Mudslide, Flood", where: "Venezuela", when: "December 14–16", deaths: "10,000–30,000", low: 10000, high: 30000 },
  { year: 2000, name: "2000 Mozambique flood", article: "2000 Mozambique flood", kind: "Flood", where: "Mozambique", when: "February–March", deaths: "700–800", low: 700, high: 800 },
  { year: 2001, name: "2001 Gujarat earthquake", article: "2001 Gujarat earthquake", kind: "Earthquake", where: "India", when: "January 26", deaths: "13,805–20,023", low: 13805, high: 20023, magnitude: 7.6, noaaDeaths: 20005, noaaId: 5589, damageUsd: 2623000000, damageFrom: "NOAA" },
  { year: 2002, name: "2002 Hindu Kush earthquakes", article: "2002 Hindu Kush earthquakes", kind: "Earthquake", where: "Afghanistan", when: "March 25", deaths: "1,200", low: 1200, high: 1200, magnitude: 6.1, noaaDeaths: 1000, noaaId: 5626 },
  { year: 2003, name: "2003 European heatwave", article: "2003 European heatwave", kind: "Heat wave", where: "Europe", when: "July – August", deaths: "72,000", low: 72000, high: 72000 },
  { year: 2004, name: "2004 Indian Ocean earthquake and tsunami", article: "2004 Indian Ocean earthquake and tsunami", kind: "Earthquake, Tsunami", where: "Indonesia, Sri Lanka, India, Thailand, Maldives, Somalia", when: "December 26", deaths: "227,898", low: 227898, high: 227898, magnitude: 9.1, noaaDeaths: 227899, noaaId: 5823, damageUsd: 10000000000, damageFrom: "NOAA" },
  { year: 2005, name: "2005 Kashmir earthquake", article: "2005 Kashmir earthquake", kind: "Earthquake", where: "India, Pakistan", when: "October 8", deaths: "86,000–87,351", low: 86000, high: 87351, magnitude: 7.6, noaaDeaths: 76213, noaaId: 6778, damageUsd: 6680000000, damageFrom: "NOAA" },
  { year: 2006, name: "2006 Yogyakarta earthquake", article: "2006 Yogyakarta earthquake", kind: "Earthquake", where: "Indonesia", when: "May 26", deaths: "5,749–5,778", low: 5749, high: 5778, magnitude: 6.3, noaaDeaths: 6234, noaaId: 7245, damageUsd: 3100000000, damageFrom: "NOAA" },
  { year: 2007, name: "Cyclone Sidr", article: "Cyclone Sidr", kind: "Tropical cyclone", where: "Bangladesh, India", when: "November 11 – 16", deaths: "15,000", low: 15000, high: 15000, damageUsd: 2310000000, damageFrom: "Wikipedia" },
  { year: 2008, name: "Cyclone Nargis", article: "Cyclone Nargis", kind: "Tropical cyclone", where: "Myanmar", when: "April 27 – May 3", deaths: "138,373", low: 138373, high: 138373, damageUsd: 15300000000, damageFrom: "Wikipedia" },
  { year: 2009, name: "2009 Sumatra earthquakes", article: "2009 Sumatra earthquakes", kind: "Earthquake", where: "Indonesia", when: "September 30", deaths: "1,115", low: 1115, high: 1115, magnitude: 7.5, noaaDeaths: 1117, noaaId: 8409, damageUsd: 2200000000, damageFrom: "NOAA" },
  { year: 2010, name: "2010 Haiti earthquake", article: "2010 Haiti earthquake", kind: "Earthquake", where: "Haiti", when: "January 12", deaths: "100,000–316,000", low: 100000, high: 316000, magnitude: 7, noaaDeaths: 316000, noaaId: 8732, damageUsd: 8000000000, damageFrom: "NOAA" },
  { year: 2011, name: "2011 Tōhoku earthquake and tsunami", article: "2011 Tōhoku earthquake and tsunami", kind: "Earthquake, Tsunami", where: "Japan", when: "March 11", deaths: "19,749", low: 19749, high: 19749, magnitude: 9.1, noaaDeaths: 18423, noaaId: 9799, damageUsd: 220136600000, damageFrom: "NOAA" },
  { year: 2012, name: "Typhoon Bopha", article: "Typhoon Bopha", kind: "Tropical cyclone", where: "Philippines", when: "December 4 – 5", deaths: "1,901", low: 1901, high: 1901, damageUsd: 1160000000, damageFrom: "Wikipedia" },
  { year: 2013, name: "Typhoon Haiyan", article: "Typhoon Haiyan", kind: "Tropical cyclone", where: "Philippines, Vietnam, China", when: "November 8 – 10", deaths: "6,340", low: 6340, high: 6340, damageUsd: 2980000000, damageFrom: "Wikipedia" },
  { year: 2014, name: "2014 Badakhshan mudslides", article: "2014 Badakhshan mudslides", kind: "Landslide", where: "Afghanistan", when: "May 2", deaths: "2,700", low: 2700, high: 2700 },
  { year: 2015, name: "April 2015 Nepal earthquake", article: "April 2015 Nepal earthquake", kind: "Earthquake", where: "Nepal, India", when: "April 25", deaths: "8,964", low: 8964, high: 8964, magnitude: 7.8, noaaDeaths: 8957, noaaId: 10134, damageUsd: 6000000000, damageFrom: "NOAA" },
  { year: 2016, name: "2016 Indian heat wave", article: "2016 Indian heat wave", kind: "Heat wave", where: "India", when: "April – May", deaths: "1,111", low: 1111, high: 1111 },
  { year: 2017, name: "Hurricane Maria", article: "Hurricane Maria", kind: "Tropical cyclone", where: "Puerto Rico, Dominica", when: "September 19 – 21", deaths: "3,059", low: 3059, high: 3059, damageUsd: 91606000000, damageFrom: "Wikipedia" },
  { year: 2018, name: "2018 Sulawesi earthquake and tsunami", article: "2018 Sulawesi earthquake and tsunami", kind: "Earthquake, Tsunami", where: "Indonesia", when: "September 28", deaths: "4,340", low: 4340, high: 4340, magnitude: 7.5, noaaDeaths: 4340, noaaId: 10369, damageUsd: 1500000000, damageFrom: "NOAA" },
  { year: 2019, name: "2019 European heatwaves", article: "2019 European heatwaves", kind: "Heat wave", where: "Europe", when: "June – July", deaths: "3,951+", low: 3951, high: 3951 },
  { year: 2020, name: "2020 South Asian floods", article: "2020 South Asian floods", kind: "Floods", where: "Afghanistan, Bangladesh, India, Nepal, Pakistan, Sri Lanka", when: "May – October", deaths: "6,511", low: 6511, high: 6511 },
  { year: 2021, name: "2021 Haiti earthquake", article: "2021 Haiti earthquake", kind: "Earthquake", where: "Haiti", when: "August 14", deaths: "2,248", low: 2248, high: 2248, magnitude: 7.2, noaaDeaths: 2248, noaaId: 10563, damageUsd: 1600000000, damageFrom: "NOAA" },
  { year: 2022, name: "2022 European heatwaves", article: "2022 European heatwaves", kind: "Heat wave", where: "Europe", when: "June 12 – September 12", deaths: "24,501–70,000", low: 24501, high: 70000 },
  { year: 2023, name: "2023 Turkey–Syria earthquakes", article: "2023 Turkey–Syria earthquakes", kind: "Earthquake", where: "Turkey, Syria", when: "February 6", deaths: "59,259–62,013", low: 59259, high: 62013, magnitude: 7.8, noaaDeaths: 56697, noaaId: 10662, damageUsd: 42900000000, damageFrom: "NOAA" },
  { year: 2024, name: "2024 European heatwaves", article: "2024 European heatwaves", kind: "Heat wave", where: "Europe", when: "June – August", deaths: "62,700", low: 62700, high: 62700 },
  { year: 2025, name: "2025 Myanmar earthquake", article: "2025 Myanmar earthquake", kind: "Earthquake", where: "Myanmar, Thailand", when: "28 March", deaths: "5,456", low: 5456, high: 5456, magnitude: 7.7, noaaDeaths: 3815, noaaId: 10815, damageUsd: 10970000000, damageFrom: "NOAA" },
];

/** For each year: the world's conflict deaths, and the three countries where most of them were. */
export const CONFLICT_DEATHS_BY_PLACE: { year: number; world: number; top: [place: string, deaths: number][] }[] = [
  { year: 1990, world: 95405, top: [["Eritrea",30702],["Ethiopia",19154],["Sri Lanka",4819]] },
  { year: 1991, world: 83961, top: [["Iraq",24498],["Somalia",8455],["Sri Lanka",6646]] },
  { year: 1992, world: 75571, top: [["Bosnia and Herzegovina",26868],["Somalia",4729],["Sri Lanka",4444]] },
  { year: 1993, world: 73785, top: [["Bosnia and Herzegovina",13786],["Angola",12397],["Burundi",10212]] },
  { year: 1994, world: 823507, top: [["Rwanda",772413],["Afghanistan",9055],["Bosnia and Herzegovina",7301]] },
  { year: 1995, world: 62309, top: [["Bosnia and Herzegovina",17252],["Afghanistan",5610],["Sri Lanka",4952]] },
  { year: 1996, world: 87390, top: [["Democratic Republic of Congo",34274],["Burundi",18183],["Sri Lanka",4097]] },
  { year: 1997, world: 65899, top: [["Democratic Republic of Congo",13897],["Congo",10426],["Rwanda",7201]] },
  { year: 1998, world: 61094, top: [["Afghanistan",12158],["Democratic Republic of Congo",7695],["Sierra Leone",5141]] },
  { year: 1999, world: 102150, top: [["Eritrea",45191],["Democratic Republic of Congo",7861],["Russia",6197]] },
  { year: 2000, world: 94616, top: [["Eritrea",49976],["Afghanistan",5387],["Colombia",4411]] },
  { year: 2001, world: 37676, top: [["Afghanistan",5553],["Colombia",4620],["United States",2986]] },
  { year: 2002, world: 41396, top: [["Democratic Republic of Congo",7895],["Colombia",5974],["Nepal",4432]] },
  { year: 2003, world: 40381, top: [["Iraq",8007],["Sudan",4761],["Colombia",4635]] },
  { year: 2004, world: 36163, top: [["Sudan",8449],["Iraq",4381],["Colombia",3318]] },
  { year: 2005, world: 20445, top: [["Iraq",3525],["Colombia",2848],["India",1840]] },
  { year: 2006, world: 27836, top: [["Afghanistan",4984],["Iraq",4606],["Sri Lanka",2147]] },
  { year: 2007, world: 28603, top: [["Afghanistan",7021],["Iraq",4513],["Sri Lanka",2536]] },
  { year: 2008, world: 39544, top: [["Sri Lanka",8447],["Afghanistan",5660],["Pakistan",4589]] },
  { year: 2009, world: 51554, top: [["Sri Lanka",10413],["Pakistan",7489],["Afghanistan",6518]] },
  { year: 2010, world: 34206, top: [["Afghanistan",7190],["Pakistan",7188],["Mexico",6280]] },
  { year: 2011, world: 41925, top: [["Afghanistan",7563],["Mexico",4920],["Syria",4343]] },
  { year: 2012, world: 90692, top: [["Syria",53690],["Afghanistan",7764],["Mexico",5922]] },
  { year: 2013, world: 114777, top: [["Syria",76462],["Afghanistan",8130],["Mexico",4450]] },
  { year: 2014, world: 150883, top: [["Syria",78627],["Iraq",16437],["Afghanistan",12565]] },
  { year: 2015, world: 131171, top: [["Syria",59544],["Afghanistan",18016],["Iraq",11300]] },
  { year: 2016, world: 115819, top: [["Syria",53851],["Afghanistan",18991],["Iraq",12046]] },
  { year: 2017, world: 112537, top: [["Syria",38472],["Afghanistan",19766],["Iraq",11437]] },
  { year: 2018, world: 88225, top: [["Afghanistan",26849],["Syria",21679],["Mexico",11175]] },
  { year: 2019, world: 77244, top: [["Afghanistan",30434],["Syria",11168],["Mexico",10432]] },
  { year: 2020, world: 102763, top: [["Ethiopia",24419],["Afghanistan",20836],["Mexico",13326]] },
  { year: 2021, world: 233754, top: [["Ethiopia",129481],["Afghanistan",36375],["Yemen",23444]] },
  { year: 2022, world: 316895, top: [["Ethiopia",164991],["Ukraine",100595],["Mexico",12507]] },
  { year: 2023, world: 169400, top: [["Ukraine",76467],["Palestine",26228],["Sudan",14687]] },
  { year: 2024, world: 187023, top: [["Ukraine",91779],["Palestine",21542],["Mexico",10946]] },
  { year: 2025, world: 244579, top: [["Ukraine",90345],["Sudan",75164],["Palestine",14505]] },
];
