/**
 * Producing countries for the uranium and wheat cards.
 *
 * GENERATED by build-other-producers.cjs on 2026-09-21 — do not edit by
 * hand; change the script and re-run it. See that script for the sources.
 */
import type { ResourceProducers } from "./resourceProducerTypes";

export const OTHER_PRODUCERS: Record<string, ResourceProducers> = {
  "Uranium": {
    "measure": "Uranium mine production, tonnes of uranium (World Nuclear Association); identified recoverable resources to $130/kgU (OECD NEA & IAEA Red Book)",
    "productionYear": "2024",
    "reservesYear": "1 Jan 2023",
    "productionUnit": "t",
    "reservesUnit": "t",
    "reservesLabel": "Resources",
    "worldProduction": {
      "value": 60213,
      "lowerBound": false
    },
    "worldReserves": {
      "value": 5864500,
      "lowerBound": false
    },
    "countries": [
      {
        "name": "Kazakhstan",
        "production": {
          "value": 23270,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 38.6,
          "bound": "exact"
        },
        "reserves": {
          "value": 827500,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 14.1,
          "bound": "exact"
        }
      },
      {
        "name": "Canada",
        "production": {
          "value": 14309,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 23.8,
          "bound": "exact"
        },
        "reserves": {
          "value": 551700,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 9.4,
          "bound": "exact"
        }
      },
      {
        "name": "Namibia",
        "production": {
          "value": 7333,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 12.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 392800,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 6.7,
          "bound": "exact"
        }
      },
      {
        "name": "Australia",
        "production": {
          "value": 4598,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 7.6,
          "bound": "exact"
        },
        "reserves": {
          "value": 1701600,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 29,
          "bound": "exact"
        }
      },
      {
        "name": "Uzbekistan",
        "production": {
          "value": 4000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 6.6,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Russia",
        "production": {
          "value": 2738,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.5,
          "bound": "exact"
        },
        "reserves": {
          "value": 471700,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 8,
          "bound": "exact"
        }
      },
      {
        "name": "China",
        "production": {
          "value": 1600,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 325400,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 5.5,
          "bound": "exact"
        }
      },
      {
        "name": "Niger",
        "production": {
          "value": 962,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.6,
          "bound": "exact"
        },
        "reserves": {
          "value": 351100,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 6,
          "bound": "exact"
        }
      },
      {
        "name": "India",
        "production": {
          "value": 500,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.8,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Ukraine",
        "production": {
          "value": 288,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.5,
          "bound": "exact"
        },
        "reserves": {
          "value": 161300,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.8,
          "bound": "exact"
        }
      },
      {
        "name": "United States",
        "production": {
          "value": 260,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.4,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "South Africa",
        "production": {
          "value": 200,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.3,
          "bound": "exact"
        },
        "reserves": {
          "value": 320900,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 5.5,
          "bound": "exact"
        }
      },
      {
        "name": "Brazil",
        "production": null,
        "productionShare": null,
        "reserves": {
          "value": 167800,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.9,
          "bound": "exact"
        }
      },
      {
        "name": "Mongolia",
        "production": null,
        "productionShare": null,
        "reserves": {
          "value": 144600,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.5,
          "bound": "exact"
        }
      },
      {
        "name": "Tanzania",
        "production": null,
        "productionShare": null,
        "reserves": {
          "value": 57700,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1,
          "bound": "exact"
        }
      }
    ],
    "estimated": [
      "Uzbekistan",
      "China",
      "India",
      "South Africa",
      "Ukraine"
    ],
    "sources": [
      {
        "label": "World Nuclear Association — World Uranium Mining Production",
        "url": "https://world-nuclear.org/information-library/nuclear-fuel-cycle/mining-of-uranium/world-uranium-mining-production"
      },
      {
        "label": "OECD NEA & IAEA — Uranium 2024 (Red Book), via World Nuclear Association",
        "url": "https://world-nuclear.org/information-library/nuclear-fuel-cycle/uranium-resources/supply-of-uranium"
      }
    ],
    "notes": [
      "Resources are what is identified and recoverable at up to $130 per kilogram of uranium; at up to $260/kg the world figure is larger.",
      "Production figures for Uzbekistan, China, India, South Africa, Ukraine are the World Nuclear Association's estimates."
    ]
  },
  "Wheat": {
    "measure": "Wheat production and exports, marketing year 2025/26 (USDA estimate)",
    "productionYear": "2025/26",
    "reservesYear": "2025/26",
    "productionUnit": "t",
    "reservesUnit": "t",
    "reservesLabel": "Exports",
    "worldProduction": {
      "value": 843989000,
      "lowerBound": false
    },
    "worldReserves": {
      "value": 227635000,
      "lowerBound": false
    },
    "countries": [
      {
        "name": "European Union",
        "production": {
          "value": 145136000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 17.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 31715000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 13.9,
          "bound": "exact"
        }
      },
      {
        "name": "China",
        "production": {
          "value": 140070000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 16.6,
          "bound": "exact"
        },
        "reserves": {
          "value": 1098000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.5,
          "bound": "exact"
        }
      },
      {
        "name": "India",
        "production": {
          "value": 117945000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 14,
          "bound": "exact"
        },
        "reserves": {
          "value": 237000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.1,
          "bound": "exact"
        }
      },
      {
        "name": "Russia",
        "production": {
          "value": 90300000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 10.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 48000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 21.1,
          "bound": "exact"
        }
      },
      {
        "name": "United States",
        "production": {
          "value": 54010000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 6.4,
          "bound": "exact"
        },
        "reserves": {
          "value": 24706000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 10.9,
          "bound": "exact"
        }
      },
      {
        "name": "Canada",
        "production": {
          "value": 40562000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.8,
          "bound": "exact"
        },
        "reserves": {
          "value": 29787000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 13.1,
          "bound": "exact"
        }
      },
      {
        "name": "Australia",
        "production": {
          "value": 35985000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.3,
          "bound": "exact"
        },
        "reserves": {
          "value": 24000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 10.5,
          "bound": "exact"
        }
      },
      {
        "name": "Pakistan",
        "production": {
          "value": 28396000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.4,
          "bound": "exact"
        },
        "reserves": {
          "value": 200000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.1,
          "bound": "exact"
        }
      },
      {
        "name": "Argentina",
        "production": {
          "value": 27886000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.3,
          "bound": "exact"
        },
        "reserves": {
          "value": 19100000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 8.4,
          "bound": "exact"
        }
      },
      {
        "name": "Ukraine",
        "production": {
          "value": 24100000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.9,
          "bound": "exact"
        },
        "reserves": {
          "value": 14104000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 6.2,
          "bound": "exact"
        }
      },
      {
        "name": "Kazakhstan",
        "production": {
          "value": 19326000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.3,
          "bound": "exact"
        },
        "reserves": {
          "value": 11500000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 5.1,
          "bound": "exact"
        }
      },
      {
        "name": "Turkey",
        "production": {
          "value": 16800000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2,
          "bound": "exact"
        },
        "reserves": {
          "value": 6468000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.8,
          "bound": "exact"
        }
      },
      {
        "name": "Iran",
        "production": {
          "value": 13500000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.6,
          "bound": "exact"
        },
        "reserves": {
          "value": 200000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.1,
          "bound": "exact"
        }
      },
      {
        "name": "United Kingdom",
        "production": {
          "value": 11958000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.4,
          "bound": "exact"
        },
        "reserves": {
          "value": 419000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.2,
          "bound": "exact"
        }
      },
      {
        "name": "Egypt",
        "production": {
          "value": 9200000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 1550000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.7,
          "bound": "exact"
        }
      },
      {
        "name": "Brazil",
        "production": {
          "value": 7873000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.9,
          "bound": "exact"
        },
        "reserves": {
          "value": 1840000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.8,
          "bound": "exact"
        }
      },
      {
        "name": "Ethiopia",
        "production": {
          "value": 6500000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.8,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Uzbekistan",
        "production": {
          "value": 6100000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 2400000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.1,
          "bound": "exact"
        }
      },
      {
        "name": "Afghanistan",
        "production": {
          "value": 4800000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.6,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Iraq",
        "production": {
          "value": 4400000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.5,
          "bound": "exact"
        },
        "reserves": {
          "value": 100000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0,
          "bound": "exact"
        }
      },
      {
        "name": "Serbia",
        "production": {
          "value": 3681000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.4,
          "bound": "exact"
        },
        "reserves": {
          "value": 1500000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.7,
          "bound": "exact"
        }
      },
      {
        "name": "Moldova",
        "production": {
          "value": 1596000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 1104000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.5,
          "bound": "exact"
        }
      },
      {
        "name": "Uruguay",
        "production": {
          "value": 1430000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 1150000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.5,
          "bound": "exact"
        }
      },
      {
        "name": "Paraguay",
        "production": {
          "value": 1200000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 720000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.3,
          "bound": "exact"
        }
      },
      {
        "name": "Korea, South",
        "production": {
          "value": 38000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0,
          "bound": "exact"
        },
        "reserves": {
          "value": 699000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.3,
          "bound": "exact"
        }
      },
      {
        "name": "Indonesia",
        "production": null,
        "productionShare": null,
        "reserves": {
          "value": 441000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.2,
          "bound": "exact"
        }
      },
      {
        "name": "Vietnam",
        "production": null,
        "productionShare": null,
        "reserves": {
          "value": 597000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.3,
          "bound": "exact"
        }
      }
    ],
    "sources": [
      {
        "label": "USDA FAS — Production, Supply and Distribution (PSD)",
        "url": "https://apps.fas.usda.gov/psdonline/app/index.html"
      }
    ],
    "notes": [
      "USDA counts the European Union as a single producer and exporter.",
      "World figures are the sum of every country USDA lists."
    ]
  }
};
