/**
 * Producing and reserve-holding countries per commodity card.
 *
 * GENERATED by build-resource-producers.cjs on 2026-09-21 — do not edit by
 * hand; change the script and re-run it. See that script for the method.
 */

import type { ResourceProducers } from "./resourceProducerTypes";
export type { ResourceProducers, ResourceProducer, Amount, Share } from "./resourceProducerTypes";

export const RESOURCE_PRODUCERS: Record<string, ResourceProducers> = {
  "Copper": {
    "measure": "Mine production",
    "productionYear": "2025",
    "reservesYear": "2025",
    "productionUnit": "t",
    "reservesUnit": "t",
    "worldProduction": {
      "value": 23000000,
      "lowerBound": false
    },
    "worldReserves": {
      "value": 980000000,
      "lowerBound": false
    },
    "countries": [
      {
        "name": "Chile",
        "production": {
          "value": 5300000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 23,
          "bound": "exact"
        },
        "reserves": {
          "value": 180000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 18.4,
          "bound": "exact"
        }
      },
      {
        "name": "DR Congo",
        "production": {
          "value": 3200000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 13.9,
          "bound": "exact"
        },
        "reserves": {
          "value": 80000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 8.2,
          "bound": "exact"
        }
      },
      {
        "name": "Peru",
        "production": {
          "value": 2700000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 11.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 85000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 8.7,
          "bound": "exact"
        }
      },
      {
        "name": "China",
        "production": {
          "value": 1800000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 7.8,
          "bound": "exact"
        },
        "reserves": {
          "value": 41000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 4.2,
          "bound": "exact"
        }
      },
      {
        "name": "Russia",
        "production": {
          "value": 1300000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 5.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 80000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 8.2,
          "bound": "exact"
        }
      },
      {
        "name": "United States",
        "production": {
          "value": 1000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.3,
          "bound": "exact"
        },
        "reserves": {
          "value": 47000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 4.8,
          "bound": "exact"
        }
      },
      {
        "name": "Zambia",
        "production": {
          "value": 940000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 21000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.1,
          "bound": "exact"
        }
      },
      {
        "name": "Australia",
        "production": {
          "value": 730000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 100000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 10.2,
          "bound": "exact"
        }
      },
      {
        "name": "Indonesia",
        "production": {
          "value": 710000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 21000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.1,
          "bound": "exact"
        }
      },
      {
        "name": "Kazakhstan",
        "production": {
          "value": 710000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 20000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2,
          "bound": "exact"
        }
      },
      {
        "name": "Mexico",
        "production": {
          "value": 690000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3,
          "bound": "exact"
        },
        "reserves": {
          "value": 53000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 5.4,
          "bound": "exact"
        }
      },
      {
        "name": "Canada",
        "production": {
          "value": 500000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 7000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.7,
          "bound": "exact"
        }
      },
      {
        "name": "Poland",
        "production": {
          "value": 410000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.8,
          "bound": "exact"
        },
        "reserves": {
          "value": 33000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3.4,
          "bound": "exact"
        }
      },
      {
        "name": "India",
        "production": {
          "value": 23000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 2200000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.2,
          "bound": "exact"
        }
      }
    ],
    "sources": [
      {
        "label": "USGS — Mineral Commodity Summaries 2026, world tables",
        "url": "https://doi.org/10.3133/mcs2026"
      }
    ],
    "notes": [
      "Countries outside these are grouped by USGS as “other countries”."
    ]
  },
  "Lithium": {
    "measure": "Mine production (lithium content)",
    "productionYear": "2025",
    "reservesYear": "2025",
    "productionUnit": "t",
    "reservesUnit": "t",
    "worldProduction": {
      "value": 290000,
      "lowerBound": false
    },
    "worldReserves": {
      "value": 37000000,
      "lowerBound": false
    },
    "countries": [
      {
        "name": "Australia",
        "production": {
          "value": 92000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 31.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 8400000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 22.7,
          "bound": "exact"
        }
      },
      {
        "name": "China",
        "production": {
          "value": 62000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 21.4,
          "bound": "exact"
        },
        "reserves": {
          "value": 4600000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 12.4,
          "bound": "exact"
        }
      },
      {
        "name": "Chile",
        "production": {
          "value": 56000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 19.3,
          "bound": "exact"
        },
        "reserves": {
          "value": 9200000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 24.9,
          "bound": "exact"
        }
      },
      {
        "name": "Zimbabwe",
        "production": {
          "value": 28000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 9.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 500000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.4,
          "bound": "exact"
        }
      },
      {
        "name": "Argentina",
        "production": {
          "value": 23000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 7.9,
          "bound": "exact"
        },
        "reserves": {
          "value": 4400000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 11.9,
          "bound": "exact"
        }
      },
      {
        "name": "Brazil",
        "production": {
          "value": 12000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 540000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.5,
          "bound": "exact"
        }
      },
      {
        "name": "Mali",
        "production": {
          "value": 9400,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 370000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1,
          "bound": "exact"
        }
      },
      {
        "name": "Canada",
        "production": {
          "value": 5600,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.9,
          "bound": "exact"
        },
        "reserves": {
          "value": 1600000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 4.3,
          "bound": "exact"
        }
      },
      {
        "name": "Portugal",
        "production": {
          "value": 380,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 60000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.2,
          "bound": "exact"
        }
      },
      {
        "name": "United States",
        "production": null,
        "productionWithheld": true,
        "productionShare": null,
        "reserves": {
          "value": 4400000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 11.9,
          "bound": "exact"
        }
      }
    ],
    "sources": [
      {
        "label": "USGS — Mineral Commodity Summaries 2026, world tables",
        "url": "https://doi.org/10.3133/mcs2026"
      }
    ],
    "notes": [
      "Countries outside these are grouped by USGS as “other countries”."
    ]
  },
  "Rare Earth": {
    "measure": "Mine production (rare-earth oxide equivalent)",
    "productionYear": "2025",
    "reservesYear": "2025",
    "productionUnit": "t",
    "reservesUnit": "t",
    "worldProduction": {
      "value": 390000,
      "lowerBound": false
    },
    "worldReserves": {
      "value": 85000000,
      "lowerBound": true
    },
    "countries": [
      {
        "name": "China",
        "production": {
          "value": 270000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 69.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 44000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 51.8,
          "bound": "atMost"
        }
      },
      {
        "name": "United States",
        "production": {
          "value": 51000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 13.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 1900000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.2,
          "bound": "atMost"
        }
      },
      {
        "name": "Australia",
        "production": {
          "value": 29000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 7.4,
          "bound": "exact"
        },
        "reserves": {
          "value": 6300000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 7.4,
          "bound": "atMost"
        }
      },
      {
        "name": "Myanmar",
        "production": {
          "value": 22000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 5.6,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Thailand",
        "production": {
          "value": 4800,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.2,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "India",
        "production": {
          "value": 2900,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.7,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Madagascar",
        "production": {
          "value": 2700,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.7,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Russia",
        "production": {
          "value": 2600,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 3800000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 4.5,
          "bound": "atMost"
        }
      },
      {
        "name": "Brazil",
        "production": {
          "value": 2000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.5,
          "bound": "exact"
        },
        "reserves": {
          "value": 21000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 24.7,
          "bound": "atMost"
        }
      },
      {
        "name": "Nigeria",
        "production": {
          "value": 1500,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.4,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Vietnam",
        "production": {
          "value": 150,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0,
          "bound": "exact"
        },
        "reserves": {
          "value": 3500000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 4.1,
          "bound": "atMost"
        }
      },
      {
        "name": "Malaysia",
        "production": {
          "value": 110,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0,
          "bound": "exact"
        },
        "reserves": {
          "value": 710000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.8,
          "bound": "atMost"
        }
      },
      {
        "name": "Greenland",
        "production": null,
        "productionShare": null,
        "reserves": {
          "value": 1500000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.8,
          "bound": "atMost"
        }
      },
      {
        "name": "Tanzania",
        "production": null,
        "productionShare": null,
        "reserves": {
          "value": 890000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1,
          "bound": "atMost"
        }
      },
      {
        "name": "South Africa",
        "production": null,
        "productionShare": null,
        "reserves": {
          "value": 860000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1,
          "bound": "atMost"
        }
      },
      {
        "name": "Canada",
        "production": null,
        "productionShare": null,
        "reserves": {
          "value": 830000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1,
          "bound": "atMost"
        }
      }
    ],
    "sources": [
      {
        "label": "USGS — Mineral Commodity Summaries 2026, world tables",
        "url": "https://doi.org/10.3133/mcs2026"
      }
    ],
    "notes": [
      "Countries outside these are grouped by USGS as “other countries”."
    ]
  },
  "Iron Ore": {
    "measure": "Mine production (usable ore); reserves as crude ore",
    "productionYear": "2025",
    "reservesYear": "2025",
    "productionUnit": "t",
    "reservesUnit": "t",
    "worldProduction": {
      "value": 2600000000,
      "lowerBound": false
    },
    "worldReserves": {
      "value": 200000000000,
      "lowerBound": false
    },
    "countries": [
      {
        "name": "Australia",
        "production": {
          "value": 980000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 37.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 59000000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 29.5,
          "bound": "exact"
        }
      },
      {
        "name": "Brazil",
        "production": {
          "value": 420000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 16.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 34000000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 17,
          "bound": "exact"
        }
      },
      {
        "name": "India",
        "production": {
          "value": 310000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 11.9,
          "bound": "exact"
        },
        "reserves": {
          "value": 5500000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.8,
          "bound": "exact"
        }
      },
      {
        "name": "China",
        "production": {
          "value": 290000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 11.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 17000000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 8.5,
          "bound": "exact"
        }
      },
      {
        "name": "Iran",
        "production": {
          "value": 93000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.6,
          "bound": "exact"
        },
        "reserves": {
          "value": 4200000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.1,
          "bound": "exact"
        }
      },
      {
        "name": "Russia",
        "production": {
          "value": 86000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.3,
          "bound": "exact"
        },
        "reserves": {
          "value": 35000000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 17.5,
          "bound": "exact"
        }
      },
      {
        "name": "Canada",
        "production": {
          "value": 69000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 6000000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3,
          "bound": "exact"
        }
      },
      {
        "name": "South Africa",
        "production": {
          "value": 66000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.5,
          "bound": "exact"
        },
        "reserves": {
          "value": 1200000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.6,
          "bound": "exact"
        }
      },
      {
        "name": "Ukraine",
        "production": {
          "value": 52000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2,
          "bound": "exact"
        },
        "reserves": {
          "value": 6500000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3.3,
          "bound": "exact"
        }
      },
      {
        "name": "United States",
        "production": {
          "value": 38000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.5,
          "bound": "exact"
        },
        "reserves": {
          "value": 3600000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.8,
          "bound": "exact"
        }
      },
      {
        "name": "Kazakhstan",
        "production": {
          "value": 35000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.3,
          "bound": "exact"
        },
        "reserves": {
          "value": 3800000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.9,
          "bound": "exact"
        }
      },
      {
        "name": "Sweden",
        "production": {
          "value": 26000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1,
          "bound": "exact"
        },
        "reserves": {
          "value": 1300000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.7,
          "bound": "exact"
        }
      },
      {
        "name": "Peru",
        "production": {
          "value": 21000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.8,
          "bound": "exact"
        },
        "reserves": {
          "value": 1800000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.9,
          "bound": "exact"
        }
      },
      {
        "name": "Chile",
        "production": {
          "value": 19000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 3000000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.5,
          "bound": "exact"
        }
      },
      {
        "name": "Turkey",
        "production": {
          "value": 18000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 150000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.1,
          "bound": "exact"
        }
      },
      {
        "name": "Mauritania",
        "production": {
          "value": 15000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.6,
          "bound": "exact"
        },
        "reserves": {
          "value": 10000000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 5,
          "bound": "exact"
        }
      },
      {
        "name": "Mexico",
        "production": {
          "value": 7700000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.3,
          "bound": "exact"
        },
        "reserves": {
          "value": 940000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.5,
          "bound": "exact"
        }
      }
    ],
    "sources": [
      {
        "label": "USGS — Mineral Commodity Summaries 2026, world tables",
        "url": "https://doi.org/10.3133/mcs2026"
      }
    ],
    "notes": [
      "Countries outside these are grouped by USGS as “other countries”."
    ]
  },
  "Gold": {
    "measure": "Mine production",
    "productionYear": "2025",
    "reservesYear": "2025",
    "productionUnit": "t",
    "reservesUnit": "t",
    "worldProduction": {
      "value": 3300,
      "lowerBound": false
    },
    "worldReserves": {
      "value": 66000,
      "lowerBound": false
    },
    "countries": [
      {
        "name": "China",
        "production": {
          "value": 380,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 11.5,
          "bound": "exact"
        },
        "reserves": {
          "value": 3200,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 4.8,
          "bound": "exact"
        }
      },
      {
        "name": "Russia",
        "production": {
          "value": 310,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 9.4,
          "bound": "exact"
        },
        "reserves": {
          "value": 12000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 18.2,
          "bound": "exact"
        }
      },
      {
        "name": "Australia",
        "production": {
          "value": 280,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 8.5,
          "bound": "exact"
        },
        "reserves": {
          "value": 13000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 19.7,
          "bound": "exact"
        }
      },
      {
        "name": "Canada",
        "production": {
          "value": 200,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 6.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 3200,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 4.8,
          "bound": "exact"
        }
      },
      {
        "name": "United States",
        "production": {
          "value": 160,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.8,
          "bound": "exact"
        },
        "reserves": {
          "value": 3000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 4.5,
          "bound": "exact"
        }
      },
      {
        "name": "Ghana",
        "production": {
          "value": 150,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.5,
          "bound": "exact"
        },
        "reserves": {
          "value": 1000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.5,
          "bound": "exact"
        }
      },
      {
        "name": "Mexico",
        "production": {
          "value": 140,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 1400,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.1,
          "bound": "exact"
        }
      },
      {
        "name": "Kazakhstan",
        "production": {
          "value": 130,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.9,
          "bound": "exact"
        },
        "reserves": {
          "value": 2300,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3.5,
          "bound": "exact"
        }
      },
      {
        "name": "Uzbekistan",
        "production": {
          "value": 130,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.9,
          "bound": "exact"
        },
        "reserves": {
          "value": 2200,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3.3,
          "bound": "exact"
        }
      },
      {
        "name": "Peru",
        "production": {
          "value": 110,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.3,
          "bound": "exact"
        },
        "reserves": {
          "value": 2200,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3.3,
          "bound": "exact"
        }
      },
      {
        "name": "South Africa",
        "production": {
          "value": 90,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 5000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 7.6,
          "bound": "exact"
        }
      },
      {
        "name": "Indonesia",
        "production": {
          "value": 90,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.7,
          "bound": "exact"
        },
        "reserves": {
          "value": 3600,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 5.5,
          "bound": "exact"
        }
      },
      {
        "name": "Brazil",
        "production": {
          "value": 80,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.4,
          "bound": "exact"
        },
        "reserves": {
          "value": 2500,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3.8,
          "bound": "exact"
        }
      }
    ],
    "sources": [
      {
        "label": "USGS — Mineral Commodity Summaries 2026, world tables",
        "url": "https://doi.org/10.3133/mcs2026"
      }
    ],
    "notes": [
      "Countries outside these are grouped by USGS as “other countries”."
    ]
  },
  "Silver": {
    "measure": "Mine production",
    "productionYear": "2025",
    "reservesYear": "2025",
    "productionUnit": "t",
    "reservesUnit": "t",
    "worldProduction": {
      "value": 26000,
      "lowerBound": false
    },
    "worldReserves": {
      "value": 610000,
      "lowerBound": false
    },
    "countries": [
      {
        "name": "Mexico",
        "production": {
          "value": 6300,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 24.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 37000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 6.1,
          "bound": "exact"
        }
      },
      {
        "name": "Peru",
        "production": {
          "value": 3600,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 13.8,
          "bound": "exact"
        },
        "reserves": {
          "value": 110000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 18,
          "bound": "exact"
        }
      },
      {
        "name": "China",
        "production": {
          "value": 3400,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 13.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 67000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 11,
          "bound": "exact"
        }
      },
      {
        "name": "Bolivia",
        "production": {
          "value": 1500,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 5.8,
          "bound": "exact"
        },
        "reserves": {
          "value": 22000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3.6,
          "bound": "exact"
        }
      },
      {
        "name": "Chile",
        "production": {
          "value": 1400,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 5.4,
          "bound": "exact"
        },
        "reserves": {
          "value": 33000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 5.4,
          "bound": "exact"
        }
      },
      {
        "name": "Poland",
        "production": {
          "value": 1300,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 5,
          "bound": "exact"
        },
        "reserves": {
          "value": 59000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 9.7,
          "bound": "exact"
        }
      },
      {
        "name": "Russia",
        "production": {
          "value": 1200,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.6,
          "bound": "exact"
        },
        "reserves": {
          "value": 92000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 15.1,
          "bound": "exact"
        }
      },
      {
        "name": "United States",
        "production": {
          "value": 1100,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.2,
          "bound": "exact"
        },
        "reserves": {
          "value": 23000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3.8,
          "bound": "exact"
        }
      },
      {
        "name": "Australia",
        "production": {
          "value": 1000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.8,
          "bound": "exact"
        },
        "reserves": {
          "value": 91000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 14.9,
          "bound": "exact"
        }
      },
      {
        "name": "India",
        "production": {
          "value": 800,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 8000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.3,
          "bound": "exact"
        }
      },
      {
        "name": "Argentina",
        "production": {
          "value": 800,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.1,
          "bound": "exact"
        },
        "reserves": {
          "value": 6500,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.1,
          "bound": "exact"
        }
      },
      {
        "name": "Kazakhstan",
        "production": {
          "value": 630,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.4,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Canada",
        "production": {
          "value": 400,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.5,
          "bound": "exact"
        },
        "reserves": {
          "value": 4900,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.8,
          "bound": "exact"
        }
      },
      {
        "name": "Sweden",
        "production": {
          "value": 400,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.5,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      }
    ],
    "sources": [
      {
        "label": "USGS — Mineral Commodity Summaries 2026, world tables",
        "url": "https://doi.org/10.3133/mcs2026"
      }
    ],
    "notes": [
      "Countries outside these are grouped by USGS as “other countries”."
    ]
  },
  "Aluminum": {
    "measure": "Smelter production (primary aluminum)",
    "productionYear": "2025",
    "reservesYear": null,
    "productionUnit": "t",
    "reservesUnit": null,
    "worldProduction": {
      "value": 74000000,
      "lowerBound": false
    },
    "worldReserves": null,
    "countries": [
      {
        "name": "China",
        "production": {
          "value": 45000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 60.8,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "India",
        "production": {
          "value": 4200000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 5.7,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Russia",
        "production": {
          "value": 3900000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 5.3,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Canada",
        "production": {
          "value": 3300000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.5,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "United Arab Emirates",
        "production": {
          "value": 2700000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.6,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Bahrain",
        "production": {
          "value": 1600000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.2,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Australia",
        "production": {
          "value": 1500000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Norway",
        "production": {
          "value": 1300000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.8,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Brazil",
        "production": {
          "value": 1200000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.6,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Malaysia",
        "production": {
          "value": 1100000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.5,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Iceland",
        "production": {
          "value": 750000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "United States",
        "production": {
          "value": 660000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.9,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      }
    ],
    "sources": [
      {
        "label": "USGS — Mineral Commodity Summaries 2026, world tables",
        "url": "https://doi.org/10.3133/mcs2026"
      }
    ],
    "notes": [
      "USGS publishes no reserves for refined aluminum — its reserves are bauxite ore, a separate commodity.",
      "Countries outside these are grouped by USGS as “other countries”."
    ]
  }
};
