/**
 * Producing and reserve-holding countries per commodity card.
 *
 * GENERATED by build-resource-producers.cjs on 2026-09-21 — do not edit by
 * hand; change the script and re-run it. See that script for the method.
 */

export type Amount = { tonnes: number; lowerBound: boolean };
export type Share = { pct: number; bound: "exact" | "atMost" | "atLeast" };

export interface ResourceProducer {
  name: string;
  production: Amount | null;
  /** USGS withholds the figure to protect company data; not zero. */
  productionWithheld?: boolean;
  productionShare: Share | null;
  reserves: Amount | null;
  reservesShare: Share | null;
}

export interface ResourceProducers {
  /** What "production" means for this commodity, in USGS's terms. */
  measure: string;
  year: string;
  worldProduction: Amount;
  /** Null where USGS reports no reserves for the commodity (aluminum). */
  worldReserves: Amount | null;
  /** Largest producer first. */
  countries: ResourceProducer[];
}

export const RESOURCE_PRODUCERS_SOURCE = {
  label: "USGS — Mineral Commodity Summaries 2026, world tables",
  url: "https://doi.org/10.3133/mcs2026",
};

export const RESOURCE_PRODUCERS: Record<string, ResourceProducers> = {
  "Copper": {
    "measure": "Mine production",
    "year": "2025",
    "worldProduction": {
      "tonnes": 23000000,
      "lowerBound": false
    },
    "worldReserves": {
      "tonnes": 980000000,
      "lowerBound": false
    },
    "countries": [
      {
        "name": "Chile",
        "production": {
          "tonnes": 5300000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 23,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 180000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 18.4,
          "bound": "exact"
        }
      },
      {
        "name": "DR Congo",
        "production": {
          "tonnes": 3200000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 13.9,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 80000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 8.2,
          "bound": "exact"
        }
      },
      {
        "name": "Peru",
        "production": {
          "tonnes": 2700000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 11.7,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 85000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 8.7,
          "bound": "exact"
        }
      },
      {
        "name": "China",
        "production": {
          "tonnes": 1800000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 7.8,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 41000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 4.2,
          "bound": "exact"
        }
      },
      {
        "name": "Russia",
        "production": {
          "tonnes": 1300000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 5.7,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 80000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 8.2,
          "bound": "exact"
        }
      },
      {
        "name": "United States",
        "production": {
          "tonnes": 1000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.3,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 47000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 4.8,
          "bound": "exact"
        }
      },
      {
        "name": "Zambia",
        "production": {
          "tonnes": 940000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.1,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 21000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.1,
          "bound": "exact"
        }
      },
      {
        "name": "Australia",
        "production": {
          "tonnes": 730000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.2,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 100000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 10.2,
          "bound": "exact"
        }
      },
      {
        "name": "Indonesia",
        "production": {
          "tonnes": 710000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.1,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 21000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.1,
          "bound": "exact"
        }
      },
      {
        "name": "Kazakhstan",
        "production": {
          "tonnes": 710000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.1,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 20000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2,
          "bound": "exact"
        }
      },
      {
        "name": "Mexico",
        "production": {
          "tonnes": 690000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 53000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 5.4,
          "bound": "exact"
        }
      },
      {
        "name": "Canada",
        "production": {
          "tonnes": 500000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.2,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 7000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.7,
          "bound": "exact"
        }
      },
      {
        "name": "Poland",
        "production": {
          "tonnes": 410000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.8,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 33000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3.4,
          "bound": "exact"
        }
      },
      {
        "name": "India",
        "production": {
          "tonnes": 23000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.1,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 2200000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.2,
          "bound": "exact"
        }
      }
    ]
  },
  "Lithium": {
    "measure": "Mine production (lithium content)",
    "year": "2025",
    "worldProduction": {
      "tonnes": 290000,
      "lowerBound": false
    },
    "worldReserves": {
      "tonnes": 37000000,
      "lowerBound": false
    },
    "countries": [
      {
        "name": "Australia",
        "production": {
          "tonnes": 92000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 31.7,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 8400000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 22.7,
          "bound": "exact"
        }
      },
      {
        "name": "China",
        "production": {
          "tonnes": 62000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 21.4,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 4600000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 12.4,
          "bound": "exact"
        }
      },
      {
        "name": "Chile",
        "production": {
          "tonnes": 56000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 19.3,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 9200000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 24.9,
          "bound": "exact"
        }
      },
      {
        "name": "Zimbabwe",
        "production": {
          "tonnes": 28000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 9.7,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 500000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.4,
          "bound": "exact"
        }
      },
      {
        "name": "Argentina",
        "production": {
          "tonnes": 23000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 7.9,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 4400000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 11.9,
          "bound": "exact"
        }
      },
      {
        "name": "Brazil",
        "production": {
          "tonnes": 12000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.1,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 540000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.5,
          "bound": "exact"
        }
      },
      {
        "name": "Mali",
        "production": {
          "tonnes": 9400,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.2,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 370000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1,
          "bound": "exact"
        }
      },
      {
        "name": "Canada",
        "production": {
          "tonnes": 5600,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.9,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 1600000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 4.3,
          "bound": "exact"
        }
      },
      {
        "name": "Portugal",
        "production": {
          "tonnes": 380,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.1,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 60000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.2,
          "bound": "exact"
        }
      },
      {
        "name": "United States",
        "production": null,
        "productionWithheld": true,
        "productionShare": null,
        "reserves": {
          "tonnes": 4400000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 11.9,
          "bound": "exact"
        }
      }
    ]
  },
  "Rare Earth": {
    "measure": "Mine production (rare-earth oxide equivalent)",
    "year": "2025",
    "worldProduction": {
      "tonnes": 390000,
      "lowerBound": false
    },
    "worldReserves": {
      "tonnes": 85000000,
      "lowerBound": true
    },
    "countries": [
      {
        "name": "China",
        "production": {
          "tonnes": 270000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 69.2,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 44000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 51.8,
          "bound": "atMost"
        }
      },
      {
        "name": "United States",
        "production": {
          "tonnes": 51000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 13.1,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 1900000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.2,
          "bound": "atMost"
        }
      },
      {
        "name": "Australia",
        "production": {
          "tonnes": 29000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 7.4,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 6300000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 7.4,
          "bound": "atMost"
        }
      },
      {
        "name": "Myanmar",
        "production": {
          "tonnes": 22000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 5.6,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Thailand",
        "production": {
          "tonnes": 4800,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.2,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "India",
        "production": {
          "tonnes": 2900,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.7,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Madagascar",
        "production": {
          "tonnes": 2700,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.7,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Russia",
        "production": {
          "tonnes": 2600,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.7,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 3800000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 4.5,
          "bound": "atMost"
        }
      },
      {
        "name": "Brazil",
        "production": {
          "tonnes": 2000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.5,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 21000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 24.7,
          "bound": "atMost"
        }
      },
      {
        "name": "Nigeria",
        "production": {
          "tonnes": 1500,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.4,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Vietnam",
        "production": {
          "tonnes": 150,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 3500000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 4.1,
          "bound": "atMost"
        }
      },
      {
        "name": "Malaysia",
        "production": {
          "tonnes": 110,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 710000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.8,
          "bound": "atMost"
        }
      },
      {
        "name": "Greenland",
        "production": null,
        "productionShare": null,
        "reserves": {
          "tonnes": 1500000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.8,
          "bound": "atMost"
        }
      },
      {
        "name": "Tanzania",
        "production": null,
        "productionShare": null,
        "reserves": {
          "tonnes": 890000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1,
          "bound": "atMost"
        }
      },
      {
        "name": "South Africa",
        "production": null,
        "productionShare": null,
        "reserves": {
          "tonnes": 860000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1,
          "bound": "atMost"
        }
      },
      {
        "name": "Canada",
        "production": null,
        "productionShare": null,
        "reserves": {
          "tonnes": 830000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1,
          "bound": "atMost"
        }
      }
    ]
  },
  "Iron Ore": {
    "measure": "Mine production (usable ore); reserves as crude ore",
    "year": "2025",
    "worldProduction": {
      "tonnes": 2600000000,
      "lowerBound": false
    },
    "worldReserves": {
      "tonnes": 200000000000,
      "lowerBound": false
    },
    "countries": [
      {
        "name": "Australia",
        "production": {
          "tonnes": 980000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 37.7,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 59000000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 29.5,
          "bound": "exact"
        }
      },
      {
        "name": "Brazil",
        "production": {
          "tonnes": 420000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 16.2,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 34000000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 17,
          "bound": "exact"
        }
      },
      {
        "name": "India",
        "production": {
          "tonnes": 310000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 11.9,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 5500000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.8,
          "bound": "exact"
        }
      },
      {
        "name": "China",
        "production": {
          "tonnes": 290000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 11.2,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 17000000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 8.5,
          "bound": "exact"
        }
      },
      {
        "name": "Iran",
        "production": {
          "tonnes": 93000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.6,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 4200000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.1,
          "bound": "exact"
        }
      },
      {
        "name": "Russia",
        "production": {
          "tonnes": 86000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.3,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 35000000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 17.5,
          "bound": "exact"
        }
      },
      {
        "name": "Canada",
        "production": {
          "tonnes": 69000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.7,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 6000000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3,
          "bound": "exact"
        }
      },
      {
        "name": "South Africa",
        "production": {
          "tonnes": 66000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.5,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 1200000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.6,
          "bound": "exact"
        }
      },
      {
        "name": "Ukraine",
        "production": {
          "tonnes": 52000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 6500000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3.3,
          "bound": "exact"
        }
      },
      {
        "name": "United States",
        "production": {
          "tonnes": 38000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.5,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 3600000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.8,
          "bound": "exact"
        }
      },
      {
        "name": "Kazakhstan",
        "production": {
          "tonnes": 35000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.3,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 3800000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.9,
          "bound": "exact"
        }
      },
      {
        "name": "Sweden",
        "production": {
          "tonnes": 26000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 1300000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.7,
          "bound": "exact"
        }
      },
      {
        "name": "Peru",
        "production": {
          "tonnes": 21000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.8,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 1800000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.9,
          "bound": "exact"
        }
      },
      {
        "name": "Chile",
        "production": {
          "tonnes": 19000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.7,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 3000000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.5,
          "bound": "exact"
        }
      },
      {
        "name": "Turkey",
        "production": {
          "tonnes": 18000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.7,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 150000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.1,
          "bound": "exact"
        }
      },
      {
        "name": "Mauritania",
        "production": {
          "tonnes": 15000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.6,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 10000000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 5,
          "bound": "exact"
        }
      },
      {
        "name": "Mexico",
        "production": {
          "tonnes": 7700000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.3,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 940000000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.5,
          "bound": "exact"
        }
      }
    ]
  },
  "Gold": {
    "measure": "Mine production",
    "year": "2025",
    "worldProduction": {
      "tonnes": 3300,
      "lowerBound": false
    },
    "worldReserves": {
      "tonnes": 66000,
      "lowerBound": false
    },
    "countries": [
      {
        "name": "China",
        "production": {
          "tonnes": 380,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 11.5,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 3200,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 4.8,
          "bound": "exact"
        }
      },
      {
        "name": "Russia",
        "production": {
          "tonnes": 310,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 9.4,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 12000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 18.2,
          "bound": "exact"
        }
      },
      {
        "name": "Australia",
        "production": {
          "tonnes": 280,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 8.5,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 13000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 19.7,
          "bound": "exact"
        }
      },
      {
        "name": "Canada",
        "production": {
          "tonnes": 200,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 6.1,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 3200,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 4.8,
          "bound": "exact"
        }
      },
      {
        "name": "United States",
        "production": {
          "tonnes": 160,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.8,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 3000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 4.5,
          "bound": "exact"
        }
      },
      {
        "name": "Ghana",
        "production": {
          "tonnes": 150,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.5,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 1000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.5,
          "bound": "exact"
        }
      },
      {
        "name": "Mexico",
        "production": {
          "tonnes": 140,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.2,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 1400,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 2.1,
          "bound": "exact"
        }
      },
      {
        "name": "Kazakhstan",
        "production": {
          "tonnes": 130,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.9,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 2300,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3.5,
          "bound": "exact"
        }
      },
      {
        "name": "Uzbekistan",
        "production": {
          "tonnes": 130,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.9,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 2200,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3.3,
          "bound": "exact"
        }
      },
      {
        "name": "Peru",
        "production": {
          "tonnes": 110,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.3,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 2200,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3.3,
          "bound": "exact"
        }
      },
      {
        "name": "South Africa",
        "production": {
          "tonnes": 90,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.7,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 5000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 7.6,
          "bound": "exact"
        }
      },
      {
        "name": "Indonesia",
        "production": {
          "tonnes": 90,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.7,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 3600,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 5.5,
          "bound": "exact"
        }
      },
      {
        "name": "Brazil",
        "production": {
          "tonnes": 80,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.4,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 2500,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3.8,
          "bound": "exact"
        }
      }
    ]
  },
  "Silver": {
    "measure": "Mine production",
    "year": "2025",
    "worldProduction": {
      "tonnes": 26000,
      "lowerBound": false
    },
    "worldReserves": {
      "tonnes": 610000,
      "lowerBound": false
    },
    "countries": [
      {
        "name": "Mexico",
        "production": {
          "tonnes": 6300,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 24.2,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 37000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 6.1,
          "bound": "exact"
        }
      },
      {
        "name": "Peru",
        "production": {
          "tonnes": 3600,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 13.8,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 110000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 18,
          "bound": "exact"
        }
      },
      {
        "name": "China",
        "production": {
          "tonnes": 3400,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 13.1,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 67000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 11,
          "bound": "exact"
        }
      },
      {
        "name": "Bolivia",
        "production": {
          "tonnes": 1500,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 5.8,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 22000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3.6,
          "bound": "exact"
        }
      },
      {
        "name": "Chile",
        "production": {
          "tonnes": 1400,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 5.4,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 33000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 5.4,
          "bound": "exact"
        }
      },
      {
        "name": "Poland",
        "production": {
          "tonnes": 1300,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 5,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 59000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 9.7,
          "bound": "exact"
        }
      },
      {
        "name": "Russia",
        "production": {
          "tonnes": 1200,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.6,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 92000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 15.1,
          "bound": "exact"
        }
      },
      {
        "name": "United States",
        "production": {
          "tonnes": 1100,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.2,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 23000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 3.8,
          "bound": "exact"
        }
      },
      {
        "name": "Australia",
        "production": {
          "tonnes": 1000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.8,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 91000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 14.9,
          "bound": "exact"
        }
      },
      {
        "name": "India",
        "production": {
          "tonnes": 800,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.1,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 8000,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.3,
          "bound": "exact"
        }
      },
      {
        "name": "Argentina",
        "production": {
          "tonnes": 800,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.1,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 6500,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 1.1,
          "bound": "exact"
        }
      },
      {
        "name": "Kazakhstan",
        "production": {
          "tonnes": 630,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.4,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Canada",
        "production": {
          "tonnes": 400,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.5,
          "bound": "exact"
        },
        "reserves": {
          "tonnes": 4900,
          "lowerBound": false
        },
        "reservesShare": {
          "pct": 0.8,
          "bound": "exact"
        }
      },
      {
        "name": "Sweden",
        "production": {
          "tonnes": 400,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.5,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      }
    ]
  },
  "Aluminum": {
    "measure": "Smelter production (primary aluminum)",
    "year": "2025",
    "worldProduction": {
      "tonnes": 74000000,
      "lowerBound": false
    },
    "worldReserves": null,
    "countries": [
      {
        "name": "China",
        "production": {
          "tonnes": 45000000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 60.8,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "India",
        "production": {
          "tonnes": 4200000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 5.7,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Russia",
        "production": {
          "tonnes": 3900000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 5.3,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Canada",
        "production": {
          "tonnes": 3300000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 4.5,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "United Arab Emirates",
        "production": {
          "tonnes": 2700000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 3.6,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Bahrain",
        "production": {
          "tonnes": 1600000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2.2,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Australia",
        "production": {
          "tonnes": 1500000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 2,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Norway",
        "production": {
          "tonnes": 1300000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.8,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Brazil",
        "production": {
          "tonnes": 1200000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.6,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Malaysia",
        "production": {
          "tonnes": 1100000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1.5,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "Iceland",
        "production": {
          "tonnes": 750000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 1,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      },
      {
        "name": "United States",
        "production": {
          "tonnes": 660000,
          "lowerBound": false
        },
        "productionShare": {
          "pct": 0.9,
          "bound": "exact"
        },
        "reserves": null,
        "reservesShare": null
      }
    ]
  }
};
