/**
 * Total energy production and consumption per US state and DC, in TWh, for
 * 2024.
 *
 * GENERATED by build-state-energy.cjs on 2026-09-30 — do not edit by hand;
 * change the script and re-run it.
 *
 * US EIA State Energy Data System: total primary energy production (TEPRB)
 * and total energy consumption (TETCB), converted from billion Btu at
 * 293.07107 TWh per quadrillion Btu, as the countries' EIA figures are.
 */
export const STATE_ENERGY_SOURCE = {
  label: "US EIA — State Energy Data System",
  url: "https://www.eia.gov/state/seds/",
  retrieved: "2026-09-30",
};

export const STATE_ENERGY_YEAR = 2024;

/** By lowercase state code, as statesData.ts keys them. */
export const STATE_ENERGY: Record<string, { totalUseTWh: number; totalProductionTWh: number }> = {
  "al": { totalUseTWh: 559, totalProductionTWh: 335 },
  "ak": { totalUseTWh: 223, totalProductionTWh: 387 },
  "az": { totalUseTWh: 460, totalProductionTWh: 127 },
  "ar": { totalUseTWh: 311, totalProductionTWh: 189 },
  "ca": { totalUseTWh: 2009, totalProductionTWh: 501 },
  "co": { totalUseTWh: 394, totalProductionTWh: 1065 },
  "ct": { totalUseTWh: 208, totalProductionTWh: 62.1 },
  "de": { totalUseTWh: 76.7, totalProductionTWh: 0.9 },
  "dc": { totalUseTWh: 40.6, totalProductionTWh: 0.6 },
  "fl": { totalUseTWh: 1277, totalProductionTWh: 158 },
  "ga": { totalUseTWh: 868, totalProductionTWh: 228 },
  "hi": { totalUseTWh: 79.7, totalProductionTWh: 5.2 },
  "id": { totalUseTWh: 145, totalProductionTWh: 22.7 },
  "il": { totalUseTWh: 1007, totalProductionTWh: 637 },
  "in": { totalUseTWh: 745, totalProductionTWh: 219 },
  "ia": { totalUseTWh: 410, totalProductionTWh: 242 },
  "ks": { totalUseTWh: 281, totalProductionTWh: 174 },
  "ky": { totalUseTWh: 482, totalProductionTWh: 213 },
  "la": { totalUseTWh: 1250, totalProductionTWh: 1265 },
  "me": { totalUseTWh: 97.7, totalProductionTWh: 25.9 },
  "md": { totalUseTWh: 352, totalProductionTWh: 63.6 },
  "ma": { totalUseTWh: 378, totalProductionTWh: 17.2 },
  "mi": { totalUseTWh: 740, totalProductionTWh: 166 },
  "mn": { totalUseTWh: 483, totalProductionTWh: 127 },
  "ms": { totalUseTWh: 314, totalProductionTWh: 86.3 },
  "mo": { totalUseTWh: 489, totalProductionTWh: 66.5 },
  "mt": { totalUseTWh: 108, totalProductionTWh: 223 },
  "ne": { totalUseTWh: 248, totalProductionTWh: 117 },
  "nv": { totalUseTWh: 203, totalProductionTWh: 22.4 },
  "nh": { totalUseTWh: 87.3, totalProductionTWh: 38.8 },
  "nj": { totalUseTWh: 579, totalProductionTWh: 96.3 },
  "nm": { totalUseTWh: 200, totalProductionTWh: 2498 },
  "ny": { totalUseTWh: 995, totalProductionTWh: 152 },
  "nc": { totalUseTWh: 753, totalProductionTWh: 184 },
  "nd": { totalUseTWh: 211, totalProductionTWh: 1357 },
  "oh": { totalUseTWh: 1006, totalProductionTWh: 883 },
  "ok": { totalUseTWh: 450, totalProductionTWh: 1248 },
  "or": { totalUseTWh: 262, totalProductionTWh: 59.9 },
  "pa": { totalUseTWh: 1059, totalProductionTWh: 2905 },
  "ri": { totalUseTWh: 55.1, totalProductionTWh: 2.3 },
  "sc": { totalUseTWh: 482, totalProductionTWh: 202 },
  "sd": { totalUseTWh: 102, totalProductionTWh: 74.8 },
  "tn": { totalUseTWh: 613, totalProductionTWh: 132 },
  "tx": { totalUseTWh: 4260, totalProductionTWh: 8290 },
  "ut": { totalUseTWh: 251, totalProductionTWh: 271 },
  "vt": { totalUseTWh: 33.5, totalProductionTWh: 5.5 },
  "va": { totalUseTWh: 724, totalProductionTWh: 234 },
  "wa": { totalUseTWh: 471, totalProductionTWh: 135 },
  "wv": { totalUseTWh: 245, totalProductionTWh: 1847 },
  "wi": { totalUseTWh: 482, totalProductionTWh: 88 },
  "wy": { totalUseTWh: 149, totalProductionTWh: 1523 },
};
