/**
 * What each university named in a state's window is: Wikidata's one-line
 * description of it, the year it was founded, and its English Wikipedia
 * article.
 *
 * GENERATED by build-state-universities.cjs on 2026-10-07 — do not edit by hand;
 * change the script and re-run it.
 *
 * The schools are the site's own list (STATE_EDUCATION in
 * src/pages/StatesPage.tsx). Each was matched to an article that Wikidata
 * (CC0) classes as a higher education institution and places in that state;
 * a school that could not be matched on both is not here, and its row in
 * the window is its name alone. The founding year is Wikidata's, given only
 * where the article's own infobox has the same year.
 *
 * What each is about and known for is not stored here: the window quotes
 * the opening of its Wikipedia article when a reader opens the row.
 */
export const STATE_UNIVERSITIES_SOURCE = {
  label: "Wikidata — each school's description and founding year (CC0)",
  url: "https://www.wikidata.org/wiki/Q38723",
  retrieved: "2026-10-07",
};

export interface SchoolArticle {
  /** Its English Wikipedia article. */
  wiki: string;
  /** Wikidata's one-line description. */
  about?: string;
  /** The year it was founded, where Wikidata gives one and the article's infobox agrees. */
  founded?: number;
}

/** Keyed by the state id used in statesData.ts, then by the school's name as the window lists it. */
export const STATE_UNIVERSITIES: Record<string, Record<string, SchoolArticle>> = {
  al: {
    "University of Alabama": {"wiki":"University of Alabama","about":"public university located in Tuscaloosa, Alabama, United States"},
    "Auburn University": {"wiki":"Auburn University","about":"public university in Auburn, Alabama, United States","founded":1856},
    "University of Alabama at Birmingham (UAB)": {"wiki":"University of Alabama at Birmingham","about":"public university in Birmingham, Alabama","founded":1969},
    "Alabama A&M University": {"wiki":"Alabama A&M University","about":"historically black land grant university","founded":1875},
  },
  ak: {
    "University of Alaska Fairbanks": {"wiki":"University of Alaska Fairbanks","about":"university","founded":1917},
    "University of Alaska Anchorage": {"wiki":"University of Alaska Anchorage","about":"university in Anchorage, Alaska, United States","founded":1954},
    "Alaska Pacific University": {"wiki":"Alaska Pacific University","about":"private university in Anchorage, Alaska, United States","founded":1957},
  },
  az: {
    "Arizona State University (ASU)": {"wiki":"Arizona State University","about":"public university in Tempe, Arizona, US","founded":1885},
    "University of Arizona": {"wiki":"University of Arizona","about":"public university in Tucson, Arizona, United States","founded":1885},
    "Grand Canyon University": {"wiki":"Grand Canyon University","about":"private Christian university in Phoenix, Arizona","founded":1949},
  },
  ar: {
    "University of Arkansas": {"wiki":"University of Arkansas","about":"public research university in Fayetteville, Arkansas, USA","founded":1871},
    "Arkansas Tech University": {"wiki":"Arkansas Tech University","about":"public university in Russellville, Arkansas","founded":1909},
    "Hendrix College": {"wiki":"Hendrix College","about":"Arkansas liberal arts college","founded":1876},
  },
  ca: {
    "Stanford University": {"wiki":"Stanford University","about":"private research university in Stanford, California, USA","founded":1885},
    "Caltech (Pasadena)": {"wiki":"California Institute of Technology","about":"private research university located in Pasadena, California, USA","founded":1891},
    "UC Berkeley": {"wiki":"University of California, Berkeley","about":"public university in Berkeley, California, USA","founded":1868},
    "UCLA": {"wiki":"University of California, Los Angeles","about":"public university in Los Angeles, California, USA"},
    "USC": {"wiki":"University of Southern California","about":"private university in Los Angeles, California, United States","founded":1880},
  },
  co: {
    "University of Colorado Boulder (CU)": {"wiki":"University of Colorado Boulder","about":"public university in Boulder, Colorado, United States, and flagship of the University of Colorado System","founded":1876},
    "Colorado State University": {"wiki":"Colorado State University","about":"public land-grant research university in Fort Collins, Colorado, United States","founded":1870},
    "Colorado School of Mines": {"wiki":"Colorado School of Mines","about":"public university in Golden, Colorado, U.S."},
    "University of Denver": {"wiki":"University of Denver","about":"private university in the Rocky Mountain Region of the United States","founded":1864},
  },
  ct: {
    "Yale University": {"wiki":"Yale University","about":"private university in New Haven, Connecticut","founded":1701},
    "University of Connecticut (UConn)": {"wiki":"University of Connecticut","about":"public research university in Storrs, Connecticut, United States","founded":1881},
    "Wesleyan University": {"wiki":"Wesleyan University","about":"private liberal arts college in Middletown, Connecticut, United States","founded":1831},
    "Trinity College": {"wiki":"Trinity College (Connecticut)","about":"college in Hartford, Connecticut","founded":1823},
  },
  de: {
    "University of Delaware": {"wiki":"University of Delaware","about":"university in Newark, Delaware, Untied States","founded":1743},
    "Delaware State University": {"wiki":"Delaware State University","about":"university","founded":1891},
    "Widener University (DE campus)": {"wiki":"Widener University Delaware Law School","about":"law school in Delaware","founded":1971},
  },
  fl: {
    "University of Florida (UF Gainesville)": {"wiki":"University of Florida","about":"public research university in Gainesville, Florida, United States","founded":1853},
    "Florida State University (FSU)": {"wiki":"Florida State University","about":"public university in Tallahassee, Florida, United States","founded":1851},
    "University of Miami": {"wiki":"University of Miami","about":"private university in Coral Gables, Florida, United States","founded":1925},
    "Florida International University (FIU)": {"wiki":"Florida International University","about":"public research university in Westchester, Florida, United States","founded":1965},
  },
  ga: {
    "Georgia Institute of Technology (Georgia Tech)": {"wiki":"Georgia Tech","about":"public research university in Atlanta, Georgia, United States","founded":1885},
    "Emory University": {"wiki":"Emory University","about":"private research university in Atlanta, Georgia, United States","founded":1836},
    "University of Georgia (UGA)": {"wiki":"University of Georgia","about":"public university located in Athens, Georgia, United States","founded":1785},
    "Spelman College": {"wiki":"Spelman College","about":"historically Black women's college in Atlanta, Georgia, United States","founded":1881},
  },
  hi: {
    "University of Hawaii at Manoa": {"wiki":"University of Hawaiʻi at Mānoa","about":"public co-educational research university and flagship University of Hawaiʻi system","founded":1907},
    "Hawaii Pacific University": {"wiki":"Hawaii Pacific University","about":"university","founded":1965},
    "Chaminade University": {"wiki":"Chaminade University of Honolulu","about":"Marianist university in Hawaii, U.S.","founded":1955},
  },
  id: {
    "University of Idaho": {"wiki":"University of Idaho","about":"public research university in Moscow, Idaho, United States","founded":1889},
    "Boise State University": {"wiki":"Boise State University","about":"public research university in Boise, Idaho, USA","founded":1932},
    "Idaho State University": {"wiki":"Idaho State University","about":"research university in eastern Idaho, USA","founded":1901},
  },
  il: {
    "University of Chicago": {"wiki":"University of Chicago","about":"private university in Chicago, Illinois","founded":1890},
    "Northwestern University": {"wiki":"Northwestern University","about":"private university in Evanston, Illinois, U.S.","founded":1851},
    "University of Illinois Urbana-Champaign (UIUC)": {"wiki":"University of Illinois Urbana-Champaign","about":"public research university in Urbana and Champaign, Illinois, United States","founded":1867},
    "DePaul University": {"wiki":"DePaul University","about":"private Catholic university in Chicago, Illinois, USA","founded":1898},
  },
  in: {
    "Notre Dame (University of Notre Dame)": {"wiki":"University of Notre Dame","about":"Catholic university located in Notre Dame, Indiana, United States","founded":1842},
    "Purdue University": {"wiki":"Purdue University","about":"public research university in West Lafayette, Indiana, United States","founded":1869},
    "Indiana University Bloomington (IU)": {"wiki":"Indiana University Bloomington","about":"public research university located in Bloomington, Indiana, U.S. (flagship campus of the Indiana University system)","founded":1820},
    "Butler University": {"wiki":"Butler University","about":"private university in Indianapolis, Indiana, United States","founded":1855},
  },
  ia: {
    "University of Iowa": {"wiki":"University of Iowa","about":"public research university in Iowa City, Iowa, United States","founded":1847},
    "Iowa State University": {"wiki":"Iowa State University","about":"public research university in Ames, Iowa, United States","founded":1858},
    "Grinnell College": {"wiki":"Grinnell College","about":"liberal arts college in Iowa, United States","founded":1846},
    "Drake University": {"wiki":"Drake University","about":"private university in Des Moines, Iowa","founded":1881},
  },
  ks: {
    "University of Kansas (KU Lawrence)": {"wiki":"University of Kansas","about":"public research university in Kansas, United States"},
    "Kansas State University (K-State)": {"wiki":"Kansas State University","about":"public university in the state of Kansas","founded":1863},
    "Wichita State University": {"wiki":"Wichita State University","about":"public university in Wichita, Kansas, U.S."},
  },
  ky: {
    "University of Kentucky (UK)": {"wiki":"University of Kentucky","about":"public university in the United States","founded":1865},
    "University of Louisville": {"wiki":"University of Louisville","about":"public university in Kentucky","founded":1798},
    "Berea College": {"wiki":"Berea College","about":"liberal arts work college in Kentucky, USA","founded":1855},
    "Centre College": {"wiki":"Centre College","about":"private liberal arts college in Danville, Kentucky, U.S.","founded":1819},
  },
  la: {
    "Tulane University": {"wiki":"Tulane University","about":"private research university in New Orleans, Louisiana, United States","founded":1834},
    "Louisiana State University (LSU)": {"wiki":"Louisiana State University","about":"public university in Baton Rouge, Louisiana, United States","founded":1860},
    "Xavier University of Louisiana": {"wiki":"Xavier University of Louisiana","about":"Catholic university in the U.S state of Louisiana"},
    "Loyola University New Orleans": {"wiki":"Loyola University New Orleans","about":"private Jesuit university in New Orleans, Louisiana, United States","founded":1904},
  },
  me: {
    "Bowdoin College": {"wiki":"Bowdoin College","about":"private liberal arts college in Brunswick, Maine","founded":1794},
    "Colby College": {"wiki":"Colby College","about":"private liberal arts college located in Waterville, Maine, USA","founded":1813},
    "Bates College": {"wiki":"Bates College","about":"private liberal arts college in Lewiston, Maine","founded":1855},
    "University of Maine": {"wiki":"University of Maine","about":"public research university in Orono, Maine, United States","founded":1865},
  },
  md: {
    "Johns Hopkins University": {"wiki":"Johns Hopkins University","about":"private university in Baltimore, Maryland, USA","founded":1876},
    "University of Maryland, College Park": {"wiki":"University of Maryland, College Park","about":"public research university in the city of College Park in Prince George's County, Maryland, USA","founded":1856},
    "United States Naval Academy": {"wiki":"United States Naval Academy","about":"U.S. Navy federal service academy in the Annapolis, Maryland area","founded":1845},
    "Loyola University Maryland": {"wiki":"Loyola University Maryland","about":"Jesuit liberal arts university in Baltimore, Maryland","founded":1852},
  },
  ma: {
    "MIT (Massachusetts Institute of Technology)": {"wiki":"Massachusetts Institute of Technology","about":"private university in Cambridge, Massachusetts, USA, founded 1861","founded":1861},
    "Harvard University": {"wiki":"Harvard University","about":"private university in Cambridge, Massachusetts","founded":1636},
    "Tufts University": {"wiki":"Tufts University","about":"private research university in Medford/Somerville, Massachusetts","founded":1852},
    "Boston University": {"wiki":"Boston University","about":"private research university in Boston, Massachusetts, United States"},
    "Amherst College": {"wiki":"Amherst College","about":"liberal arts college in Massachusetts","founded":1821},
  },
  mi: {
    "University of Michigan (Ann Arbor)": {"wiki":"University of Michigan","about":"public research university in Ann Arbor, Michigan","founded":1817},
    "Michigan State University (MSU)": {"wiki":"Michigan State University","about":"public research university in East Lansing, Michigan, United States","founded":1855},
    "Wayne State University": {"wiki":"Wayne State University","about":"American public research university located in Detroit, Michigan","founded":1868},
    "Kalamazoo College": {"wiki":"Kalamazoo College","about":"private liberal-arts college in Kalamazoo, Michigan, USA","founded":1833},
  },
  mn: {
    "University of Minnesota Twin Cities": {"wiki":"University of Minnesota","about":"public research university in Minneapolis and Saint Paul, Minnesota, United States","founded":1851},
    "Carleton College": {"wiki":"Carleton College","about":"liberal arts college in Northfield, Minnesota","founded":1866},
    "Macalester College": {"wiki":"Macalester College","about":"private liberal arts college in Saint Paul, Minnesota","founded":1874},
    "St. Olaf College": {"wiki":"St. Olaf College","about":"four-year Lutheran liberal-arts college in Northfield, Minnesota","founded":1874},
  },
  ms: {
    "University of Mississippi (Ole Miss)": {"wiki":"University of Mississippi","about":"public university in the United States"},
    "Mississippi State University": {"wiki":"Mississippi State University","about":"public university near Starkville, Mississippi, United States","founded":1878},
    "Tougaloo College": {"wiki":"Tougaloo College","about":"historically black college in Tougaloo, Mississippi, United States","founded":1869},
    "Millsaps College": {"wiki":"Millsaps College","about":"private liberal arts college in Jackson, Mississippi, United States","founded":1890},
  },
  mo: {
    "Washington University in St. Louis (WashU)": {"wiki":"Washington University in St. Louis","about":"private research university in St. Louis, Missouri, United States","founded":1853},
    "University of Missouri (Mizzou)": {"wiki":"University of Missouri","about":"public research university in Columbia, Missouri, USA","founded":1839},
    "Saint Louis University": {"wiki":"Saint Louis University","about":"private research university with campuses in St. Louis, Missouri, and Madrid, Spain","founded":1818},
    "Truman State University": {"wiki":"Truman State University","about":"university in Missouri, United States","founded":1867},
  },
  mt: {
    "University of Montana": {"wiki":"University of Montana","about":"public research university located in Missoula, Montana","founded":1893},
    "Montana State University (MSU Bozeman)": {"wiki":"Montana State University","about":"public land-grant research university in Bozeman, Montana, United States","founded":1893},
    "Carroll College": {"wiki":"Carroll College","about":"college located in Helena, Montana, United States","founded":1909},
  },
  ne: {
    "University of Nebraska-Lincoln (UNL)": {"wiki":"University of Nebraska–Lincoln","about":"public university in Lincoln, Nebraska, United States","founded":1869},
    "Creighton University": {"wiki":"Creighton University","about":"private Jesuit university in Omaha, Nebraska, U.S.","founded":1878},
    "Nebraska Wesleyan University": {"wiki":"Nebraska Wesleyan University","about":"university in Lincoln, Nebraska, United States","founded":1887},
  },
  nv: {
    "University of Nevada, Las Vegas (UNLV)": {"wiki":"University of Nevada, Las Vegas","about":"public research university in Paradise, Nevada, United States","founded":1957},
    "University of Nevada, Reno (UNR)": {"wiki":"University of Nevada, Reno","about":"public research university in Reno, Nevada, United States","founded":1874},
    "Nevada State University": {"wiki":"Nevada State University","about":"four-year public college located in Henderson, Nevada","founded":2002},
  },
  nh: {
    "Dartmouth College": {"wiki":"Dartmouth College","about":"private university in Hanover, New Hampshire, US","founded":1769},
    "University of New Hampshire (UNH)": {"wiki":"University of New Hampshire","about":"public research university in New Hampshire, United States","founded":1866},
    "Keene State College": {"wiki":"Keene State College","about":"Public university in New Hampshire, United States","founded":1909},
  },
  nj: {
    "Princeton University": {"wiki":"Princeton University","about":"private Ivy League research university in Princeton, New Jersey, United States","founded":1746},
    "Rutgers University–New Brunswick": {"wiki":"Rutgers University–New Brunswick","about":"largest campus of Rutgers University in New Brunswick and Piscataway, New Jersey","founded":1766},
    "Stevens Institute of Technology": {"wiki":"Stevens Institute of Technology","about":"higher education institute in Hoboken, New Jersey, USA","founded":1870},
    "Seton Hall University": {"wiki":"Seton Hall University","about":"private Roman Catholic university in South Orange, New Jersey","founded":1856},
  },
  nm: {
    "University of New Mexico (UNM)": {"wiki":"University of New Mexico","about":"public research university in Albuquerque, New Mexico, United States","founded":1889},
    "New Mexico State University (NMSU)": {"wiki":"New Mexico State University","about":"university in the United States","founded":1888},
    "New Mexico Institute of Mining & Technology (NM Tech)": {"wiki":"New Mexico Institute of Mining and Technology","about":"university in the United States","founded":1889},
  },
  ny: {
    "Columbia University": {"wiki":"Columbia University","about":"private university in New York City, New York, US","founded":1754},
    "Cornell University": {"wiki":"Cornell University","about":"private and statutory land-grant research university in Ithaca, New York, USA","founded":1865},
    "New York University (NYU)": {"wiki":"New York University","about":"private university in New York City","founded":1831},
    "Rensselaer Polytechnic Institute (RPI)": {"wiki":"Rensselaer Polytechnic Institute","about":"private research university in Troy, New York","founded":1824},
    "Vassar College": {"wiki":"Vassar College","about":"private, coeducational liberal arts college in the Town of Poughkeepsie, New York, in the United States","founded":1861},
  },
  nc: {
    "Duke University": {"wiki":"Duke University","about":"private university in Durham, North Carolina, USA","founded":1838},
    "UNC Chapel Hill": {"wiki":"University of North Carolina at Chapel Hill","about":"public research university in Chapel Hill, North Carolina, United States","founded":1789},
    "Wake Forest University": {"wiki":"Wake Forest University","about":"university in Winston-Salem, North Carolina, United States","founded":1834},
    "NC State University": {"wiki":"North Carolina State University","about":"public research university in Raleigh, North Carolina, United States","founded":1887},
  },
  nd: {
    "University of North Dakota (UND)": {"wiki":"University of North Dakota","about":"public university in North Dakota, United States of America","founded":1883},
    "North Dakota State University (NDSU)": {"wiki":"North Dakota State University","about":"public university in Fargo, North Dakota","founded":1890},
    "Bismarck State College": {"wiki":"Bismarck State College","about":"a polytechnic institution in Bismarck, North Dakota","founded":1939},
  },
  oh: {
    "Ohio State University (Columbus)": {"wiki":"Ohio State University","about":"public research university in Columbus, Ohio, United States","founded":1870},
    "Case Western Reserve University": {"wiki":"Case Western Reserve University","about":"private university in Ohio, United States"},
    "Oberlin College": {"wiki":"Oberlin College","about":"private liberal arts college in Oberlin, Ohio, United States","founded":1833},
    "University of Cincinnati": {"wiki":"University of Cincinnati","about":"public research university in Cincinnati, Ohio, USA","founded":1819},
  },
  ok: {
    "University of Oklahoma (OU Norman)": {"wiki":"University of Oklahoma","about":"public research university in Norman, Oklahoma, United States","founded":1890},
    "Oklahoma State University (OSU)": {"wiki":"Oklahoma State University","about":"public university in Oklahoma, United States of America","founded":1890},
    "Oral Roberts University": {"wiki":"Oral Roberts University","about":"interdenominational, Christian, comprehensive liberal arts university","founded":1963},
    "University of Tulsa": {"wiki":"University of Tulsa","about":"university in Oklahoma, United States","founded":1894},
  },
  or: {
    "University of Oregon (UO Eugene)": {"wiki":"University of Oregon","about":"public research university in Eugene, Oregon, USA"},
    "Oregon State University (OSU)": {"wiki":"Oregon State University","about":"public research university in Corvallis, Oregon, United States"},
    "Reed College": {"wiki":"Reed College","about":"private liberal arts college in Portland, Oregon","founded":1908},
    "Lewis & Clark College": {"wiki":"Lewis & Clark College","about":"private liberal arts college in Portland, Oregon, United States","founded":1867},
  },
  pa: {
    "University of Pennsylvania (Penn)": {"wiki":"University of Pennsylvania","about":"private research university in Philadelphia, Pennsylvania, United States","founded":1740},
    "Carnegie Mellon University (CMU)": {"wiki":"Carnegie Mellon University","about":"private research university in Pittsburgh, Pennsylvania, United States","founded":1900},
    "Villanova University": {"wiki":"Villanova University","about":"Catholic university near Philadelphia, Pennsylvania","founded":1842},
    "Penn State University Park": {"wiki":"Pennsylvania State University","about":"public university in Pennsylvania, United States","founded":1855},
    "Swarthmore College": {"wiki":"Swarthmore College","about":"liberal arts college in Swarthmore, Pennsylvania","founded":1864},
  },
  ri: {
    "Brown University": {"wiki":"Brown University","about":"private university in Providence, Rhode Island, United States"},
    "Rhode Island School of Design (RISD)": {"wiki":"Rhode Island School of Design","about":"private art and design college in Providence, Rhode Island, USA","founded":1877},
    "Roger Williams University": {"wiki":"Roger Williams University","about":"Rhode Island, United States","founded":1956},
  },
  sc: {
    "Clemson University": {"wiki":"Clemson University","about":"public university in South Carolina, United States","founded":1889},
    "University of South Carolina (UofSC)": {"wiki":"University of South Carolina","about":"public university in Columbia, South Carolina","founded":1801},
    "College of Charleston": {"wiki":"College of Charleston","about":"liberal arts college in Charleston, South Carolina, USA","founded":1770},
    "Furman University": {"wiki":"Furman University","about":"private liberal arts college in Greenville, South Carolina, United States","founded":1826},
  },
  sd: {
    "South Dakota State University (SDSU)": {"wiki":"South Dakota State University","about":"public university in Brookings, South Dakota, US","founded":1881},
    "University of South Dakota (USD)": {"wiki":"University of South Dakota","about":"public research university located in Vermillion, South Dakota, USA","founded":1862},
    "Augustana University": {"wiki":"Augustana University","about":"private Lutheran university in Sioux Falls, South Dakota, USA","founded":1860},
  },
  tn: {
    "Vanderbilt University": {"wiki":"Vanderbilt University","about":"private university in Nashville, Tennessee, US","founded":1873},
    "University of Tennessee Knoxville (UTK)": {"wiki":"University of Tennessee","about":"public university in Knoxville, Tennessee, United States","founded":1794},
    "Rhodes College": {"wiki":"Rhodes College","about":"private, four-year liberal arts college in Memphis, Tennessee","founded":1848},
    "Fisk University": {"wiki":"Fisk University","about":"historically black university in Nashville, Tennessee, US","founded":1866},
  },
  tx: {
    "University of Texas at Austin (UT Austin)": {"wiki":"University of Texas at Austin","about":"public university in Austin, Texas, USA","founded":1883},
    "Rice University": {"wiki":"Rice University","about":"private university in Houston, Texas, USA"},
    "Texas A&M University": {"wiki":"Texas A&M University","about":"public research university in College Station, Texas, United States","founded":1876},
    "SMU (Southern Methodist University)": {"wiki":"Southern Methodist University","about":"private university in Dallas, Texas, United States","founded":1911},
  },
  ut: {
    "University of Utah": {"wiki":"University of Utah","about":"public coeducational space-grant research university in Salt Lake City, Utah, United States","founded":1850},
    "Brigham Young University (BYU)": {"wiki":"Brigham Young University","about":"private research university in Provo, Utah, United States","founded":1875},
    "Utah State University (USU)": {"wiki":"Utah State University","about":"public university in Logan, Utah, United States","founded":1888},
    "Westminster University": {"wiki":"Westminster University (Utah)","about":"Liberal arts university in Salt Lake City, Utah, United States","founded":1875},
  },
  vt: {
    "Middlebury College": {"wiki":"Middlebury College","about":"private college in Middlebury, Vermont, US","founded":1800},
    "University of Vermont (UVM)": {"wiki":"University of Vermont","about":"public research university in Burlington, Vermont, USA","founded":1791},
    "Norwich University": {"wiki":"Norwich University","about":"military college in Vermont","founded":1819},
  },
  va: {
    "University of Virginia (UVA)": {"wiki":"University of Virginia","about":"public university in Charlottesville, Virginia","founded":1819},
    "William & Mary": {"wiki":"College of William & Mary","about":"public university in Williamsburg, Virginia","founded":1693},
    "Virginia Tech (VT)": {"wiki":"Virginia Tech","about":"public university with the main campus in Blacksburg, Virginia","founded":1872},
    "Washington and Lee University": {"wiki":"Washington and Lee University","about":"private liberal arts university in Lexington, Virginia","founded":1749},
  },
  wa: {
    "University of Washington (UW Seattle)": {"wiki":"University of Washington","about":"public research university in Seattle, Washington, United States","founded":1861},
    "Washington State University (WSU)": {"wiki":"Washington State University","about":"public university in Pullman, Washington, USA"},
    "Whitman College": {"wiki":"Whitman College","about":"private liberal arts college, located in Walla Walla, Washington, USA","founded":1859},
    "Seattle University": {"wiki":"Seattle University","about":"Jesuit university in Seattle, Washington, USA","founded":1891},
  },
  wv: {
    "West Virginia University (WVU)": {"wiki":"West Virginia University","about":"public university in Morgantown, West Virginia, United States","founded":1867},
    "Marshall University": {"wiki":"Marshall University","about":"public research university in Huntington, West Virginia, United States","founded":1837},
    "Bethany College": {"wiki":"Bethany College (West Virginia)","about":"private liberal arts college located in Bethany, West Virginia","founded":1840},
  },
  wi: {
    "University of Wisconsin-Madison (UW)": {"wiki":"University of Wisconsin–Madison","about":"public research university in Madison, Wisconsin, USA","founded":1848},
    "Marquette University": {"wiki":"Marquette University","about":"private university in Milwaukee, Wisconsin, US","founded":1881},
    "Lawrence University": {"wiki":"Lawrence University","about":"liberal arts college and conservatory of music, in Appleton, Wisconsin","founded":1847},
    "Carroll University": {"wiki":"Carroll University","about":"university","founded":1846},
  },
  wy: {
    "University of Wyoming (UW Laramie)": {"wiki":"University of Wyoming","about":"public university in Laramie, Wyoming","founded":1886},
    "Western Wyoming Community College": {"wiki":"Western Wyoming College","about":"college in Rock Springs, Wyoming, U.S.","founded":1959},
  },
};
